"""increase financial_statements value precision to numeric 38 6

Revision ID: 6b106e82ce20
Revises: b0b30daa80c5
Create Date: 2026-01-31 12:16:58.700181

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b106e82ce20"
down_revision: str | Sequence[str] | None = "b0b30daa80c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_statements",
        "value",
        existing_type=sa.NUMERIC(precision=20, scale=6),
        type_=sa.Numeric(precision=38, scale=6),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_statements",
        "value",
        existing_type=sa.Numeric(precision=38, scale=6),
        type_=sa.NUMERIC(precision=20, scale=6),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
