"""normalize instruments: drop exchange_name, add indexes and unique constraint

Revision ID: c51c70973022
Revises: bdd615f586f8
Create Date: 2026-01-30 15:21:07.541524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51c70973022'
down_revision: Union[str, Sequence[str], None] = 'bdd615f586f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_instrument_exchange_id', 'instruments', ['exchange_id'], unique=False)
    op.create_index('ix_instrument_isin', 'instruments', ['isin'], unique=False)
    op.create_index('ix_instrument_yfinance_ticker', 'instruments', ['yfinance_ticker'], unique=False)
    op.create_index(op.f('ix_instruments_ticker'), 'instruments', ['ticker'], unique=False)
    op.create_unique_constraint('uq_instrument_ticker_exchange', 'instruments', ['ticker', 'exchange_id'])
    op.drop_column('instruments', 'exchange_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('exchange_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('uq_instrument_ticker_exchange', 'instruments', type_='unique')
    op.drop_index(op.f('ix_instruments_ticker'), table_name='instruments')
    op.drop_index('ix_instrument_yfinance_ticker', table_name='instruments')
    op.drop_index('ix_instrument_isin', table_name='instruments')
    op.drop_index('ix_instrument_exchange_id', table_name='instruments')
    # ### end Alembic commands ###