# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyBusinessCycleWithLLM(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BusinessCycleClassification:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyBusinessCycleWithLLM", llm_response=llm_response, mode="request")
        return typing.cast(types.BusinessCycleClassification, __result__)

    def GenerateBlackLittermanView(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BlackLittermanView:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateBlackLittermanView", llm_response=llm_response, mode="request")
        return typing.cast(types.BlackLittermanView, __result__)

    def GenerateStockSignal(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StockSignalOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateStockSignal", llm_response=llm_response, mode="request")
        return typing.cast(types.StockSignalOutput, __result__)

    def RecommendBlackLittermanParameters(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BlackLittermanParameters:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RecommendBlackLittermanParameters", llm_response=llm_response, mode="request")
        return typing.cast(types.BlackLittermanParameters, __result__)

    def SummarizeNewsArticles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MacroNewsSignals:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeNewsArticles", llm_response=llm_response, mode="request")
        return typing.cast(types.MacroNewsSignals, __result__)

    def SummarizeStockNews(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StockNewsSignals:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeStockNews", llm_response=llm_response, mode="request")
        return typing.cast(types.StockNewsSignals, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyBusinessCycleWithLLM(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BusinessCycleClassification:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyBusinessCycleWithLLM", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BusinessCycleClassification, __result__)

    def GenerateBlackLittermanView(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BlackLittermanView:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateBlackLittermanView", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BlackLittermanView, __result__)

    def GenerateStockSignal(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StockSignalOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateStockSignal", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StockSignalOutput, __result__)

    def RecommendBlackLittermanParameters(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BlackLittermanParameters:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RecommendBlackLittermanParameters", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BlackLittermanParameters, __result__)

    def SummarizeNewsArticles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MacroNewsSignals:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeNewsArticles", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MacroNewsSignals, __result__)

    def SummarizeStockNews(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StockNewsSignals:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeStockNews", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StockNewsSignals, __result__)

    