# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (42)
# #########################################################################

class BlackLittermanParameters(BaseModel):
    tau: typing.Optional[float] = None
    delta: typing.Optional[float] = None
    strong_buy_return_min: typing.Optional[float] = None
    strong_buy_return_max: typing.Optional[float] = None
    buy_return_min: typing.Optional[float] = None
    buy_return_max: typing.Optional[float] = None
    uncertainty_min_pct: typing.Optional[float] = None
    uncertainty_max_pct: typing.Optional[float] = None
    confidence_scaling: typing.Optional[float] = None
    min_position_weight: typing.Optional[float] = None
    max_position_weight: typing.Optional[float] = None
    overall_rationale: typing.Optional[str] = None
    tau_rationale: typing.Optional[str] = None
    delta_rationale: typing.Optional[str] = None
    return_expectations_rationale: typing.Optional[str] = None
    uncertainty_rationale: typing.Optional[str] = None
    weight_constraints_rationale: typing.Optional[str] = None
    regime_multiplier: typing.Optional[float] = None
    volatility_adjustment: typing.Optional[str] = None
    confidence_adjustment: typing.Optional[str] = None
    parameter_risks: typing.List[str]
    monitoring_recommendations: typing.List[str]

class BlackLittermanView(BaseModel):
    ticker: typing.Optional[str] = None
    expected_return: typing.Optional[float] = None
    confidence: typing.Optional[float] = None
    view_uncertainty: typing.Optional[float] = None
    rationale: typing.Optional[str] = None
    factor_contributions: typing.Optional[str] = None
    risk_adjustments: typing.Optional[str] = None
    regime_adjustment: typing.Optional[str] = None

class BusinessCycleClassification(BaseModel):
    regime: typing.Optional[types.BusinessCycleRegime] = None
    confidence: typing.Optional[float] = None
    rationale: typing.Optional[str] = None
    ism_signal: typing.Optional[types.ISMSignal] = None
    yield_curve_signal: typing.Optional[types.YieldCurveSignal] = None
    credit_spread_signal: typing.Optional[types.CreditSpreadSignal] = None
    recession_risk_6m: typing.Optional[float] = None
    recession_risk_12m: typing.Optional[float] = None
    recession_drivers: typing.List[str]
    sector_tilts: typing.Dict[str, float]
    recommended_overweights: typing.List[str]
    recommended_underweights: typing.List[str]
    factor_exposure: typing.Optional[types.FactorExposure] = None
    primary_risks: typing.List[str]
    conflicting_signals: typing.List[str]

class ComprehensiveYFinanceData(BaseModel):
    ticker: typing.Optional[str] = None
    company_name: typing.Optional[str] = None
    price_data: typing.Optional["YFinancePriceData"] = None
    financial_metrics: typing.Optional["YFinanceFinancialMetrics"] = None
    dividend_data: typing.Optional["YFinanceDividendData"] = None
    company_info: typing.Optional["YFinanceCompanyInfo"] = None
    governance: typing.Optional["YFinanceGovernance"] = None
    market_data: typing.Optional["YFinanceMarketData"] = None
    trading_info: typing.Optional["YFinanceTradingInfo"] = None
    analyst_data: typing.Optional["YFinanceAnalystData"] = None
    dates: typing.Optional["YFinanceDates"] = None
    technical_data: typing.Optional["YFinanceTechnicalData"] = None
    data_fetch_timestamp: typing.Optional[str] = None
    data_completeness_pct: typing.Optional[float] = None
    yfinance_info_dict_size: typing.Optional[int] = None

class CountryForecastData(BaseModel):
    country: typing.Optional[str] = None
    last_inflation: typing.Optional[float] = None
    inflation_6m: typing.Optional[float] = None
    inflation_10y_avg: typing.Optional[float] = None
    gdp_growth_6m: typing.Optional[float] = None
    earnings_12m: typing.Optional[float] = None
    eps_expected_12m: typing.Optional[float] = None
    peg_ratio: typing.Optional[float] = None
    lt_rate_forecast: typing.Optional[float] = None

class CountryQuantitativeData(BaseModel):
    country: typing.Optional[str] = None
    gdp_growth_qq: typing.Optional[float] = None
    industrial_production: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    consumer_prices: typing.Optional[float] = None
    deficit: typing.Optional[float] = None
    debt: typing.Optional[float] = None
    st_rate: typing.Optional[float] = None
    lt_rate: typing.Optional[float] = None

class EconomicIndicators(BaseModel):
    gdp_growth_qq: typing.Optional[float] = None
    gdp_growth_yy: typing.Optional[float] = None
    gdp_forecast_6m: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    industrial_production: typing.Optional[float] = None
    capacity_utilization: typing.Optional[float] = None
    inflation: typing.Optional[float] = None
    inflation_mom: typing.Optional[float] = None
    core_inflation: typing.Optional[float] = None
    inflation_forecast: typing.Optional[float] = None
    retail_sales_mom: typing.Optional[float] = None
    earnings_growth_forecast: typing.Optional[float] = None
    business_confidence: typing.Optional[float] = None
    consumer_confidence: typing.Optional[float] = None
    trade_balance: typing.Optional[float] = None
    current_account: typing.Optional[float] = None
    current_account_gdp: typing.Optional[float] = None
    government_debt_gdp: typing.Optional[float] = None
    budget_balance_gdp: typing.Optional[float] = None

class FREDIndicators(BaseModel):
    ism_pmi: typing.Optional[float] = None
    ism_signal: typing.Optional[str] = None
    yield_curve_2s10s: typing.Optional[float] = None
    curve_signal: typing.Optional[str] = None
    hy_spread: typing.Optional[float] = None
    ig_spread: typing.Optional[float] = None
    credit_signal: typing.Optional[str] = None
    vix: typing.Optional[float] = None
    vix_signal: typing.Optional[str] = None

class G7CountrySnapshot(BaseModel):
    country: typing.Optional[str] = None
    gdp_growth_qq: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    inflation: typing.Optional[float] = None
    inflation_forecast_6m: typing.Optional[float] = None
    gdp_forecast_6m: typing.Optional[float] = None
    policy_rate: typing.Optional[float] = None
    regime_assessment: typing.Optional[str] = None

class G7MacroOverview(BaseModel):
    countries: typing.List["G7CountrySnapshot"]
    synchronized_slowdown: typing.Optional[bool] = None
    divergence_note: typing.Optional[str] = None
    global_growth_signal: typing.Optional[str] = None
    global_inflation_signal: typing.Optional[str] = None
    monetary_policy_direction: typing.Optional[str] = None
    key_risks: typing.List[str]

class HistoricalPerformance(BaseModel):
    recent_sharpe_ratio: typing.Optional[float] = None
    recent_turnover: typing.Optional[float] = None
    avg_tracking_error: typing.Optional[float] = None

class HistoricalPriceData(BaseModel):
    dates: typing.List[str]
    open: typing.List[float]
    high: typing.List[float]
    low: typing.List[float]
    close: typing.List[float]
    adj_close: typing.List[float]
    volume: typing.List[float]
    ticker: typing.Optional[str] = None
    start_date: typing.Optional[str] = None
    end_date: typing.Optional[str] = None
    trading_days_count: typing.Optional[int] = None
    data_quality_score: typing.Optional[float] = None

class MacroNewsSignals(BaseModel):
    dominant_themes: typing.List[str]
    growth_sentiment: typing.Optional[types.GrowthSentiment] = None
    growth_summary: typing.Optional[str] = None
    inflation_sentiment: typing.Optional[types.InflationSentiment] = None
    inflation_summary: typing.Optional[str] = None
    labor_market_sentiment: typing.Optional[types.LaborMarketSentiment] = None
    labor_market_summary: typing.Optional[str] = None
    policy_stance: typing.Optional[types.PolicyStance] = None
    policy_summary: typing.Optional[str] = None
    risk_appetite: typing.Optional[types.RiskAppetite] = None
    regime_narrative: typing.Optional[types.RegimeNarrative] = None
    regime_rationale: typing.Optional[str] = None

class MacroRegimeContext(BaseModel):
    current_regime: typing.Optional[str] = None
    regime_confidence: typing.Optional[float] = None
    recession_risk_6m: typing.Optional[float] = None
    recession_risk_12m: typing.Optional[float] = None
    vix: typing.Optional[float] = None
    hy_spread: typing.Optional[float] = None
    yield_curve_2s10s: typing.Optional[float] = None
    recommended_overweights: typing.Optional[typing.List[str]] = None
    recommended_underweights: typing.Optional[typing.List[str]] = None

class MacroRegimeData(BaseModel):
    country: typing.Optional[str] = None
    assessment_date: typing.Optional[str] = None
    regime: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    rationale: typing.Optional[str] = None
    ism_pmi: typing.Optional[float] = None
    ism_signal: typing.Optional[str] = None
    yield_curve_2s10s: typing.Optional[float] = None
    yield_curve_signal: typing.Optional[str] = None
    hy_spread: typing.Optional[float] = None
    credit_spread_signal: typing.Optional[str] = None
    vix: typing.Optional[float] = None
    recession_risk_6m: typing.Optional[float] = None
    recession_risk_12m: typing.Optional[float] = None
    gdp_growth_yy: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    inflation: typing.Optional[float] = None
    recommended_overweights: typing.List[str]
    recommended_underweights: typing.List[str]
    factor_exposure: typing.Optional[str] = None
    primary_risks: typing.List[str]

class MacroRegimeInput(BaseModel):
    current_regime: typing.Optional[str] = None
    regime_confidence: typing.Optional[float] = None
    recession_risk_6m: typing.Optional[float] = None
    recession_risk_12m: typing.Optional[float] = None
    market_stress_level: typing.Optional[str] = None
    fred_indicators: typing.Optional["FREDIndicators"] = None
    usa_quantitative: typing.Optional["CountryQuantitativeData"] = None
    usa_forecast: typing.Optional["CountryForecastData"] = None
    regime_news_analysis: typing.Optional["RegimeNewsAnalysis"] = None
    g7_macro_overview: typing.Optional["G7MacroOverview"] = None

class MarketIndicators(BaseModel):
    ism_pmi: typing.Optional[float] = None
    manufacturing_pmi: typing.Optional[float] = None
    services_pmi: typing.Optional[float] = None
    composite_pmi: typing.Optional[float] = None
    interest_rate: typing.Optional[float] = None
    yield_curve_2s10s: typing.Optional[float] = None
    bond_yield_2y: typing.Optional[float] = None
    bond_yield_5y: typing.Optional[float] = None
    bond_yield_10y: typing.Optional[float] = None
    bond_yield_30y: typing.Optional[float] = None
    hy_spread: typing.Optional[float] = None
    vix: typing.Optional[float] = None
    vix_signal: typing.Optional[str] = None

class MarketVolatilityMetrics(BaseModel):
    current_vix: typing.Optional[float] = None
    market_realized_vol: typing.Optional[float] = None
    signal_universe_vol: typing.Optional[float] = None
    vol_regime: typing.Optional[str] = None

class MinimalYFinanceData(BaseModel):
    ticker: typing.Optional[str] = None
    company_name: typing.Optional[str] = None
    sector: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    currentPrice: typing.Optional[float] = None
    marketCap: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    trailingPE: typing.Optional[float] = None
    priceToBook: typing.Optional[float] = None
    returnOnEquity: typing.Optional[float] = None
    debtToEquity: typing.Optional[float] = None
    profitMargins: typing.Optional[float] = None
    revenueGrowth: typing.Optional[float] = None
    earningsGrowth: typing.Optional[float] = None
    fiftyTwoWeekChangePercent: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    recommendationKey: typing.Optional[str] = None

class NewsArticle(BaseModel):
    title: typing.Optional[str] = None
    publisher: typing.Optional[str] = None
    date: typing.Optional[str] = None
    link: typing.Optional[str] = None
    summary: typing.Optional[str] = None
    full_content: typing.Optional[str] = None

class RegimeNewsAnalysis(BaseModel):
    regime_analysis_summary: typing.Optional[str] = None
    news_summary: typing.Optional[str] = None
    key_news_signals: typing.List[str]
    news_alignment: typing.Optional[str] = None
    warning_signs: typing.List[str]
    leading_indicators: typing.List[str]

class RiskFactors(BaseModel):
    volatility_level: typing.Optional[str] = None
    beta_risk: typing.Optional[str] = None
    debt_risk: typing.Optional[str] = None
    liquidity_risk: typing.Optional[str] = None
    data_gaps: typing.List[str]
    primary_risks: typing.List[str]

class SectorContext(BaseModel):
    sector_name: typing.Optional[str] = None
    avg_sector_return: typing.Optional[float] = None
    sector_momentum: typing.Optional[str] = None
    sector_valuation: typing.Optional[str] = None
    num_signals_in_sector: typing.Optional[int] = None

class SignalCharacteristics(BaseModel):
    total_signals: typing.Optional[int] = None
    buy_signals: typing.Optional[int] = None
    strong_buy_signals: typing.Optional[int] = None
    avg_confidence: typing.Optional[float] = None
    confidence_dispersion: typing.Optional[float] = None
    signal_concentration: typing.Optional[float] = None

class SignalDrivers(BaseModel):
    valuation_score: typing.Optional[float] = None
    valuation_summary: typing.Optional[str] = None
    momentum_score: typing.Optional[float] = None
    momentum_summary: typing.Optional[str] = None
    quality_score: typing.Optional[float] = None
    quality_summary: typing.Optional[str] = None
    growth_score: typing.Optional[float] = None
    growth_summary: typing.Optional[str] = None
    technical_score: typing.Optional[float] = None
    technical_summary: typing.Optional[str] = None
    analyst_score: typing.Optional[float] = None
    analyst_summary: typing.Optional[str] = None

class StockNewsSignals(BaseModel):
    dominant_themes: typing.List[str]
    company_momentum: typing.Optional[types.CompanyMomentum] = None
    momentum_summary: typing.Optional[str] = None
    earnings_outlook: typing.Optional[types.EarningsOutlook] = None
    earnings_summary: typing.Optional[str] = None
    management_sentiment: typing.Optional[types.ManagementSentiment] = None
    management_summary: typing.Optional[str] = None
    competitive_position: typing.Optional[types.CompetitivePosition] = None
    competitive_summary: typing.Optional[str] = None
    key_catalysts: typing.List[str]
    key_risks: typing.List[str]
    news_bias: typing.Optional[str] = None
    confidence_assessment: typing.Optional[str] = None

class StockSignalData(BaseModel):
    ticker: typing.Optional[str] = None
    yfinance_ticker: typing.Optional[str] = None
    sector: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    signal_type: typing.Optional[str] = None
    confidence_level: typing.Optional[str] = None
    valuation_score: typing.Optional[float] = None
    momentum_score: typing.Optional[float] = None
    quality_score: typing.Optional[float] = None
    growth_score: typing.Optional[float] = None
    technical_score: typing.Optional[float] = None
    annualized_return: typing.Optional[float] = None
    volatility: typing.Optional[float] = None
    sharpe_ratio: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    alpha: typing.Optional[float] = None
    volatility_level: typing.Optional[str] = None
    beta_risk: typing.Optional[str] = None
    debt_risk: typing.Optional[str] = None
    liquidity_risk: typing.Optional[str] = None
    upside_potential_pct: typing.Optional[float] = None
    downside_risk_pct: typing.Optional[float] = None
    close_price: typing.Optional[float] = None
    daily_return: typing.Optional[float] = None

class StockSignalOutput(BaseModel):
    signal_type: typing.Optional[types.SignalType] = None
    signal_date: typing.Optional[str] = None
    close_price: typing.Optional[float] = None
    open_price: typing.Optional[float] = None
    daily_return: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    volatility: typing.Optional[float] = None
    rsi: typing.Optional[float] = None
    data_quality_score: typing.Optional[float] = None
    confidence_level: typing.Optional[types.ConfidenceLevel] = None
    analysis_notes: typing.Optional[str] = None
    signal_drivers: typing.Optional["SignalDrivers"] = None
    risk_factors: typing.Optional["RiskFactors"] = None
    upside_potential_pct: typing.Optional[float] = None
    downside_risk_pct: typing.Optional[float] = None

class YFinanceAnalystData(BaseModel):
    recommendationKey: typing.Optional[str] = None
    recommendationMean: typing.Optional[float] = None
    numberOfAnalystOpinions: typing.Optional[int] = None
    averageAnalystRating: typing.Optional[str] = None

class YFinanceBalanceSheet(BaseModel):
    periods: typing.List[str]
    TotalAssets: typing.Optional[typing.List[float]] = None
    CurrentAssets: typing.Optional[typing.List[float]] = None
    CashAndCashEquivalents: typing.Optional[typing.List[float]] = None
    CashCashEquivalentsAndShortTermInvestments: typing.Optional[typing.List[float]] = None
    AccountsReceivable: typing.Optional[typing.List[float]] = None
    Inventory: typing.Optional[typing.List[float]] = None
    PropertyPlantEquipment: typing.Optional[typing.List[float]] = None
    Goodwill: typing.Optional[typing.List[float]] = None
    IntangibleAssets: typing.Optional[typing.List[float]] = None
    TotalLiabilities: typing.Optional[typing.List[float]] = None
    CurrentLiabilities: typing.Optional[typing.List[float]] = None
    AccountsPayable: typing.Optional[typing.List[float]] = None
    ShortTermDebt: typing.Optional[typing.List[float]] = None
    LongTermDebt: typing.Optional[typing.List[float]] = None
    TotalDebt: typing.Optional[typing.List[float]] = None
    StockholdersEquity: typing.Optional[typing.List[float]] = None
    RetainedEarnings: typing.Optional[typing.List[float]] = None
    TreasuryStock: typing.Optional[typing.List[float]] = None
    ShareIssued: typing.Optional[typing.List[float]] = None
    OrdinarySharesNumber: typing.Optional[typing.List[float]] = None

class YFinanceCashFlow(BaseModel):
    periods: typing.List[str]
    OperatingCashFlow: typing.Optional[typing.List[float]] = None
    CashFlowFromContinuingOperatingActivities: typing.Optional[typing.List[float]] = None
    DepreciationAndAmortization: typing.Optional[typing.List[float]] = None
    ChangeInWorkingCapital: typing.Optional[typing.List[float]] = None
    CashFlowFromInvestingActivities: typing.Optional[typing.List[float]] = None
    CapitalExpenditure: typing.Optional[typing.List[float]] = None
    NetBusinessPurchaseAndSale: typing.Optional[typing.List[float]] = None
    NetInvestmentPurchaseAndSale: typing.Optional[typing.List[float]] = None
    CashFlowFromFinancingActivities: typing.Optional[typing.List[float]] = None
    RepurchaseOfCapitalStock: typing.Optional[typing.List[float]] = None
    RepaymentOfDebt: typing.Optional[typing.List[float]] = None
    IssuanceOfDebt: typing.Optional[typing.List[float]] = None
    CashDividendsPaid: typing.Optional[typing.List[float]] = None
    FreeCashFlow: typing.Optional[typing.List[float]] = None

class YFinanceCompanyInfo(BaseModel):
    symbol: typing.Optional[str] = None
    shortName: typing.Optional[str] = None
    longName: typing.Optional[str] = None
    displayName: typing.Optional[str] = None
    sector: typing.Optional[str] = None
    sectorDisp: typing.Optional[str] = None
    sectorKey: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    industryDisp: typing.Optional[str] = None
    industryKey: typing.Optional[str] = None
    country: typing.Optional[str] = None
    state: typing.Optional[str] = None
    city: typing.Optional[str] = None
    zip: typing.Optional[str] = None
    address1: typing.Optional[str] = None
    address2: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    website: typing.Optional[str] = None
    irWebsite: typing.Optional[str] = None
    longBusinessSummary: typing.Optional[str] = None
    exchange: typing.Optional[str] = None
    fullExchangeName: typing.Optional[str] = None
    quoteSourceName: typing.Optional[str] = None
    exchangeTimezoneName: typing.Optional[str] = None
    exchangeTimezoneShortName: typing.Optional[str] = None
    fullTimeEmployees: typing.Optional[int] = None

class YFinanceDates(BaseModel):
    firstTradeDateMilliseconds: typing.Optional[int] = None
    lastFiscalYearEnd: typing.Optional[int] = None
    nextFiscalYearEnd: typing.Optional[int] = None
    mostRecentQuarter: typing.Optional[int] = None
    lastSplitDate: typing.Optional[int] = None
    lastSplitFactor: typing.Optional[str] = None
    ipoExpectedDate: typing.Optional[int] = None

class YFinanceDividendData(BaseModel):
    dividendYield: typing.Optional[float] = None
    dividendRate: typing.Optional[float] = None
    trailingAnnualDividendRate: typing.Optional[float] = None
    trailingAnnualDividendYield: typing.Optional[float] = None
    fiveYearAvgDividendYield: typing.Optional[float] = None
    dividendDate: typing.Optional[int] = None
    exDividendDate: typing.Optional[int] = None
    lastDividendDate: typing.Optional[int] = None
    lastDividendValue: typing.Optional[float] = None

class YFinanceFinancialMetrics(BaseModel):
    profitMargins: typing.Optional[float] = None
    grossMargins: typing.Optional[float] = None
    operatingMargins: typing.Optional[float] = None
    ebitdaMargins: typing.Optional[float] = None
    returnOnAssets: typing.Optional[float] = None
    returnOnEquity: typing.Optional[float] = None
    revenueGrowth: typing.Optional[float] = None
    earningsGrowth: typing.Optional[float] = None
    earningsQuarterlyGrowth: typing.Optional[float] = None
    currentRatio: typing.Optional[float] = None
    quickRatio: typing.Optional[float] = None
    debtToEquity: typing.Optional[float] = None
    payoutRatio: typing.Optional[float] = None
    grossProfits: typing.Optional[float] = None
    totalRevenue: typing.Optional[float] = None
    revenuePerShare: typing.Optional[float] = None
    netIncomeToCommon: typing.Optional[float] = None
    totalCash: typing.Optional[float] = None
    totalCashPerShare: typing.Optional[float] = None
    totalDebt: typing.Optional[float] = None
    operatingCashflow: typing.Optional[float] = None
    freeCashflow: typing.Optional[float] = None
    enterpriseToRevenue: typing.Optional[float] = None
    shortRatio: typing.Optional[float] = None
    earningsTimestampStart: typing.Optional[int] = None
    earningsTimestampEnd: typing.Optional[int] = None
    earningsTimestamp: typing.Optional[int] = None
    earningsCallTimestampStart: typing.Optional[int] = None
    earningsCallTimestampEnd: typing.Optional[int] = None
    isEarningsDateEstimate: typing.Optional[bool] = None
    trailingPegRatio: typing.Optional[float] = None

class YFinanceFinancialStatements(BaseModel):
    ticker: typing.Optional[str] = None
    income_statement: typing.Optional["YFinanceIncomeStatement"] = None
    balance_sheet: typing.Optional["YFinanceBalanceSheet"] = None
    cash_flow: typing.Optional["YFinanceCashFlow"] = None
    statement_frequency: typing.Optional[str] = None
    most_recent_period: typing.Optional[str] = None
    periods_available: typing.Optional[int] = None

class YFinanceGovernance(BaseModel):
    companyOfficers: typing.Optional[str] = None
    executiveTeam: typing.Optional[str] = None
    boardRisk: typing.Optional[int] = None
    compensationRisk: typing.Optional[int] = None
    overallRisk: typing.Optional[int] = None
    shareHolderRightsRisk: typing.Optional[int] = None
    auditRisk: typing.Optional[int] = None
    compensationAsOfEpochDate: typing.Optional[int] = None
    governanceEpochDate: typing.Optional[int] = None
    messageBoardId: typing.Optional[str] = None

class YFinanceIncomeStatement(BaseModel):
    periods: typing.List[str]
    TotalRevenue: typing.Optional[typing.List[float]] = None
    CostOfRevenue: typing.Optional[typing.List[float]] = None
    GrossProfit: typing.Optional[typing.List[float]] = None
    OperatingExpense: typing.Optional[typing.List[float]] = None
    OperatingIncome: typing.Optional[typing.List[float]] = None
    EBITDA: typing.Optional[typing.List[float]] = None
    NetIncome: typing.Optional[typing.List[float]] = None
    NetIncomeCommonStockholders: typing.Optional[typing.List[float]] = None
    BasicEPS: typing.Optional[typing.List[float]] = None
    DilutedEPS: typing.Optional[typing.List[float]] = None
    ResearchAndDevelopment: typing.Optional[typing.List[float]] = None
    SellingGeneralAndAdministration: typing.Optional[typing.List[float]] = None
    InterestExpense: typing.Optional[typing.List[float]] = None
    TaxProvision: typing.Optional[typing.List[float]] = None

class YFinanceMarketData(BaseModel):
    marketCap: typing.Optional[float] = None
    sharesOutstanding: typing.Optional[float] = None
    impliedSharesOutstanding: typing.Optional[float] = None
    floatShares: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    regularMarketVolume: typing.Optional[float] = None
    averageVolume: typing.Optional[float] = None
    averageVolume10days: typing.Optional[float] = None
    averageDailyVolume10Day: typing.Optional[float] = None
    averageDailyVolume3Month: typing.Optional[float] = None
    sharesShort: typing.Optional[float] = None
    sharesShortPriorMonth: typing.Optional[float] = None
    shortPercentOfFloat: typing.Optional[float] = None
    sharesPercentSharesOut: typing.Optional[float] = None
    sharesShortPreviousMonthDate: typing.Optional[int] = None
    dateShortInterest: typing.Optional[int] = None
    heldPercentInstitutions: typing.Optional[float] = None
    heldPercentInsiders: typing.Optional[float] = None
    market: typing.Optional[str] = None
    marketState: typing.Optional[str] = None
    hasPrePostMarketData: typing.Optional[bool] = None
    regularMarketTime: typing.Optional[int] = None
    gmtOffSetMilliseconds: typing.Optional[int] = None
    corporateActions: typing.Optional[str] = None

class YFinancePriceData(BaseModel):
    currentPrice: typing.Optional[float] = None
    regularMarketPrice: typing.Optional[float] = None
    regularMarketOpen: typing.Optional[float] = None
    open: typing.Optional[float] = None
    previousClose: typing.Optional[float] = None
    regularMarketPreviousClose: typing.Optional[float] = None
    dayHigh: typing.Optional[float] = None
    dayLow: typing.Optional[float] = None
    regularMarketDayHigh: typing.Optional[float] = None
    regularMarketDayLow: typing.Optional[float] = None
    regularMarketDayRange: typing.Optional[str] = None
    fiftyTwoWeekHigh: typing.Optional[float] = None
    fiftyTwoWeekLow: typing.Optional[float] = None
    fiftyTwoWeekHighChange: typing.Optional[float] = None
    fiftyTwoWeekLowChange: typing.Optional[float] = None
    fiftyTwoWeekHighChangePercent: typing.Optional[float] = None
    fiftyTwoWeekLowChangePercent: typing.Optional[float] = None
    fiftyTwoWeekRange: typing.Optional[str] = None
    fiftyTwoWeekChangePercent: typing.Optional[float] = None
    allTimeHigh: typing.Optional[float] = None
    allTimeLow: typing.Optional[float] = None
    bid: typing.Optional[float] = None
    ask: typing.Optional[float] = None
    bidSize: typing.Optional[int] = None
    askSize: typing.Optional[int] = None
    regularMarketChange: typing.Optional[float] = None
    regularMarketChangePercent: typing.Optional[float] = None
    postMarketPrice: typing.Optional[float] = None
    postMarketChange: typing.Optional[float] = None
    postMarketChangePercent: typing.Optional[float] = None
    postMarketTime: typing.Optional[int] = None
    targetMeanPrice: typing.Optional[float] = None
    targetMedianPrice: typing.Optional[float] = None
    targetHighPrice: typing.Optional[float] = None
    targetLowPrice: typing.Optional[float] = None
    priceToBook: typing.Optional[float] = None
    priceToSalesTrailing12Months: typing.Optional[float] = None
    priceEpsCurrentYear: typing.Optional[float] = None
    priceHint: typing.Optional[int] = None
    customPriceAlertConfidence: typing.Optional[str] = None

class YFinanceTechnicalData(BaseModel):
    fiftyDayAverage: typing.Optional[float] = None
    twoHundredDayAverage: typing.Optional[float] = None
    fiftyDayAverageChange: typing.Optional[float] = None
    twoHundredDayAverageChange: typing.Optional[float] = None
    fiftyDayAverageChangePercent: typing.Optional[float] = None
    twoHundredDayAverageChangePercent: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    SandP52WeekChange: typing.Optional[float] = None
    epsTrailingTwelveMonths: typing.Optional[float] = None
    epsCurrentYear: typing.Optional[float] = None
    epsForward: typing.Optional[float] = None
    forwardEps: typing.Optional[float] = None
    trailingEps: typing.Optional[float] = None
    trailingPE: typing.Optional[float] = None
    forwardPE: typing.Optional[float] = None
    bookValue: typing.Optional[float] = None
    ebitda: typing.Optional[float] = None
    enterpriseValue: typing.Optional[float] = None
    enterpriseToEbitda: typing.Optional[float] = None
    esgPopulated: typing.Optional[bool] = None
    quoteType: typing.Optional[str] = None
    typeDisp: typing.Optional[str] = None
    language: typing.Optional[str] = None
    region: typing.Optional[str] = None
    maxAge: typing.Optional[int] = None
    sourceInterval: typing.Optional[int] = None
    triggerable: typing.Optional[bool] = None
    fax: typing.Optional[str] = None

class YFinanceTradingInfo(BaseModel):
    currency: typing.Optional[str] = None
    financialCurrency: typing.Optional[str] = None
    exchange: typing.Optional[str] = None
    exchangeDataDelayedBy: typing.Optional[int] = None
    tradeable: typing.Optional[bool] = None
    cryptoTradeable: typing.Optional[bool] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
