# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (42)
# #########################################################################

class BlackLittermanParameters(BaseModel):
    tau: typing.Optional[float] = None
    delta: typing.Optional[float] = None
    strong_buy_return_min: typing.Optional[float] = None
    strong_buy_return_max: typing.Optional[float] = None
    buy_return_min: typing.Optional[float] = None
    buy_return_max: typing.Optional[float] = None
    uncertainty_min_pct: typing.Optional[float] = None
    uncertainty_max_pct: typing.Optional[float] = None
    confidence_scaling: typing.Optional[float] = None
    min_position_weight: typing.Optional[float] = None
    max_position_weight: typing.Optional[float] = None
    overall_rationale: typing.Optional[str] = None
    tau_rationale: typing.Optional[str] = None
    delta_rationale: typing.Optional[str] = None
    return_expectations_rationale: typing.Optional[str] = None
    uncertainty_rationale: typing.Optional[str] = None
    weight_constraints_rationale: typing.Optional[str] = None
    regime_multiplier: typing.Optional[float] = None
    volatility_adjustment: typing.Optional[str] = None
    confidence_adjustment: typing.Optional[str] = None
    parameter_risks: typing.List[str]
    monitoring_recommendations: typing.List[str]

class BlackLittermanView(BaseModel):
    ticker: typing.Optional[str] = None
    expected_return: typing.Optional[float] = Field(default=None, description='Expected annual return for this asset. Range: -0.30 to +0.30 (-30% to +30%).\nTypical values: Strong Buy: 0.08-0.15, Buy: 0.04-0.10, Sell: -0.05 to -0.15')
    confidence: typing.Optional[float] = Field(default=None, description='Confidence level in this view (0 = no confidence, 1 = absolute certainty).\nHIGH: 0.75-0.95, MEDIUM: 0.50-0.75, LOW: 0.20-0.50')
    view_uncertainty: typing.Optional[float] = Field(default=None, description='Uncertainty (standard deviation) of the expected return forecast.\nDerived from confidence: higher confidence → lower uncertainty.\nTypical range: 0.01 (1%) to 0.08 (8%)')
    rationale: typing.Optional[str] = Field(default=None, description='2-3 sentence explanation of why this expected return is justified.\nReference specific factors: valuation, momentum, quality, growth.\nMention regime considerations and risk adjustments.')
    factor_contributions: typing.Optional[str] = Field(default=None, description='Breakdown of which factors support the view (e.g., "Momentum +3%, Valuation +2%, Quality +1%")')
    risk_adjustments: typing.Optional[str] = Field(default=None, description='Any penalties applied due to risk factors (e.g., "High debt: -2%, Low liquidity: -1%")')
    regime_adjustment: typing.Optional[str] = Field(default=None, description='How the macro regime influenced the view (e.g., "Late cycle: reduced return by 2%")')

class BusinessCycleClassification(BaseModel):
    regime: typing.Optional[types.BusinessCycleRegime] = None
    confidence: typing.Optional[float] = Field(default=None, description='0.0 to 1.0')
    rationale: typing.Optional[str] = Field(default=None, description='Concise explanation (2-3 sentences maximum)')
    ism_signal: typing.Optional[types.ISMSignal] = None
    yield_curve_signal: typing.Optional[types.YieldCurveSignal] = None
    credit_spread_signal: typing.Optional[types.CreditSpreadSignal] = None
    recession_risk_6m: typing.Optional[float] = Field(default=None, description='0.0 to 1.0')
    recession_risk_12m: typing.Optional[float] = Field(default=None, description='0.0 to 1.0')
    recession_drivers: typing.List[str] = Field(description='2-4 key recession risk factors')
    sector_tilts: typing.Dict[str, float] = Field(description='Sector -> weight adjustment between -0.10 and +0.10')
    recommended_overweights: typing.List[str] = Field(description='3-5 sectors to overweight with brief rationale')
    recommended_underweights: typing.List[str] = Field(description='3-5 sectors to underweight with brief rationale')
    factor_exposure: typing.Optional[types.FactorExposure] = None
    primary_risks: typing.List[str] = Field(description='2-3 main risks to watch')
    conflicting_signals: typing.List[str] = Field(description='Any major contradictions (empty if none)')

class ComprehensiveYFinanceData(BaseModel):
    ticker: typing.Optional[str] = None
    company_name: typing.Optional[str] = None
    price_data: typing.Optional["YFinancePriceData"] = None
    financial_metrics: typing.Optional["YFinanceFinancialMetrics"] = None
    dividend_data: typing.Optional["YFinanceDividendData"] = None
    company_info: typing.Optional["YFinanceCompanyInfo"] = None
    governance: typing.Optional["YFinanceGovernance"] = None
    market_data: typing.Optional["YFinanceMarketData"] = None
    trading_info: typing.Optional["YFinanceTradingInfo"] = None
    analyst_data: typing.Optional["YFinanceAnalystData"] = None
    dates: typing.Optional["YFinanceDates"] = None
    technical_data: typing.Optional["YFinanceTechnicalData"] = None
    data_fetch_timestamp: typing.Optional[str] = None
    data_completeness_pct: typing.Optional[float] = None
    yfinance_info_dict_size: typing.Optional[int] = None

class CountryForecastData(BaseModel):
    country: typing.Optional[str] = None
    last_inflation: typing.Optional[float] = None
    inflation_6m: typing.Optional[float] = None
    inflation_10y_avg: typing.Optional[float] = None
    gdp_growth_6m: typing.Optional[float] = None
    earnings_12m: typing.Optional[float] = None
    eps_expected_12m: typing.Optional[float] = None
    peg_ratio: typing.Optional[float] = None
    lt_rate_forecast: typing.Optional[float] = None

class CountryQuantitativeData(BaseModel):
    country: typing.Optional[str] = None
    gdp_growth_qq: typing.Optional[float] = None
    industrial_production: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    consumer_prices: typing.Optional[float] = None
    deficit: typing.Optional[float] = None
    debt: typing.Optional[float] = None
    st_rate: typing.Optional[float] = None
    lt_rate: typing.Optional[float] = None

class EconomicIndicators(BaseModel):
    gdp_growth_qq: typing.Optional[float] = None
    gdp_growth_yy: typing.Optional[float] = None
    gdp_forecast_6m: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    industrial_production: typing.Optional[float] = None
    capacity_utilization: typing.Optional[float] = None
    inflation: typing.Optional[float] = None
    inflation_mom: typing.Optional[float] = None
    core_inflation: typing.Optional[float] = None
    inflation_forecast: typing.Optional[float] = None
    retail_sales_mom: typing.Optional[float] = None
    earnings_growth_forecast: typing.Optional[float] = None
    business_confidence: typing.Optional[float] = None
    consumer_confidence: typing.Optional[float] = None
    trade_balance: typing.Optional[float] = None
    current_account: typing.Optional[float] = None
    current_account_gdp: typing.Optional[float] = None
    government_debt_gdp: typing.Optional[float] = None
    budget_balance_gdp: typing.Optional[float] = None

class FREDIndicators(BaseModel):
    ism_pmi: typing.Optional[float] = None
    ism_signal: typing.Optional[str] = None
    yield_curve_2s10s: typing.Optional[float] = None
    curve_signal: typing.Optional[str] = None
    hy_spread: typing.Optional[float] = None
    ig_spread: typing.Optional[float] = None
    credit_signal: typing.Optional[str] = None
    vix: typing.Optional[float] = None
    vix_signal: typing.Optional[str] = None

class G7CountrySnapshot(BaseModel):
    country: typing.Optional[str] = None
    gdp_growth_qq: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    inflation: typing.Optional[float] = None
    inflation_forecast_6m: typing.Optional[float] = None
    gdp_forecast_6m: typing.Optional[float] = None
    policy_rate: typing.Optional[float] = None
    regime_assessment: typing.Optional[str] = None

class G7MacroOverview(BaseModel):
    countries: typing.List["G7CountrySnapshot"]
    synchronized_slowdown: typing.Optional[bool] = None
    divergence_note: typing.Optional[str] = None
    global_growth_signal: typing.Optional[str] = None
    global_inflation_signal: typing.Optional[str] = None
    monetary_policy_direction: typing.Optional[str] = None
    key_risks: typing.List[str]

class HistoricalPerformance(BaseModel):
    recent_sharpe_ratio: typing.Optional[float] = None
    recent_turnover: typing.Optional[float] = None
    avg_tracking_error: typing.Optional[float] = None

class HistoricalPriceData(BaseModel):
    dates: typing.List[str]
    open: typing.List[float]
    high: typing.List[float]
    low: typing.List[float]
    close: typing.List[float]
    adj_close: typing.List[float]
    volume: typing.List[float]
    ticker: typing.Optional[str] = None
    start_date: typing.Optional[str] = None
    end_date: typing.Optional[str] = None
    trading_days_count: typing.Optional[int] = None
    data_quality_score: typing.Optional[float] = None

class MacroNewsSignals(BaseModel):
    dominant_themes: typing.List[str] = Field(description='Top 3-5 themes (e.g., "Fed hawkish tone", "recession fears rising")')
    growth_sentiment: typing.Optional[types.GrowthSentiment] = None
    growth_summary: typing.Optional[str] = Field(default=None, description='2-3 sentences on GDP, earnings, business activity trends')
    inflation_sentiment: typing.Optional[types.InflationSentiment] = None
    inflation_summary: typing.Optional[str] = Field(default=None, description='2-3 sentences on inflation trends and central bank response')
    labor_market_sentiment: typing.Optional[types.LaborMarketSentiment] = None
    labor_market_summary: typing.Optional[str] = Field(default=None, description='2-3 sentences on unemployment, hiring, layoffs')
    policy_stance: typing.Optional[types.PolicyStance] = None
    policy_summary: typing.Optional[str] = Field(default=None, description='2-3 sentences on monetary policy tone and expectations')
    risk_appetite: typing.Optional[types.RiskAppetite] = None
    regime_narrative: typing.Optional[types.RegimeNarrative] = None
    regime_rationale: typing.Optional[str] = Field(default=None, description='2-3 sentences explaining why news suggests this regime')

class MacroRegimeContext(BaseModel):
    current_regime: typing.Optional[str] = None
    regime_confidence: typing.Optional[float] = None
    recession_risk_6m: typing.Optional[float] = None
    recession_risk_12m: typing.Optional[float] = None
    vix: typing.Optional[float] = None
    hy_spread: typing.Optional[float] = None
    yield_curve_2s10s: typing.Optional[float] = None
    recommended_overweights: typing.Optional[typing.List[str]] = None
    recommended_underweights: typing.Optional[typing.List[str]] = None

class MacroRegimeData(BaseModel):
    country: typing.Optional[str] = Field(default=None, description='Country code (USA, Germany, etc.)')
    assessment_date: typing.Optional[str] = Field(default=None, description='Date of macro assessment (YYYY-MM-DD)')
    regime: typing.Optional[str] = Field(default=None, description='Current regime: EARLY_CYCLE, MID_CYCLE, LATE_CYCLE, RECESSION, UNCERTAIN')
    confidence: typing.Optional[float] = Field(default=None, description='Regime classification confidence (0.0-1.0)')
    rationale: typing.Optional[str] = Field(default=None, description='Brief rationale for regime classification')
    ism_pmi: typing.Optional[float] = Field(default=None, description='ISM Manufacturing PMI (if available)')
    ism_signal: typing.Optional[str] = Field(default=None, description='ISM signal: STRONG_EXPANSION, MILD_EXPANSION, MILD_CONTRACTION, DEEP_CONTRACTION')
    yield_curve_2s10s: typing.Optional[float] = Field(default=None, description='2s10s yield spread in bps (if available)')
    yield_curve_signal: typing.Optional[str] = Field(default=None, description='Yield curve signal: STEEP, NORMAL, FLAT, INVERTED')
    hy_spread: typing.Optional[float] = Field(default=None, description='High-yield credit spread in bps (if available)')
    credit_spread_signal: typing.Optional[str] = Field(default=None, description='Credit spread signal: TIGHT, NEUTRAL, WIDENING, STRESS')
    vix: typing.Optional[float] = Field(default=None, description='VIX volatility index (if available)')
    recession_risk_6m: typing.Optional[float] = Field(default=None, description='6-month recession probability (0.0-1.0)')
    recession_risk_12m: typing.Optional[float] = Field(default=None, description='12-month recession probability (0.0-1.0)')
    gdp_growth_yy: typing.Optional[float] = Field(default=None, description='GDP growth year-over-year %')
    unemployment: typing.Optional[float] = Field(default=None, description='Unemployment rate %')
    inflation: typing.Optional[float] = Field(default=None, description='Inflation rate %')
    recommended_overweights: typing.List[str] = Field(description='Sectors currently recommended for overweight')
    recommended_underweights: typing.List[str] = Field(description='Sectors currently recommended for underweight')
    factor_exposure: typing.Optional[str] = Field(default=None, description='Recommended factor exposure: GROWTH_MOMENTUM, QUALITY_DEFENSIVE, BALANCED')
    primary_risks: typing.List[str] = Field(description='2-3 main macro risks to monitor')

class MacroRegimeInput(BaseModel):
    current_regime: typing.Optional[str] = None
    regime_confidence: typing.Optional[float] = None
    recession_risk_6m: typing.Optional[float] = None
    recession_risk_12m: typing.Optional[float] = None
    market_stress_level: typing.Optional[str] = None
    fred_indicators: typing.Optional["FREDIndicators"] = None
    usa_quantitative: typing.Optional["CountryQuantitativeData"] = None
    usa_forecast: typing.Optional["CountryForecastData"] = None
    regime_news_analysis: typing.Optional["RegimeNewsAnalysis"] = None
    g7_macro_overview: typing.Optional["G7MacroOverview"] = None

class MarketIndicators(BaseModel):
    ism_pmi: typing.Optional[float] = None
    manufacturing_pmi: typing.Optional[float] = None
    services_pmi: typing.Optional[float] = None
    composite_pmi: typing.Optional[float] = None
    interest_rate: typing.Optional[float] = None
    yield_curve_2s10s: typing.Optional[float] = None
    bond_yield_2y: typing.Optional[float] = None
    bond_yield_5y: typing.Optional[float] = None
    bond_yield_10y: typing.Optional[float] = None
    bond_yield_30y: typing.Optional[float] = None
    hy_spread: typing.Optional[float] = None
    vix: typing.Optional[float] = None
    vix_signal: typing.Optional[str] = None

class MarketVolatilityMetrics(BaseModel):
    current_vix: typing.Optional[float] = None
    market_realized_vol: typing.Optional[float] = None
    signal_universe_vol: typing.Optional[float] = None
    vol_regime: typing.Optional[str] = None

class MinimalYFinanceData(BaseModel):
    ticker: typing.Optional[str] = None
    company_name: typing.Optional[str] = None
    sector: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    currentPrice: typing.Optional[float] = None
    marketCap: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    trailingPE: typing.Optional[float] = None
    priceToBook: typing.Optional[float] = None
    returnOnEquity: typing.Optional[float] = None
    debtToEquity: typing.Optional[float] = None
    profitMargins: typing.Optional[float] = None
    revenueGrowth: typing.Optional[float] = None
    earningsGrowth: typing.Optional[float] = None
    fiftyTwoWeekChangePercent: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    recommendationKey: typing.Optional[str] = None

class NewsArticle(BaseModel):
    title: typing.Optional[str] = None
    publisher: typing.Optional[str] = None
    date: typing.Optional[str] = None
    link: typing.Optional[str] = None
    summary: typing.Optional[str] = None
    full_content: typing.Optional[str] = None

class RegimeNewsAnalysis(BaseModel):
    regime_analysis_summary: typing.Optional[str] = None
    news_summary: typing.Optional[str] = None
    key_news_signals: typing.List[str]
    news_alignment: typing.Optional[str] = None
    warning_signs: typing.List[str]
    leading_indicators: typing.List[str]

class RiskFactors(BaseModel):
    volatility_level: typing.Optional[str] = Field(default=None, description='Low/Medium/High - historical volatility assessment')
    beta_risk: typing.Optional[str] = Field(default=None, description='Market sensitivity assessment if beta available')
    debt_risk: typing.Optional[str] = Field(default=None, description='Assessment of debt levels and financial leverage')
    liquidity_risk: typing.Optional[str] = Field(default=None, description='Assessment of trading liquidity and market depth')
    data_gaps: typing.List[str] = Field(description='List of missing or unreliable data points that affected analysis')
    primary_risks: typing.List[str] = Field(description='Top 3-5 key risks to the signal thesis')

class SectorContext(BaseModel):
    sector_name: typing.Optional[str] = None
    avg_sector_return: typing.Optional[float] = None
    sector_momentum: typing.Optional[str] = None
    sector_valuation: typing.Optional[str] = None
    num_signals_in_sector: typing.Optional[int] = None

class SignalCharacteristics(BaseModel):
    total_signals: typing.Optional[int] = None
    buy_signals: typing.Optional[int] = None
    strong_buy_signals: typing.Optional[int] = None
    avg_confidence: typing.Optional[float] = None
    confidence_dispersion: typing.Optional[float] = None
    signal_concentration: typing.Optional[float] = None

class SignalDrivers(BaseModel):
    valuation_score: typing.Optional[float] = Field(default=None, description='Composite valuation score based on P/E, P/B, price vs targets')
    valuation_summary: typing.Optional[str] = Field(default=None, description='Brief valuation assessment (1-2 sentences)')
    momentum_score: typing.Optional[float] = Field(default=None, description='Price momentum based on 52-week performance, moving averages')
    momentum_summary: typing.Optional[str] = Field(default=None, description='Brief momentum assessment (1-2 sentences)')
    quality_score: typing.Optional[float] = Field(default=None, description='Business quality based on margins, ROE, debt levels')
    quality_summary: typing.Optional[str] = Field(default=None, description='Brief quality assessment (1-2 sentences)')
    growth_score: typing.Optional[float] = Field(default=None, description='Growth prospects based on revenue/earnings growth')
    growth_summary: typing.Optional[str] = Field(default=None, description='Brief growth assessment (1-2 sentences)')
    technical_score: typing.Optional[float] = Field(default=None, description='Technical indicators: RSI, moving averages, volume trends')
    technical_summary: typing.Optional[str] = Field(default=None, description='Brief technical assessment if data available')
    analyst_score: typing.Optional[float] = Field(default=None, description='Analyst consensus and ratings')
    analyst_summary: typing.Optional[str] = Field(default=None, description='Brief analyst sentiment summary')

class StockNewsSignals(BaseModel):
    dominant_themes: typing.List[str] = Field(description='Top 3-5 themes from company news (e.g., "Strong earnings beat", "Product launch success", "Regulatory concerns")')
    company_momentum: typing.Optional[types.CompanyMomentum] = None
    momentum_summary: typing.Optional[str] = Field(default=None, description='2-3 sentences on business growth, revenue trends, market share changes')
    earnings_outlook: typing.Optional[types.EarningsOutlook] = None
    earnings_summary: typing.Optional[str] = Field(default=None, description='2-3 sentences on recent/expected earnings, guidance, profitability')
    management_sentiment: typing.Optional[types.ManagementSentiment] = None
    management_summary: typing.Optional[str] = Field(default=None, description='2-3 sentences on management commentary, strategic initiatives, capital allocation')
    competitive_position: typing.Optional[types.CompetitivePosition] = None
    competitive_summary: typing.Optional[str] = Field(default=None, description='2-3 sentences on competitive positioning, industry trends, market dynamics')
    key_catalysts: typing.List[str] = Field(description='List of specific positive catalysts mentioned (e.g., "New product launch", "Partnership announced")')
    key_risks: typing.List[str] = Field(description='List of specific risks or concerns (e.g., "Regulatory investigation", "Supply chain issues")')
    news_bias: typing.Optional[str] = Field(default=None, description='Overall tone: "BULLISH", "NEUTRAL", or "BEARISH"')
    confidence_assessment: typing.Optional[str] = Field(default=None, description='How clear/actionable the news signal is: "HIGH", "MEDIUM", "LOW"')

class StockSignalData(BaseModel):
    ticker: typing.Optional[str] = None
    yfinance_ticker: typing.Optional[str] = None
    sector: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    signal_type: typing.Optional[str] = None
    confidence_level: typing.Optional[str] = None
    valuation_score: typing.Optional[float] = None
    momentum_score: typing.Optional[float] = None
    quality_score: typing.Optional[float] = None
    growth_score: typing.Optional[float] = None
    technical_score: typing.Optional[float] = None
    annualized_return: typing.Optional[float] = None
    volatility: typing.Optional[float] = None
    sharpe_ratio: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    alpha: typing.Optional[float] = None
    volatility_level: typing.Optional[str] = None
    beta_risk: typing.Optional[str] = None
    debt_risk: typing.Optional[str] = None
    liquidity_risk: typing.Optional[str] = None
    upside_potential_pct: typing.Optional[float] = None
    downside_risk_pct: typing.Optional[float] = None
    close_price: typing.Optional[float] = None
    daily_return: typing.Optional[float] = None

class StockSignalOutput(BaseModel):
    signal_type: typing.Optional[types.SignalType] = Field(default=None, description='Primary trading signal classification')
    signal_date: typing.Optional[str] = Field(default=None, description='Date for the signal (YYYY-MM-DD format)')
    close_price: typing.Optional[float] = Field(default=None, description='Current/most recent closing price')
    open_price: typing.Optional[float] = Field(default=None, description='Most recent opening price')
    daily_return: typing.Optional[float] = Field(default=None, description='Most recent daily return percentage')
    volume: typing.Optional[float] = Field(default=None, description='Recent trading volume')
    volatility: typing.Optional[float] = Field(default=None, description='Historical volatility (annualized standard deviation)')
    rsi: typing.Optional[float] = Field(default=None, description='Relative Strength Index if available from yfinance')
    data_quality_score: typing.Optional[float] = Field(default=None, description='Data quality score 0-1 based on completeness of input data.\n1.0 = all key fields present, 0.5 = moderate data, 0.0 = minimal data')
    confidence_level: typing.Optional[types.ConfidenceLevel] = Field(default=None, description='Confidence in signal classification')
    analysis_notes: typing.Optional[str] = Field(default=None, description='Concise analysis explaining the signal classification.\nMaximum 2-3 sentences covering:\n1. Primary signal driver and rationale\n2. Key supporting factors or risks\n3. Overall conviction level\nProfessional, institutional tone. Be concise and actionable.')
    signal_drivers: typing.Optional["SignalDrivers"] = Field(default=None, description='Quantified assessment across key factors')
    risk_factors: typing.Optional["RiskFactors"] = Field(default=None, description='Identified risks and data quality concerns')
    upside_potential_pct: typing.Optional[float] = Field(default=None, description='Estimated upside % to fair value or target')
    downside_risk_pct: typing.Optional[float] = Field(default=None, description='Estimated downside % risk to support levels')

class YFinanceAnalystData(BaseModel):
    recommendationKey: typing.Optional[str] = None
    recommendationMean: typing.Optional[float] = None
    numberOfAnalystOpinions: typing.Optional[int] = None
    averageAnalystRating: typing.Optional[str] = None

class YFinanceBalanceSheet(BaseModel):
    periods: typing.List[str]
    TotalAssets: typing.Optional[typing.List[float]] = None
    CurrentAssets: typing.Optional[typing.List[float]] = None
    CashAndCashEquivalents: typing.Optional[typing.List[float]] = None
    CashCashEquivalentsAndShortTermInvestments: typing.Optional[typing.List[float]] = None
    AccountsReceivable: typing.Optional[typing.List[float]] = None
    Inventory: typing.Optional[typing.List[float]] = None
    PropertyPlantEquipment: typing.Optional[typing.List[float]] = None
    Goodwill: typing.Optional[typing.List[float]] = None
    IntangibleAssets: typing.Optional[typing.List[float]] = None
    TotalLiabilities: typing.Optional[typing.List[float]] = None
    CurrentLiabilities: typing.Optional[typing.List[float]] = None
    AccountsPayable: typing.Optional[typing.List[float]] = None
    ShortTermDebt: typing.Optional[typing.List[float]] = None
    LongTermDebt: typing.Optional[typing.List[float]] = None
    TotalDebt: typing.Optional[typing.List[float]] = None
    StockholdersEquity: typing.Optional[typing.List[float]] = None
    RetainedEarnings: typing.Optional[typing.List[float]] = None
    TreasuryStock: typing.Optional[typing.List[float]] = None
    ShareIssued: typing.Optional[typing.List[float]] = None
    OrdinarySharesNumber: typing.Optional[typing.List[float]] = None

class YFinanceCashFlow(BaseModel):
    periods: typing.List[str]
    OperatingCashFlow: typing.Optional[typing.List[float]] = None
    CashFlowFromContinuingOperatingActivities: typing.Optional[typing.List[float]] = None
    DepreciationAndAmortization: typing.Optional[typing.List[float]] = None
    ChangeInWorkingCapital: typing.Optional[typing.List[float]] = None
    CashFlowFromInvestingActivities: typing.Optional[typing.List[float]] = None
    CapitalExpenditure: typing.Optional[typing.List[float]] = None
    NetBusinessPurchaseAndSale: typing.Optional[typing.List[float]] = None
    NetInvestmentPurchaseAndSale: typing.Optional[typing.List[float]] = None
    CashFlowFromFinancingActivities: typing.Optional[typing.List[float]] = None
    RepurchaseOfCapitalStock: typing.Optional[typing.List[float]] = None
    RepaymentOfDebt: typing.Optional[typing.List[float]] = None
    IssuanceOfDebt: typing.Optional[typing.List[float]] = None
    CashDividendsPaid: typing.Optional[typing.List[float]] = None
    FreeCashFlow: typing.Optional[typing.List[float]] = None

class YFinanceCompanyInfo(BaseModel):
    symbol: typing.Optional[str] = None
    shortName: typing.Optional[str] = None
    longName: typing.Optional[str] = None
    displayName: typing.Optional[str] = None
    sector: typing.Optional[str] = None
    sectorDisp: typing.Optional[str] = None
    sectorKey: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    industryDisp: typing.Optional[str] = None
    industryKey: typing.Optional[str] = None
    country: typing.Optional[str] = None
    state: typing.Optional[str] = None
    city: typing.Optional[str] = None
    zip: typing.Optional[str] = None
    address1: typing.Optional[str] = None
    address2: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    website: typing.Optional[str] = None
    irWebsite: typing.Optional[str] = None
    longBusinessSummary: typing.Optional[str] = None
    exchange: typing.Optional[str] = None
    fullExchangeName: typing.Optional[str] = None
    quoteSourceName: typing.Optional[str] = None
    exchangeTimezoneName: typing.Optional[str] = None
    exchangeTimezoneShortName: typing.Optional[str] = None
    fullTimeEmployees: typing.Optional[int] = None

class YFinanceDates(BaseModel):
    firstTradeDateMilliseconds: typing.Optional[int] = None
    lastFiscalYearEnd: typing.Optional[int] = None
    nextFiscalYearEnd: typing.Optional[int] = None
    mostRecentQuarter: typing.Optional[int] = None
    lastSplitDate: typing.Optional[int] = None
    lastSplitFactor: typing.Optional[str] = None
    ipoExpectedDate: typing.Optional[int] = None

class YFinanceDividendData(BaseModel):
    dividendYield: typing.Optional[float] = None
    dividendRate: typing.Optional[float] = None
    trailingAnnualDividendRate: typing.Optional[float] = None
    trailingAnnualDividendYield: typing.Optional[float] = None
    fiveYearAvgDividendYield: typing.Optional[float] = None
    dividendDate: typing.Optional[int] = None
    exDividendDate: typing.Optional[int] = None
    lastDividendDate: typing.Optional[int] = None
    lastDividendValue: typing.Optional[float] = None

class YFinanceFinancialMetrics(BaseModel):
    profitMargins: typing.Optional[float] = None
    grossMargins: typing.Optional[float] = None
    operatingMargins: typing.Optional[float] = None
    ebitdaMargins: typing.Optional[float] = None
    returnOnAssets: typing.Optional[float] = None
    returnOnEquity: typing.Optional[float] = None
    revenueGrowth: typing.Optional[float] = None
    earningsGrowth: typing.Optional[float] = None
    earningsQuarterlyGrowth: typing.Optional[float] = None
    currentRatio: typing.Optional[float] = None
    quickRatio: typing.Optional[float] = None
    debtToEquity: typing.Optional[float] = None
    payoutRatio: typing.Optional[float] = None
    grossProfits: typing.Optional[float] = None
    totalRevenue: typing.Optional[float] = None
    revenuePerShare: typing.Optional[float] = None
    netIncomeToCommon: typing.Optional[float] = None
    totalCash: typing.Optional[float] = None
    totalCashPerShare: typing.Optional[float] = None
    totalDebt: typing.Optional[float] = None
    operatingCashflow: typing.Optional[float] = None
    freeCashflow: typing.Optional[float] = None
    enterpriseToRevenue: typing.Optional[float] = None
    shortRatio: typing.Optional[float] = None
    earningsTimestampStart: typing.Optional[int] = None
    earningsTimestampEnd: typing.Optional[int] = None
    earningsTimestamp: typing.Optional[int] = None
    earningsCallTimestampStart: typing.Optional[int] = None
    earningsCallTimestampEnd: typing.Optional[int] = None
    isEarningsDateEstimate: typing.Optional[bool] = None
    trailingPegRatio: typing.Optional[float] = None

class YFinanceFinancialStatements(BaseModel):
    ticker: typing.Optional[str] = None
    income_statement: typing.Optional["YFinanceIncomeStatement"] = None
    balance_sheet: typing.Optional["YFinanceBalanceSheet"] = None
    cash_flow: typing.Optional["YFinanceCashFlow"] = None
    statement_frequency: typing.Optional[str] = None
    most_recent_period: typing.Optional[str] = None
    periods_available: typing.Optional[int] = None

class YFinanceGovernance(BaseModel):
    companyOfficers: typing.Optional[str] = None
    executiveTeam: typing.Optional[str] = None
    boardRisk: typing.Optional[int] = None
    compensationRisk: typing.Optional[int] = None
    overallRisk: typing.Optional[int] = None
    shareHolderRightsRisk: typing.Optional[int] = None
    auditRisk: typing.Optional[int] = None
    compensationAsOfEpochDate: typing.Optional[int] = None
    governanceEpochDate: typing.Optional[int] = None
    messageBoardId: typing.Optional[str] = None

class YFinanceIncomeStatement(BaseModel):
    periods: typing.List[str]
    TotalRevenue: typing.Optional[typing.List[float]] = None
    CostOfRevenue: typing.Optional[typing.List[float]] = None
    GrossProfit: typing.Optional[typing.List[float]] = None
    OperatingExpense: typing.Optional[typing.List[float]] = None
    OperatingIncome: typing.Optional[typing.List[float]] = None
    EBITDA: typing.Optional[typing.List[float]] = None
    NetIncome: typing.Optional[typing.List[float]] = None
    NetIncomeCommonStockholders: typing.Optional[typing.List[float]] = None
    BasicEPS: typing.Optional[typing.List[float]] = None
    DilutedEPS: typing.Optional[typing.List[float]] = None
    ResearchAndDevelopment: typing.Optional[typing.List[float]] = None
    SellingGeneralAndAdministration: typing.Optional[typing.List[float]] = None
    InterestExpense: typing.Optional[typing.List[float]] = None
    TaxProvision: typing.Optional[typing.List[float]] = None

class YFinanceMarketData(BaseModel):
    marketCap: typing.Optional[float] = None
    sharesOutstanding: typing.Optional[float] = None
    impliedSharesOutstanding: typing.Optional[float] = None
    floatShares: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    regularMarketVolume: typing.Optional[float] = None
    averageVolume: typing.Optional[float] = None
    averageVolume10days: typing.Optional[float] = None
    averageDailyVolume10Day: typing.Optional[float] = None
    averageDailyVolume3Month: typing.Optional[float] = None
    sharesShort: typing.Optional[float] = None
    sharesShortPriorMonth: typing.Optional[float] = None
    shortPercentOfFloat: typing.Optional[float] = None
    sharesPercentSharesOut: typing.Optional[float] = None
    sharesShortPreviousMonthDate: typing.Optional[int] = None
    dateShortInterest: typing.Optional[int] = None
    heldPercentInstitutions: typing.Optional[float] = None
    heldPercentInsiders: typing.Optional[float] = None
    market: typing.Optional[str] = None
    marketState: typing.Optional[str] = None
    hasPrePostMarketData: typing.Optional[bool] = None
    regularMarketTime: typing.Optional[int] = None
    gmtOffSetMilliseconds: typing.Optional[int] = None
    corporateActions: typing.Optional[str] = None

class YFinancePriceData(BaseModel):
    currentPrice: typing.Optional[float] = None
    regularMarketPrice: typing.Optional[float] = None
    regularMarketOpen: typing.Optional[float] = None
    open: typing.Optional[float] = None
    previousClose: typing.Optional[float] = None
    regularMarketPreviousClose: typing.Optional[float] = None
    dayHigh: typing.Optional[float] = None
    dayLow: typing.Optional[float] = None
    regularMarketDayHigh: typing.Optional[float] = None
    regularMarketDayLow: typing.Optional[float] = None
    regularMarketDayRange: typing.Optional[str] = None
    fiftyTwoWeekHigh: typing.Optional[float] = None
    fiftyTwoWeekLow: typing.Optional[float] = None
    fiftyTwoWeekHighChange: typing.Optional[float] = None
    fiftyTwoWeekLowChange: typing.Optional[float] = None
    fiftyTwoWeekHighChangePercent: typing.Optional[float] = None
    fiftyTwoWeekLowChangePercent: typing.Optional[float] = None
    fiftyTwoWeekRange: typing.Optional[str] = None
    fiftyTwoWeekChangePercent: typing.Optional[float] = None
    allTimeHigh: typing.Optional[float] = None
    allTimeLow: typing.Optional[float] = None
    bid: typing.Optional[float] = None
    ask: typing.Optional[float] = None
    bidSize: typing.Optional[int] = None
    askSize: typing.Optional[int] = None
    regularMarketChange: typing.Optional[float] = None
    regularMarketChangePercent: typing.Optional[float] = None
    postMarketPrice: typing.Optional[float] = None
    postMarketChange: typing.Optional[float] = None
    postMarketChangePercent: typing.Optional[float] = None
    postMarketTime: typing.Optional[int] = None
    targetMeanPrice: typing.Optional[float] = None
    targetMedianPrice: typing.Optional[float] = None
    targetHighPrice: typing.Optional[float] = None
    targetLowPrice: typing.Optional[float] = None
    priceToBook: typing.Optional[float] = None
    priceToSalesTrailing12Months: typing.Optional[float] = None
    priceEpsCurrentYear: typing.Optional[float] = None
    priceHint: typing.Optional[int] = None
    customPriceAlertConfidence: typing.Optional[str] = None

class YFinanceTechnicalData(BaseModel):
    fiftyDayAverage: typing.Optional[float] = None
    twoHundredDayAverage: typing.Optional[float] = None
    fiftyDayAverageChange: typing.Optional[float] = None
    twoHundredDayAverageChange: typing.Optional[float] = None
    fiftyDayAverageChangePercent: typing.Optional[float] = None
    twoHundredDayAverageChangePercent: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    SandP52WeekChange: typing.Optional[float] = None
    epsTrailingTwelveMonths: typing.Optional[float] = None
    epsCurrentYear: typing.Optional[float] = None
    epsForward: typing.Optional[float] = None
    forwardEps: typing.Optional[float] = None
    trailingEps: typing.Optional[float] = None
    trailingPE: typing.Optional[float] = None
    forwardPE: typing.Optional[float] = None
    bookValue: typing.Optional[float] = None
    ebitda: typing.Optional[float] = None
    enterpriseValue: typing.Optional[float] = None
    enterpriseToEbitda: typing.Optional[float] = None
    esgPopulated: typing.Optional[bool] = None
    quoteType: typing.Optional[str] = None
    typeDisp: typing.Optional[str] = None
    language: typing.Optional[str] = None
    region: typing.Optional[str] = None
    maxAge: typing.Optional[int] = None
    sourceInterval: typing.Optional[int] = None
    triggerable: typing.Optional[bool] = None
    fax: typing.Optional[str] = None

class YFinanceTradingInfo(BaseModel):
    currency: typing.Optional[str] = None
    financialCurrency: typing.Optional[str] = None
    exchange: typing.Optional[str] = None
    exchangeDataDelayedBy: typing.Optional[int] = None
    tradeable: typing.Optional[bool] = None
    cryptoTradeable: typing.Optional[bool] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
