# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BlackLittermanParameters": types.BlackLittermanParameters,
    "stream_types.BlackLittermanParameters": stream_types.BlackLittermanParameters,

    "types.BlackLittermanView": types.BlackLittermanView,
    "stream_types.BlackLittermanView": stream_types.BlackLittermanView,

    "types.BusinessCycleClassification": types.BusinessCycleClassification,
    "stream_types.BusinessCycleClassification": stream_types.BusinessCycleClassification,

    "types.ComprehensiveYFinanceData": types.ComprehensiveYFinanceData,
    "stream_types.ComprehensiveYFinanceData": stream_types.ComprehensiveYFinanceData,

    "types.CountryForecastData": types.CountryForecastData,
    "stream_types.CountryForecastData": stream_types.CountryForecastData,

    "types.CountryQuantitativeData": types.CountryQuantitativeData,
    "stream_types.CountryQuantitativeData": stream_types.CountryQuantitativeData,

    "types.EconomicIndicators": types.EconomicIndicators,
    "stream_types.EconomicIndicators": stream_types.EconomicIndicators,

    "types.FREDIndicators": types.FREDIndicators,
    "stream_types.FREDIndicators": stream_types.FREDIndicators,

    "types.G7CountrySnapshot": types.G7CountrySnapshot,
    "stream_types.G7CountrySnapshot": stream_types.G7CountrySnapshot,

    "types.G7MacroOverview": types.G7MacroOverview,
    "stream_types.G7MacroOverview": stream_types.G7MacroOverview,

    "types.HistoricalPerformance": types.HistoricalPerformance,
    "stream_types.HistoricalPerformance": stream_types.HistoricalPerformance,

    "types.HistoricalPriceData": types.HistoricalPriceData,
    "stream_types.HistoricalPriceData": stream_types.HistoricalPriceData,

    "types.MacroNewsSignals": types.MacroNewsSignals,
    "stream_types.MacroNewsSignals": stream_types.MacroNewsSignals,

    "types.MacroRegimeContext": types.MacroRegimeContext,
    "stream_types.MacroRegimeContext": stream_types.MacroRegimeContext,

    "types.MacroRegimeData": types.MacroRegimeData,
    "stream_types.MacroRegimeData": stream_types.MacroRegimeData,

    "types.MacroRegimeInput": types.MacroRegimeInput,
    "stream_types.MacroRegimeInput": stream_types.MacroRegimeInput,

    "types.MarketIndicators": types.MarketIndicators,
    "stream_types.MarketIndicators": stream_types.MarketIndicators,

    "types.MarketVolatilityMetrics": types.MarketVolatilityMetrics,
    "stream_types.MarketVolatilityMetrics": stream_types.MarketVolatilityMetrics,

    "types.MinimalYFinanceData": types.MinimalYFinanceData,
    "stream_types.MinimalYFinanceData": stream_types.MinimalYFinanceData,

    "types.NewsArticle": types.NewsArticle,
    "stream_types.NewsArticle": stream_types.NewsArticle,

    "types.RegimeNewsAnalysis": types.RegimeNewsAnalysis,
    "stream_types.RegimeNewsAnalysis": stream_types.RegimeNewsAnalysis,

    "types.RiskFactors": types.RiskFactors,
    "stream_types.RiskFactors": stream_types.RiskFactors,

    "types.SectorContext": types.SectorContext,
    "stream_types.SectorContext": stream_types.SectorContext,

    "types.SignalCharacteristics": types.SignalCharacteristics,
    "stream_types.SignalCharacteristics": stream_types.SignalCharacteristics,

    "types.SignalDrivers": types.SignalDrivers,
    "stream_types.SignalDrivers": stream_types.SignalDrivers,

    "types.StockNewsSignals": types.StockNewsSignals,
    "stream_types.StockNewsSignals": stream_types.StockNewsSignals,

    "types.StockSignalData": types.StockSignalData,
    "stream_types.StockSignalData": stream_types.StockSignalData,

    "types.StockSignalOutput": types.StockSignalOutput,
    "stream_types.StockSignalOutput": stream_types.StockSignalOutput,

    "types.YFinanceAnalystData": types.YFinanceAnalystData,
    "stream_types.YFinanceAnalystData": stream_types.YFinanceAnalystData,

    "types.YFinanceBalanceSheet": types.YFinanceBalanceSheet,
    "stream_types.YFinanceBalanceSheet": stream_types.YFinanceBalanceSheet,

    "types.YFinanceCashFlow": types.YFinanceCashFlow,
    "stream_types.YFinanceCashFlow": stream_types.YFinanceCashFlow,

    "types.YFinanceCompanyInfo": types.YFinanceCompanyInfo,
    "stream_types.YFinanceCompanyInfo": stream_types.YFinanceCompanyInfo,

    "types.YFinanceDates": types.YFinanceDates,
    "stream_types.YFinanceDates": stream_types.YFinanceDates,

    "types.YFinanceDividendData": types.YFinanceDividendData,
    "stream_types.YFinanceDividendData": stream_types.YFinanceDividendData,

    "types.YFinanceFinancialMetrics": types.YFinanceFinancialMetrics,
    "stream_types.YFinanceFinancialMetrics": stream_types.YFinanceFinancialMetrics,

    "types.YFinanceFinancialStatements": types.YFinanceFinancialStatements,
    "stream_types.YFinanceFinancialStatements": stream_types.YFinanceFinancialStatements,

    "types.YFinanceGovernance": types.YFinanceGovernance,
    "stream_types.YFinanceGovernance": stream_types.YFinanceGovernance,

    "types.YFinanceIncomeStatement": types.YFinanceIncomeStatement,
    "stream_types.YFinanceIncomeStatement": stream_types.YFinanceIncomeStatement,

    "types.YFinanceMarketData": types.YFinanceMarketData,
    "stream_types.YFinanceMarketData": stream_types.YFinanceMarketData,

    "types.YFinancePriceData": types.YFinancePriceData,
    "stream_types.YFinancePriceData": stream_types.YFinancePriceData,

    "types.YFinanceTechnicalData": types.YFinanceTechnicalData,
    "stream_types.YFinanceTechnicalData": stream_types.YFinanceTechnicalData,

    "types.YFinanceTradingInfo": types.YFinanceTradingInfo,
    "stream_types.YFinanceTradingInfo": stream_types.YFinanceTradingInfo,


    "types.BusinessCycleRegime": types.BusinessCycleRegime,

    "types.CompanyMomentum": types.CompanyMomentum,

    "types.CompetitivePosition": types.CompetitivePosition,

    "types.ConfidenceLevel": types.ConfidenceLevel,

    "types.CreditSpreadSignal": types.CreditSpreadSignal,

    "types.EarningsOutlook": types.EarningsOutlook,

    "types.FactorExposure": types.FactorExposure,

    "types.GrowthSentiment": types.GrowthSentiment,

    "types.ISMSignal": types.ISMSignal,

    "types.InflationSentiment": types.InflationSentiment,

    "types.LaborMarketSentiment": types.LaborMarketSentiment,

    "types.ManagementSentiment": types.ManagementSentiment,

    "types.PolicyStance": types.PolicyStance,

    "types.RegimeNarrative": types.RegimeNarrative,

    "types.RiskAppetite": types.RiskAppetite,

    "types.SignalType": types.SignalType,

    "types.YieldCurveSignal": types.YieldCurveSignal,

}