# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (17)
# #########################################################################

class BusinessCycleRegime(str, Enum):
    EARLY_CYCLE = "EARLY_CYCLE"
    MID_CYCLE = "MID_CYCLE"
    LATE_CYCLE = "LATE_CYCLE"
    RECESSION = "RECESSION"
    UNCERTAIN = "UNCERTAIN"

class CompanyMomentum(str, Enum):
    ACCELERATING = "ACCELERATING"
    POSITIVE = "POSITIVE"
    STABLE = "STABLE"
    SLOWING = "SLOWING"
    NEGATIVE = "NEGATIVE"

class CompetitivePosition(str, Enum):
    STRENGTHENING = "STRENGTHENING"
    STABLE = "STABLE"
    WEAKENING = "WEAKENING"
    UNDER_PRESSURE = "UNDER_PRESSURE"

class ConfidenceLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

class CreditSpreadSignal(str, Enum):
    TIGHT = "TIGHT"
    NEUTRAL = "NEUTRAL"
    WIDENING = "WIDENING"
    STRESS = "STRESS"

class EarningsOutlook(str, Enum):
    BEATS_EXPECTED = "BEATS_EXPECTED"
    MEETS_EXPECTED = "MEETS_EXPECTED"
    BELOW_EXPECTED = "BELOW_EXPECTED"
    UNCERTAIN = "UNCERTAIN"

class FactorExposure(str, Enum):
    GROWTH_MOMENTUM = "GROWTH_MOMENTUM"
    QUALITY_DEFENSIVE = "QUALITY_DEFENSIVE"
    BALANCED = "BALANCED"

class GrowthSentiment(str, Enum):
    ACCELERATING = "ACCELERATING"
    STABLE = "STABLE"
    SLOWING = "SLOWING"
    CONTRACTING = "CONTRACTING"

class ISMSignal(str, Enum):
    STRONG_EXPANSION = "STRONG_EXPANSION"
    MILD_EXPANSION = "MILD_EXPANSION"
    MILD_CONTRACTION = "MILD_CONTRACTION"
    DEEP_CONTRACTION = "DEEP_CONTRACTION"

class InflationSentiment(str, Enum):
    RISING = "RISING"
    STABLE = "STABLE"
    FALLING = "FALLING"
    ELEVATED = "ELEVATED"

class LaborMarketSentiment(str, Enum):
    STRONG = "STRONG"
    HEALTHY = "HEALTHY"
    SOFTENING = "SOFTENING"
    WEAK = "WEAK"

class ManagementSentiment(str, Enum):
    VERY_BULLISH = "VERY_BULLISH"
    BULLISH = "BULLISH"
    NEUTRAL = "NEUTRAL"
    CAUTIOUS = "CAUTIOUS"
    PESSIMISTIC = "PESSIMISTIC"

class PolicyStance(str, Enum):
    DOVISH = "DOVISH"
    NEUTRAL = "NEUTRAL"
    HAWKISH = "HAWKISH"
    TIGHTENING = "TIGHTENING"
    EASING = "EASING"

class RegimeNarrative(str, Enum):
    EARLY_CYCLE = "EARLY_CYCLE"
    MID_CYCLE = "MID_CYCLE"
    LATE_CYCLE = "LATE_CYCLE"
    RECESSION = "RECESSION"
    UNCERTAIN = "UNCERTAIN"

class RiskAppetite(str, Enum):
    RISK_ON = "RISK_ON"
    NEUTRAL = "NEUTRAL"
    CAUTIOUS = "CAUTIOUS"
    RISK_OFF = "RISK_OFF"
    FEAR = "FEAR"

class SignalType(str, Enum):
    LARGE_DECLINE = "LARGE_DECLINE"
    SMALL_DECLINE = "SMALL_DECLINE"
    NEUTRAL = "NEUTRAL"
    SMALL_GAIN = "SMALL_GAIN"
    LARGE_GAIN = "LARGE_GAIN"

class YieldCurveSignal(str, Enum):
    STEEP = "STEEP"
    NORMAL = "NORMAL"
    FLAT = "FLAT"
    INVERTED = "INVERTED"

# #########################################################################
# Generated classes (42)
# #########################################################################

class BlackLittermanParameters(BaseModel):
    tau: float
    delta: float
    strong_buy_return_min: float
    strong_buy_return_max: float
    buy_return_min: float
    buy_return_max: float
    uncertainty_min_pct: float
    uncertainty_max_pct: float
    confidence_scaling: float
    min_position_weight: float
    max_position_weight: float
    overall_rationale: str
    tau_rationale: str
    delta_rationale: str
    return_expectations_rationale: str
    uncertainty_rationale: str
    weight_constraints_rationale: str
    regime_multiplier: float
    volatility_adjustment: str
    confidence_adjustment: str
    parameter_risks: typing.List[str]
    monitoring_recommendations: typing.List[str]

class BlackLittermanView(BaseModel):
    ticker: str
    expected_return: float
    confidence: float
    view_uncertainty: float
    rationale: str
    factor_contributions: str
    risk_adjustments: str
    regime_adjustment: str

class BusinessCycleClassification(BaseModel):
    regime: BusinessCycleRegime
    confidence: float
    rationale: str
    ism_signal: ISMSignal
    yield_curve_signal: YieldCurveSignal
    credit_spread_signal: CreditSpreadSignal
    recession_risk_6m: float
    recession_risk_12m: float
    recession_drivers: typing.List[str]
    sector_tilts: typing.Dict[str, float]
    recommended_overweights: typing.List[str]
    recommended_underweights: typing.List[str]
    factor_exposure: FactorExposure
    primary_risks: typing.List[str]
    conflicting_signals: typing.List[str]

class ComprehensiveYFinanceData(BaseModel):
    ticker: str
    company_name: str
    price_data: typing.Optional["YFinancePriceData"] = None
    financial_metrics: typing.Optional["YFinanceFinancialMetrics"] = None
    dividend_data: typing.Optional["YFinanceDividendData"] = None
    company_info: typing.Optional["YFinanceCompanyInfo"] = None
    governance: typing.Optional["YFinanceGovernance"] = None
    market_data: typing.Optional["YFinanceMarketData"] = None
    trading_info: typing.Optional["YFinanceTradingInfo"] = None
    analyst_data: typing.Optional["YFinanceAnalystData"] = None
    dates: typing.Optional["YFinanceDates"] = None
    technical_data: typing.Optional["YFinanceTechnicalData"] = None
    data_fetch_timestamp: str
    data_completeness_pct: float
    yfinance_info_dict_size: int

class CountryForecastData(BaseModel):
    country: str
    last_inflation: typing.Optional[float] = None
    inflation_6m: typing.Optional[float] = None
    inflation_10y_avg: typing.Optional[float] = None
    gdp_growth_6m: typing.Optional[float] = None
    earnings_12m: typing.Optional[float] = None
    eps_expected_12m: typing.Optional[float] = None
    peg_ratio: typing.Optional[float] = None
    lt_rate_forecast: typing.Optional[float] = None

class CountryQuantitativeData(BaseModel):
    country: str
    gdp_growth_qq: typing.Optional[float] = None
    industrial_production: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    consumer_prices: typing.Optional[float] = None
    deficit: typing.Optional[float] = None
    debt: typing.Optional[float] = None
    st_rate: typing.Optional[float] = None
    lt_rate: typing.Optional[float] = None

class EconomicIndicators(BaseModel):
    gdp_growth_qq: typing.Optional[float] = None
    gdp_growth_yy: typing.Optional[float] = None
    gdp_forecast_6m: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    industrial_production: typing.Optional[float] = None
    capacity_utilization: typing.Optional[float] = None
    inflation: typing.Optional[float] = None
    inflation_mom: typing.Optional[float] = None
    core_inflation: typing.Optional[float] = None
    inflation_forecast: typing.Optional[float] = None
    retail_sales_mom: typing.Optional[float] = None
    earnings_growth_forecast: typing.Optional[float] = None
    business_confidence: typing.Optional[float] = None
    consumer_confidence: typing.Optional[float] = None
    trade_balance: typing.Optional[float] = None
    current_account: typing.Optional[float] = None
    current_account_gdp: typing.Optional[float] = None
    government_debt_gdp: typing.Optional[float] = None
    budget_balance_gdp: typing.Optional[float] = None

class FREDIndicators(BaseModel):
    ism_pmi: typing.Optional[float] = None
    ism_signal: typing.Optional[str] = None
    yield_curve_2s10s: typing.Optional[float] = None
    curve_signal: typing.Optional[str] = None
    hy_spread: typing.Optional[float] = None
    ig_spread: typing.Optional[float] = None
    credit_signal: typing.Optional[str] = None
    vix: typing.Optional[float] = None
    vix_signal: typing.Optional[str] = None

class G7CountrySnapshot(BaseModel):
    country: str
    gdp_growth_qq: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    inflation: typing.Optional[float] = None
    inflation_forecast_6m: typing.Optional[float] = None
    gdp_forecast_6m: typing.Optional[float] = None
    policy_rate: typing.Optional[float] = None
    regime_assessment: typing.Optional[str] = None

class G7MacroOverview(BaseModel):
    countries: typing.List["G7CountrySnapshot"]
    synchronized_slowdown: typing.Optional[bool] = None
    divergence_note: typing.Optional[str] = None
    global_growth_signal: typing.Optional[str] = None
    global_inflation_signal: typing.Optional[str] = None
    monetary_policy_direction: typing.Optional[str] = None
    key_risks: typing.List[str]

class HistoricalPerformance(BaseModel):
    recent_sharpe_ratio: typing.Optional[float] = None
    recent_turnover: typing.Optional[float] = None
    avg_tracking_error: typing.Optional[float] = None

class HistoricalPriceData(BaseModel):
    dates: typing.List[str]
    open: typing.List[float]
    high: typing.List[float]
    low: typing.List[float]
    close: typing.List[float]
    adj_close: typing.List[float]
    volume: typing.List[float]
    ticker: str
    start_date: str
    end_date: str
    trading_days_count: int
    data_quality_score: float

class MacroNewsSignals(BaseModel):
    dominant_themes: typing.List[str]
    growth_sentiment: GrowthSentiment
    growth_summary: str
    inflation_sentiment: InflationSentiment
    inflation_summary: str
    labor_market_sentiment: LaborMarketSentiment
    labor_market_summary: str
    policy_stance: PolicyStance
    policy_summary: str
    risk_appetite: RiskAppetite
    regime_narrative: RegimeNarrative
    regime_rationale: str

class MacroRegimeContext(BaseModel):
    current_regime: str
    regime_confidence: float
    recession_risk_6m: typing.Optional[float] = None
    recession_risk_12m: typing.Optional[float] = None
    vix: typing.Optional[float] = None
    hy_spread: typing.Optional[float] = None
    yield_curve_2s10s: typing.Optional[float] = None
    recommended_overweights: typing.Optional[typing.List[str]] = None
    recommended_underweights: typing.Optional[typing.List[str]] = None

class MacroRegimeData(BaseModel):
    country: str
    assessment_date: str
    regime: str
    confidence: float
    rationale: str
    ism_pmi: typing.Optional[float] = None
    ism_signal: typing.Optional[str] = None
    yield_curve_2s10s: typing.Optional[float] = None
    yield_curve_signal: typing.Optional[str] = None
    hy_spread: typing.Optional[float] = None
    credit_spread_signal: typing.Optional[str] = None
    vix: typing.Optional[float] = None
    recession_risk_6m: float
    recession_risk_12m: float
    gdp_growth_yy: typing.Optional[float] = None
    unemployment: typing.Optional[float] = None
    inflation: typing.Optional[float] = None
    recommended_overweights: typing.List[str]
    recommended_underweights: typing.List[str]
    factor_exposure: typing.Optional[str] = None
    primary_risks: typing.List[str]

class MacroRegimeInput(BaseModel):
    current_regime: str
    regime_confidence: float
    recession_risk_6m: float
    recession_risk_12m: float
    market_stress_level: str
    fred_indicators: typing.Optional["FREDIndicators"] = None
    usa_quantitative: typing.Optional["CountryQuantitativeData"] = None
    usa_forecast: typing.Optional["CountryForecastData"] = None
    regime_news_analysis: typing.Optional["RegimeNewsAnalysis"] = None
    g7_macro_overview: typing.Optional["G7MacroOverview"] = None

class MarketIndicators(BaseModel):
    ism_pmi: typing.Optional[float] = None
    manufacturing_pmi: typing.Optional[float] = None
    services_pmi: typing.Optional[float] = None
    composite_pmi: typing.Optional[float] = None
    interest_rate: typing.Optional[float] = None
    yield_curve_2s10s: typing.Optional[float] = None
    bond_yield_2y: typing.Optional[float] = None
    bond_yield_5y: typing.Optional[float] = None
    bond_yield_10y: typing.Optional[float] = None
    bond_yield_30y: typing.Optional[float] = None
    hy_spread: typing.Optional[float] = None
    vix: typing.Optional[float] = None
    vix_signal: typing.Optional[str] = None

class MarketVolatilityMetrics(BaseModel):
    current_vix: typing.Optional[float] = None
    market_realized_vol: float
    signal_universe_vol: float
    vol_regime: str

class MinimalYFinanceData(BaseModel):
    ticker: str
    company_name: str
    sector: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    currentPrice: typing.Optional[float] = None
    marketCap: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    trailingPE: typing.Optional[float] = None
    priceToBook: typing.Optional[float] = None
    returnOnEquity: typing.Optional[float] = None
    debtToEquity: typing.Optional[float] = None
    profitMargins: typing.Optional[float] = None
    revenueGrowth: typing.Optional[float] = None
    earningsGrowth: typing.Optional[float] = None
    fiftyTwoWeekChangePercent: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    recommendationKey: typing.Optional[str] = None

class NewsArticle(BaseModel):
    title: str
    publisher: str
    date: str
    link: typing.Optional[str] = None
    summary: typing.Optional[str] = None
    full_content: typing.Optional[str] = None

class RegimeNewsAnalysis(BaseModel):
    regime_analysis_summary: typing.Optional[str] = None
    news_summary: typing.Optional[str] = None
    key_news_signals: typing.List[str]
    news_alignment: typing.Optional[str] = None
    warning_signs: typing.List[str]
    leading_indicators: typing.List[str]

class RiskFactors(BaseModel):
    volatility_level: str
    beta_risk: typing.Optional[str] = None
    debt_risk: str
    liquidity_risk: str
    data_gaps: typing.List[str]
    primary_risks: typing.List[str]

class SectorContext(BaseModel):
    sector_name: str
    avg_sector_return: typing.Optional[float] = None
    sector_momentum: typing.Optional[str] = None
    sector_valuation: typing.Optional[str] = None
    num_signals_in_sector: typing.Optional[int] = None

class SignalCharacteristics(BaseModel):
    total_signals: int
    buy_signals: int
    strong_buy_signals: int
    avg_confidence: float
    confidence_dispersion: float
    signal_concentration: float

class SignalDrivers(BaseModel):
    valuation_score: float
    valuation_summary: str
    momentum_score: float
    momentum_summary: str
    quality_score: float
    quality_summary: str
    growth_score: float
    growth_summary: str
    technical_score: typing.Optional[float] = None
    technical_summary: typing.Optional[str] = None
    analyst_score: typing.Optional[float] = None
    analyst_summary: typing.Optional[str] = None

class StockNewsSignals(BaseModel):
    dominant_themes: typing.List[str]
    company_momentum: CompanyMomentum
    momentum_summary: str
    earnings_outlook: EarningsOutlook
    earnings_summary: str
    management_sentiment: ManagementSentiment
    management_summary: str
    competitive_position: CompetitivePosition
    competitive_summary: str
    key_catalysts: typing.List[str]
    key_risks: typing.List[str]
    news_bias: str
    confidence_assessment: str

class StockSignalData(BaseModel):
    ticker: str
    yfinance_ticker: str
    sector: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    signal_type: str
    confidence_level: str
    valuation_score: typing.Optional[float] = None
    momentum_score: typing.Optional[float] = None
    quality_score: typing.Optional[float] = None
    growth_score: typing.Optional[float] = None
    technical_score: typing.Optional[float] = None
    annualized_return: typing.Optional[float] = None
    volatility: typing.Optional[float] = None
    sharpe_ratio: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    alpha: typing.Optional[float] = None
    volatility_level: typing.Optional[str] = None
    beta_risk: typing.Optional[str] = None
    debt_risk: typing.Optional[str] = None
    liquidity_risk: typing.Optional[str] = None
    upside_potential_pct: typing.Optional[float] = None
    downside_risk_pct: typing.Optional[float] = None
    close_price: typing.Optional[float] = None
    daily_return: typing.Optional[float] = None

class StockSignalOutput(BaseModel):
    signal_type: SignalType
    signal_date: str
    close_price: typing.Optional[float] = None
    open_price: typing.Optional[float] = None
    daily_return: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    volatility: typing.Optional[float] = None
    rsi: typing.Optional[float] = None
    data_quality_score: float
    confidence_level: ConfidenceLevel
    analysis_notes: str
    signal_drivers: "SignalDrivers"
    risk_factors: "RiskFactors"
    upside_potential_pct: typing.Optional[float] = None
    downside_risk_pct: typing.Optional[float] = None

class YFinanceAnalystData(BaseModel):
    recommendationKey: typing.Optional[str] = None
    recommendationMean: typing.Optional[float] = None
    numberOfAnalystOpinions: typing.Optional[int] = None
    averageAnalystRating: typing.Optional[str] = None

class YFinanceBalanceSheet(BaseModel):
    periods: typing.List[str]
    TotalAssets: typing.Optional[typing.List[float]] = None
    CurrentAssets: typing.Optional[typing.List[float]] = None
    CashAndCashEquivalents: typing.Optional[typing.List[float]] = None
    CashCashEquivalentsAndShortTermInvestments: typing.Optional[typing.List[float]] = None
    AccountsReceivable: typing.Optional[typing.List[float]] = None
    Inventory: typing.Optional[typing.List[float]] = None
    PropertyPlantEquipment: typing.Optional[typing.List[float]] = None
    Goodwill: typing.Optional[typing.List[float]] = None
    IntangibleAssets: typing.Optional[typing.List[float]] = None
    TotalLiabilities: typing.Optional[typing.List[float]] = None
    CurrentLiabilities: typing.Optional[typing.List[float]] = None
    AccountsPayable: typing.Optional[typing.List[float]] = None
    ShortTermDebt: typing.Optional[typing.List[float]] = None
    LongTermDebt: typing.Optional[typing.List[float]] = None
    TotalDebt: typing.Optional[typing.List[float]] = None
    StockholdersEquity: typing.Optional[typing.List[float]] = None
    RetainedEarnings: typing.Optional[typing.List[float]] = None
    TreasuryStock: typing.Optional[typing.List[float]] = None
    ShareIssued: typing.Optional[typing.List[float]] = None
    OrdinarySharesNumber: typing.Optional[typing.List[float]] = None

class YFinanceCashFlow(BaseModel):
    periods: typing.List[str]
    OperatingCashFlow: typing.Optional[typing.List[float]] = None
    CashFlowFromContinuingOperatingActivities: typing.Optional[typing.List[float]] = None
    DepreciationAndAmortization: typing.Optional[typing.List[float]] = None
    ChangeInWorkingCapital: typing.Optional[typing.List[float]] = None
    CashFlowFromInvestingActivities: typing.Optional[typing.List[float]] = None
    CapitalExpenditure: typing.Optional[typing.List[float]] = None
    NetBusinessPurchaseAndSale: typing.Optional[typing.List[float]] = None
    NetInvestmentPurchaseAndSale: typing.Optional[typing.List[float]] = None
    CashFlowFromFinancingActivities: typing.Optional[typing.List[float]] = None
    RepurchaseOfCapitalStock: typing.Optional[typing.List[float]] = None
    RepaymentOfDebt: typing.Optional[typing.List[float]] = None
    IssuanceOfDebt: typing.Optional[typing.List[float]] = None
    CashDividendsPaid: typing.Optional[typing.List[float]] = None
    FreeCashFlow: typing.Optional[typing.List[float]] = None

class YFinanceCompanyInfo(BaseModel):
    symbol: typing.Optional[str] = None
    shortName: typing.Optional[str] = None
    longName: typing.Optional[str] = None
    displayName: typing.Optional[str] = None
    sector: typing.Optional[str] = None
    sectorDisp: typing.Optional[str] = None
    sectorKey: typing.Optional[str] = None
    industry: typing.Optional[str] = None
    industryDisp: typing.Optional[str] = None
    industryKey: typing.Optional[str] = None
    country: typing.Optional[str] = None
    state: typing.Optional[str] = None
    city: typing.Optional[str] = None
    zip: typing.Optional[str] = None
    address1: typing.Optional[str] = None
    address2: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    website: typing.Optional[str] = None
    irWebsite: typing.Optional[str] = None
    longBusinessSummary: typing.Optional[str] = None
    exchange: typing.Optional[str] = None
    fullExchangeName: typing.Optional[str] = None
    quoteSourceName: typing.Optional[str] = None
    exchangeTimezoneName: typing.Optional[str] = None
    exchangeTimezoneShortName: typing.Optional[str] = None
    fullTimeEmployees: typing.Optional[int] = None

class YFinanceDates(BaseModel):
    firstTradeDateMilliseconds: typing.Optional[int] = None
    lastFiscalYearEnd: typing.Optional[int] = None
    nextFiscalYearEnd: typing.Optional[int] = None
    mostRecentQuarter: typing.Optional[int] = None
    lastSplitDate: typing.Optional[int] = None
    lastSplitFactor: typing.Optional[str] = None
    ipoExpectedDate: typing.Optional[int] = None

class YFinanceDividendData(BaseModel):
    dividendYield: typing.Optional[float] = None
    dividendRate: typing.Optional[float] = None
    trailingAnnualDividendRate: typing.Optional[float] = None
    trailingAnnualDividendYield: typing.Optional[float] = None
    fiveYearAvgDividendYield: typing.Optional[float] = None
    dividendDate: typing.Optional[int] = None
    exDividendDate: typing.Optional[int] = None
    lastDividendDate: typing.Optional[int] = None
    lastDividendValue: typing.Optional[float] = None

class YFinanceFinancialMetrics(BaseModel):
    profitMargins: typing.Optional[float] = None
    grossMargins: typing.Optional[float] = None
    operatingMargins: typing.Optional[float] = None
    ebitdaMargins: typing.Optional[float] = None
    returnOnAssets: typing.Optional[float] = None
    returnOnEquity: typing.Optional[float] = None
    revenueGrowth: typing.Optional[float] = None
    earningsGrowth: typing.Optional[float] = None
    earningsQuarterlyGrowth: typing.Optional[float] = None
    currentRatio: typing.Optional[float] = None
    quickRatio: typing.Optional[float] = None
    debtToEquity: typing.Optional[float] = None
    payoutRatio: typing.Optional[float] = None
    grossProfits: typing.Optional[float] = None
    totalRevenue: typing.Optional[float] = None
    revenuePerShare: typing.Optional[float] = None
    netIncomeToCommon: typing.Optional[float] = None
    totalCash: typing.Optional[float] = None
    totalCashPerShare: typing.Optional[float] = None
    totalDebt: typing.Optional[float] = None
    operatingCashflow: typing.Optional[float] = None
    freeCashflow: typing.Optional[float] = None
    enterpriseToRevenue: typing.Optional[float] = None
    shortRatio: typing.Optional[float] = None
    earningsTimestampStart: typing.Optional[int] = None
    earningsTimestampEnd: typing.Optional[int] = None
    earningsTimestamp: typing.Optional[int] = None
    earningsCallTimestampStart: typing.Optional[int] = None
    earningsCallTimestampEnd: typing.Optional[int] = None
    isEarningsDateEstimate: typing.Optional[bool] = None
    trailingPegRatio: typing.Optional[float] = None

class YFinanceFinancialStatements(BaseModel):
    ticker: str
    income_statement: typing.Optional["YFinanceIncomeStatement"] = None
    balance_sheet: typing.Optional["YFinanceBalanceSheet"] = None
    cash_flow: typing.Optional["YFinanceCashFlow"] = None
    statement_frequency: str
    most_recent_period: str
    periods_available: int

class YFinanceGovernance(BaseModel):
    companyOfficers: typing.Optional[str] = None
    executiveTeam: typing.Optional[str] = None
    boardRisk: typing.Optional[int] = None
    compensationRisk: typing.Optional[int] = None
    overallRisk: typing.Optional[int] = None
    shareHolderRightsRisk: typing.Optional[int] = None
    auditRisk: typing.Optional[int] = None
    compensationAsOfEpochDate: typing.Optional[int] = None
    governanceEpochDate: typing.Optional[int] = None
    messageBoardId: typing.Optional[str] = None

class YFinanceIncomeStatement(BaseModel):
    periods: typing.List[str]
    TotalRevenue: typing.Optional[typing.List[float]] = None
    CostOfRevenue: typing.Optional[typing.List[float]] = None
    GrossProfit: typing.Optional[typing.List[float]] = None
    OperatingExpense: typing.Optional[typing.List[float]] = None
    OperatingIncome: typing.Optional[typing.List[float]] = None
    EBITDA: typing.Optional[typing.List[float]] = None
    NetIncome: typing.Optional[typing.List[float]] = None
    NetIncomeCommonStockholders: typing.Optional[typing.List[float]] = None
    BasicEPS: typing.Optional[typing.List[float]] = None
    DilutedEPS: typing.Optional[typing.List[float]] = None
    ResearchAndDevelopment: typing.Optional[typing.List[float]] = None
    SellingGeneralAndAdministration: typing.Optional[typing.List[float]] = None
    InterestExpense: typing.Optional[typing.List[float]] = None
    TaxProvision: typing.Optional[typing.List[float]] = None

class YFinanceMarketData(BaseModel):
    marketCap: typing.Optional[float] = None
    sharesOutstanding: typing.Optional[float] = None
    impliedSharesOutstanding: typing.Optional[float] = None
    floatShares: typing.Optional[float] = None
    volume: typing.Optional[float] = None
    regularMarketVolume: typing.Optional[float] = None
    averageVolume: typing.Optional[float] = None
    averageVolume10days: typing.Optional[float] = None
    averageDailyVolume10Day: typing.Optional[float] = None
    averageDailyVolume3Month: typing.Optional[float] = None
    sharesShort: typing.Optional[float] = None
    sharesShortPriorMonth: typing.Optional[float] = None
    shortPercentOfFloat: typing.Optional[float] = None
    sharesPercentSharesOut: typing.Optional[float] = None
    sharesShortPreviousMonthDate: typing.Optional[int] = None
    dateShortInterest: typing.Optional[int] = None
    heldPercentInstitutions: typing.Optional[float] = None
    heldPercentInsiders: typing.Optional[float] = None
    market: typing.Optional[str] = None
    marketState: typing.Optional[str] = None
    hasPrePostMarketData: typing.Optional[bool] = None
    regularMarketTime: typing.Optional[int] = None
    gmtOffSetMilliseconds: typing.Optional[int] = None
    corporateActions: typing.Optional[str] = None

class YFinancePriceData(BaseModel):
    currentPrice: typing.Optional[float] = None
    regularMarketPrice: typing.Optional[float] = None
    regularMarketOpen: typing.Optional[float] = None
    open: typing.Optional[float] = None
    previousClose: typing.Optional[float] = None
    regularMarketPreviousClose: typing.Optional[float] = None
    dayHigh: typing.Optional[float] = None
    dayLow: typing.Optional[float] = None
    regularMarketDayHigh: typing.Optional[float] = None
    regularMarketDayLow: typing.Optional[float] = None
    regularMarketDayRange: typing.Optional[str] = None
    fiftyTwoWeekHigh: typing.Optional[float] = None
    fiftyTwoWeekLow: typing.Optional[float] = None
    fiftyTwoWeekHighChange: typing.Optional[float] = None
    fiftyTwoWeekLowChange: typing.Optional[float] = None
    fiftyTwoWeekHighChangePercent: typing.Optional[float] = None
    fiftyTwoWeekLowChangePercent: typing.Optional[float] = None
    fiftyTwoWeekRange: typing.Optional[str] = None
    fiftyTwoWeekChangePercent: typing.Optional[float] = None
    allTimeHigh: typing.Optional[float] = None
    allTimeLow: typing.Optional[float] = None
    bid: typing.Optional[float] = None
    ask: typing.Optional[float] = None
    bidSize: typing.Optional[int] = None
    askSize: typing.Optional[int] = None
    regularMarketChange: typing.Optional[float] = None
    regularMarketChangePercent: typing.Optional[float] = None
    postMarketPrice: typing.Optional[float] = None
    postMarketChange: typing.Optional[float] = None
    postMarketChangePercent: typing.Optional[float] = None
    postMarketTime: typing.Optional[int] = None
    targetMeanPrice: typing.Optional[float] = None
    targetMedianPrice: typing.Optional[float] = None
    targetHighPrice: typing.Optional[float] = None
    targetLowPrice: typing.Optional[float] = None
    priceToBook: typing.Optional[float] = None
    priceToSalesTrailing12Months: typing.Optional[float] = None
    priceEpsCurrentYear: typing.Optional[float] = None
    priceHint: typing.Optional[int] = None
    customPriceAlertConfidence: typing.Optional[str] = None

class YFinanceTechnicalData(BaseModel):
    fiftyDayAverage: typing.Optional[float] = None
    twoHundredDayAverage: typing.Optional[float] = None
    fiftyDayAverageChange: typing.Optional[float] = None
    twoHundredDayAverageChange: typing.Optional[float] = None
    fiftyDayAverageChangePercent: typing.Optional[float] = None
    twoHundredDayAverageChangePercent: typing.Optional[float] = None
    beta: typing.Optional[float] = None
    SandP52WeekChange: typing.Optional[float] = None
    epsTrailingTwelveMonths: typing.Optional[float] = None
    epsCurrentYear: typing.Optional[float] = None
    epsForward: typing.Optional[float] = None
    forwardEps: typing.Optional[float] = None
    trailingEps: typing.Optional[float] = None
    trailingPE: typing.Optional[float] = None
    forwardPE: typing.Optional[float] = None
    bookValue: typing.Optional[float] = None
    ebitda: typing.Optional[float] = None
    enterpriseValue: typing.Optional[float] = None
    enterpriseToEbitda: typing.Optional[float] = None
    esgPopulated: typing.Optional[bool] = None
    quoteType: typing.Optional[str] = None
    typeDisp: typing.Optional[str] = None
    language: typing.Optional[str] = None
    region: typing.Optional[str] = None
    maxAge: typing.Optional[int] = None
    sourceInterval: typing.Optional[int] = None
    triggerable: typing.Optional[bool] = None
    fax: typing.Optional[str] = None

class YFinanceTradingInfo(BaseModel):
    currency: typing.Optional[str] = None
    financialCurrency: typing.Optional[str] = None
    exchange: typing.Optional[str] = None
    exchangeDataDelayedBy: typing.Optional[int] = None
    tradeable: typing.Optional[bool] = None
    cryptoTradeable: typing.Optional[bool] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
