# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class BusinessCyclePhase(str, Enum):
    EARLY_EXPANSION = "EARLY_EXPANSION"
    MID_EXPANSION = "MID_EXPANSION"
    LATE_EXPANSION = "LATE_EXPANSION"
    RECESSION = "RECESSION"

class SentimentLabel(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"
    MIXED = "MIXED"

# #########################################################################
# Generated classes (2)
# #########################################################################

class CountryNewsSummary(BaseModel):
    summary: str = Field(description='Concise macro summary (3-5 sentences) of the day\'s news for the country. Cover key economic events, policy signals, market reactions, and forward implications. Focus on market-moving themes only.')
    sentiment: SentimentLabel = Field(description='Overall macro sentiment derived from the news.')
    sentiment_score: float = Field(description='Numeric sentiment score in [-1.0, 1.0]. +1.0 = strongly bullish, -1.0 = strongly bearish, 0.0 = neutral.')

class MacroRegimeCalibration(BaseModel):
    phase: BusinessCyclePhase = Field(description='Classified business cycle phase.')
    delta: float = Field(description='Black-Litterman risk aversion scalar. Range [1.0, 10.0]. Higher = more conservative equilibrium prior.')
    tau: float = Field(description='Black-Litterman uncertainty scaling. Range [0.001, 0.1]. Higher = more weight on views vs. equilibrium.')
    confidence: float = Field(description='Classification confidence in [0.0, 1.0].')
    rationale: str = Field(description='Brief explanation of the phase classification and parameter choices.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
