# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class BusinessCyclePhase(str, Enum):
    EARLY_EXPANSION = "EARLY_EXPANSION"
    MID_EXPANSION = "MID_EXPANSION"
    LATE_EXPANSION = "LATE_EXPANSION"
    RECESSION = "RECESSION"

class CovEstimatorChoice(str, Enum):
    EMPIRICAL = "EMPIRICAL"
    LEDOIT_WOLF = "LEDOIT_WOLF"
    OAS = "OAS"
    SHRUNK = "SHRUNK"
    EW = "EW"
    GERBER = "GERBER"
    GRAPHICAL_LASSO_CV = "GRAPHICAL_LASSO_CV"
    DENOISE = "DENOISE"
    DETONE = "DETONE"
    IMPLIED = "IMPLIED"

class ExpertPersona(str, Enum):
    VALUE_INVESTOR = "VALUE_INVESTOR"
    MOMENTUM_TRADER = "MOMENTUM_TRADER"
    MACRO_ANALYST = "MACRO_ANALYST"

# #########################################################################
# Generated classes (9)
# #########################################################################

class AssetFactorData(BaseModel):
    ticker: str = Field(description='Asset ticker symbol (e.g. \'AAPL\').')
    trailing_pe: typing.Optional[float] = Field(default=None, description='Trailing price-to-earnings ratio.')
    price_to_book: typing.Optional[float] = Field(default=None, description='Price-to-book ratio.')
    ev_to_ebitda: typing.Optional[float] = Field(default=None, description='Enterprise value / EBITDA ratio.')
    momentum_12_1m: typing.Optional[float] = Field(default=None, description='12-1 month price momentum (decimal, e.g. 0.18 = +18%).')
    momentum_1m: typing.Optional[float] = Field(default=None, description='1-month price momentum (decimal). Negative = recent reversal.')
    rsi_14: typing.Optional[float] = Field(default=None, description='14-day RSI in [0, 100]. >70 overbought, <30 oversold.')
    return_on_equity: typing.Optional[float] = Field(default=None, description='Return on equity (decimal, e.g. 0.15 = 15%).')
    debt_to_equity: typing.Optional[float] = Field(default=None, description='Debt-to-equity ratio.')
    profit_margins: typing.Optional[float] = Field(default=None, description='Net profit margin (decimal).')
    revenue_growth_yoy: typing.Optional[float] = Field(default=None, description='Revenue growth year-over-year (decimal).')
    earnings_growth_yoy: typing.Optional[float] = Field(default=None, description='Earnings growth year-over-year (decimal).')
    pct_from_52w_high: typing.Optional[float] = Field(default=None, description='Distance from 52-week high (negative means below high, e.g. -0.15 = 15% below).')
    pct_from_52w_low: typing.Optional[float] = Field(default=None, description='Distance from 52-week low (positive, e.g. 0.30 = 30% above low).')
    recommendation_mean: typing.Optional[float] = Field(default=None, description='Mean analyst recommendation: 1=Strong Buy, 2=Buy, 3=Hold, 4=Sell, 5=Strong Sell.')
    target_upside: typing.Optional[float] = Field(default=None, description='(target_mean_price - current_price) / current_price. Positive = upside.')
    analyst_count: typing.Optional[int] = Field(default=None, description='Number of analysts covering the stock.')

class AssetView(BaseModel):
    asset: str = Field(description='Ticker symbol of the asset this view is about.')
    direction: int = Field(description='View direction: +1 (bullish/outperform) or -1 (bearish/underperform).')
    magnitude_bps: float = Field(description='Expected annual excess return in basis points (e.g. 200 = 2% p.a.). Always positive; sign is captured by direction.')
    confidence: float = Field(description='View confidence in (0, 1). Higher = more certain. Maps to Idzorek alpha_k.')
    reasoning: str = Field(description='One-sentence explanation referencing the factor evidence.')

class CovRegimeSelection(BaseModel):
    estimator: CovEstimatorChoice = Field(description='Recommended covariance estimator for current conditions.')
    confidence: float = Field(description='Confidence in this selection, in [0.0, 1.0].')
    rationale: str = Field(description='Brief explanation referencing the sentiment and volatility regime.')

class DeltaCalibration(BaseModel):
    delta: float = Field(description='Risk aversion scalar in [1.0, 10.0]. Higher = more risk-averse prior.')
    rationale: str = Field(description='Brief explanation of why this delta was chosen.')

class FactorWeightAdaptation(BaseModel):
    phase: BusinessCyclePhase = Field(description='Detected business cycle phase.')
    weights: typing.Dict[str, float] = Field(description='Factor group -> weight multiplier. Multipliers sum to the number of factor groups.')
    rationale: str = Field(description='Brief explanation of the phase classification and weight adjustments.')

class MacroRegimeCalibration(BaseModel):
    phase: BusinessCyclePhase = Field(description='Classified business cycle phase.')
    delta: float = Field(description='Black-Litterman risk aversion scalar. Range [1.0, 10.0]. Higher = more conservative equilibrium prior.')
    tau: float = Field(description='Black-Litterman uncertainty scaling. Range [0.001, 0.1]. Higher = more weight on views vs. equilibrium.')
    confidence: float = Field(description='Classification confidence in [0.0, 1.0].')
    rationale: str = Field(description='Brief explanation of the phase classification and parameter choices.')

class NewsArticle(BaseModel):
    title: str = Field(description='News headline to score.')

class NewsSentimentOutput(BaseModel):
    scores: typing.List[float] = Field(description='Sentiment score for each article: +1=strongly bullish, -1=strongly bearish, 0=neutral.')
    reasoning: str = Field(description='Brief overall summary of the sentiment assessment.')

class ViewOutput(BaseModel):
    views: typing.List["AssetView"] = Field(description='List of asset views. Only include assets with sufficiently strong factor evidence.')
    idzorek_alphas: typing.Dict[str, float] = Field(description='Asset ticker -> Idzorek alpha_k in (0, 1). Must include an entry for every asset in views[].')
    rationale: str = Field(description='Brief overall narrative explaining the view generation process and dominant themes.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
