import { LUCIDE_ICONS, LucideIconProvider } from 'lucide-angular';
import {
  Activity,
  ArrowDown,
  ArrowLeftRight,
  ArrowUp,
  BarChart3,
  Briefcase,
  ChevronDown,
  CircleCheck,
  CircleCheckBig,
  CircleX,
  Clock,
  Copy,
  Cpu,
  Database,
  Download,
  FileCode,
  FileDown,
  FileText,
  FlaskConical,
  Globe,
  Image,
  Info,
  Layers,
  LayoutDashboard,
  Loader2,
  Maximize,
  Menu,
  Minimize,
  Newspaper,
  PieChart,
  Play,
  Plus,
  Printer,
  RefreshCw,
  Search,
  Settings,
  Settings2,
  ShieldAlert,
  SlidersVertical,
  Sparkles,
  SquareFunction,
  Table,
  Target,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  X,
} from 'lucide-angular';

// LucideIconProvider matches template names by converting kebab-case to PascalCase
// and looking up the result in this map's keys. Most entries use the icon's own
// PascalCase identifier as the key; the three aliased entries below preserve
// existing kebab-case names from `models/jobs.model.ts` while pointing at the
// canonical (non-deprecated) icons in lucide-angular ≥ 0.477.
const icons = {
  Activity,
  ArrowDown,
  ArrowLeftRight,
  ArrowUp,
  BarChart3,
  Briefcase,
  CheckCircle: CircleCheckBig,
  ChevronDown,
  CircleCheck,
  CircleX,
  Clock,
  Copy,
  Cpu,
  Database,
  Download,
  FileCode,
  FileDown,
  FileText,
  FlaskConical,
  FunctionSquare: SquareFunction,
  Globe,
  Image,
  Info,
  Layers,
  LayoutDashboard,
  Loader2,
  Maximize,
  Menu,
  Minimize,
  Newspaper,
  PieChart,
  Play,
  Plus,
  Printer,
  RefreshCw,
  Search,
  Settings,
  Settings2,
  ShieldAlert,
  Sliders: SlidersVertical,
  Sparkles,
  Table,
  Target,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  X,
};

export const ICON_PROVIDER = {
  provide: LUCIDE_ICONS,
  multi: true,
  useValue: new LucideIconProvider(icons),
};
