"""
View Domain Model - Pure Python representation of Black-Litterman views and macro regimes.
"""

from dataclasses import dataclass, field
from datetime import date, datetime
from enum import Enum
from typing import Optional, Dict, Any, List
from uuid import UUID


class MacroRegime(str, Enum):
    """Business cycle regime classification."""
    EARLY_CYCLE = "early_cycle"
    MID_CYCLE = "mid_cycle"
    LATE_CYCLE = "late_cycle"
    RECESSION = "recession"
    UNCERTAIN = "uncertain"


class FactorExposure(str, Enum):
    """Factor timing recommendation."""
    OVERWEIGHT = "overweight"
    NEUTRAL = "neutral"
    UNDERWEIGHT = "underweight"


@dataclass(frozen=True)
class BlackLittermanViewDTO:
    """
    Data Transfer Object for Black-Litterman views.

    Represents an investor's view on an asset's expected return,
    generated by BAML AI analysis.

    Attributes:
        ticker: Asset ticker symbol
        expected_return: Expected annualized return (decimal, e.g., 0.12 for 12%)
        confidence: View confidence (0.0 to 1.0)
        view_uncertainty: Uncertainty in the view (used for Omega matrix)
        rationale: Human-readable explanation of the view
        view_type: 'absolute' (stock return) or 'relative' (vs benchmark)
        benchmark_ticker: Benchmark for relative views
        sector: Stock sector
        country: Stock country
    """

    # Required fields
    ticker: str
    expected_return: float
    confidence: float
    view_uncertainty: float

    # Optional fields
    rationale: Optional[str] = None
    view_type: str = "absolute"  # 'absolute' or 'relative'
    benchmark_ticker: Optional[str] = None
    sector: Optional[str] = None
    country: Optional[str] = None

    # Metadata
    generated_at: Optional[datetime] = None
    macro_regime: Optional[str] = None
    news_bias: Optional[str] = None  # 'positive', 'negative', 'neutral'

    def __post_init__(self):
        """Validate view parameters."""
        if not 0 <= self.confidence <= 1:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")
        if self.view_uncertainty <= 0:
            raise ValueError(f"View uncertainty must be positive, got {self.view_uncertainty}")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "ticker": self.ticker,
            "expected_return": self.expected_return,
            "confidence": self.confidence,
            "view_uncertainty": self.view_uncertainty,
            "rationale": self.rationale,
            "view_type": self.view_type,
            "benchmark_ticker": self.benchmark_ticker,
            "sector": self.sector,
            "country": self.country,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "macro_regime": self.macro_regime,
            "news_bias": self.news_bias,
        }

    @property
    def expected_return_pct(self) -> str:
        """Format expected return as percentage string."""
        return f"{self.expected_return * 100:.2f}%"


@dataclass(frozen=True)
class MacroRegimeDTO:
    """
    Data Transfer Object for macro regime assessments.

    Represents a country-level business cycle classification with
    associated recommendations.

    Attributes:
        country: Country code (e.g., 'USA', 'Germany')
        regime: Business cycle phase
        confidence: Classification confidence (0.0 to 1.0)
        assessment_timestamp: When the assessment was made

        # Recession risk
        recession_risk_6m: 6-month recession probability
        recession_risk_12m: 12-month recession probability

        # Market indicators
        vix: VIX volatility index
        hy_spread: High-yield spread (bps)
        yield_curve_2s10s: 2s10s yield curve (bps)
        ism_pmi: ISM Manufacturing PMI

        # Recommendations
        sector_tilts: Sector weight adjustments
        factor_exposure: Factor timing recommendation
        recommended_overweights: Sectors to overweight
        recommended_underweights: Sectors to underweight

        # Rationale
        rationale: Explanation of classification
        primary_risks: Key risks to monitor
        conflicting_signals: Any contradictory indicators
    """

    # Required fields
    country: str
    regime: MacroRegime
    confidence: float
    assessment_timestamp: datetime

    # Recession risk
    recession_risk_6m: Optional[float] = None
    recession_risk_12m: Optional[float] = None
    transition_probability: Optional[float] = None

    # Market indicators
    vix: Optional[float] = None
    hy_spread: Optional[float] = None
    yield_curve_2s10s: Optional[float] = None
    ism_pmi: Optional[float] = None

    # Recommendations
    sector_tilts: Dict[str, float] = field(default_factory=dict)
    factor_exposure: Optional[str] = None  # 'growth_momentum', 'quality_defensive', 'balanced'
    recommended_overweights: List[str] = field(default_factory=list)
    recommended_underweights: List[str] = field(default_factory=list)

    # Rationale
    rationale: Optional[str] = None
    primary_risks: List[str] = field(default_factory=list)
    conflicting_signals: List[str] = field(default_factory=list)

    def __post_init__(self):
        """Validate regime parameters."""
        if not 0 <= self.confidence <= 1:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")
        if self.recession_risk_6m is not None and not 0 <= self.recession_risk_6m <= 1:
            raise ValueError(f"Recession risk must be between 0 and 1")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "country": self.country,
            "regime": self.regime.value,
            "confidence": self.confidence,
            "assessment_timestamp": self.assessment_timestamp.isoformat(),
            "recession_risk_6m": self.recession_risk_6m,
            "recession_risk_12m": self.recession_risk_12m,
            "transition_probability": self.transition_probability,
            "vix": self.vix,
            "hy_spread": self.hy_spread,
            "yield_curve_2s10s": self.yield_curve_2s10s,
            "ism_pmi": self.ism_pmi,
            "sector_tilts": self.sector_tilts,
            "factor_exposure": self.factor_exposure,
            "recommended_overweights": self.recommended_overweights,
            "recommended_underweights": self.recommended_underweights,
            "rationale": self.rationale,
            "primary_risks": self.primary_risks,
            "conflicting_signals": self.conflicting_signals,
        }

    @property
    def is_defensive_regime(self) -> bool:
        """Check if current regime suggests defensive positioning."""
        return self.regime in (MacroRegime.LATE_CYCLE, MacroRegime.RECESSION)

    @property
    def is_growth_regime(self) -> bool:
        """Check if current regime favors growth stocks."""
        return self.regime in (MacroRegime.EARLY_CYCLE, MacroRegime.MID_CYCLE)

    @property
    def recession_risk_level(self) -> str:
        """Categorize recession risk level."""
        if self.recession_risk_6m is None:
            return "unknown"
        if self.recession_risk_6m < 0.15:
            return "low"
        if self.recession_risk_6m < 0.35:
            return "moderate"
        if self.recession_risk_6m < 0.60:
            return "elevated"
        return "high"
