"""All abstract interfaces (ISP)."""

from .interfaces import (
    AnalysisClientProtocol,
    ArticleScraperProtocol,
    AsyncStreamingClientProtocol,
    CacheProtocol,
    CalendarsClientProtocol,
    CircuitBreakerProtocol,
    CorporateActionsClientProtocol,
    FinancialsClientProtocol,
    FundsClientProtocol,
    HoldersClientProtocol,
    MarketClientProtocol,
    MetadataClientProtocol,
    RateLimiterProtocol,
    ScreenerClientProtocol,
    SearchClientProtocol,
    SectorIndustryClientProtocol,
    StreamingClientProtocol,
    YFinanceClientProtocol,
)

__all__ = [
    "AnalysisClientProtocol",
    "ArticleScraperProtocol",
    "AsyncStreamingClientProtocol",
    "CacheProtocol",
    "CalendarsClientProtocol",
    "CircuitBreakerProtocol",
    "CorporateActionsClientProtocol",
    "FinancialsClientProtocol",
    "FundsClientProtocol",
    "HoldersClientProtocol",
    "MarketClientProtocol",
    "MetadataClientProtocol",
    "RateLimiterProtocol",
    "ScreenerClientProtocol",
    "SearchClientProtocol",
    "SectorIndustryClientProtocol",
    "StreamingClientProtocol",
    "YFinanceClientProtocol",
]
