"""add_stock_signals_table

Revision ID: 02ed4a8dfce3
Revises: 895727b1aba5
Create Date: 2025-10-15 13:58:40.045091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ed4a8dfce3'
down_revision: Union[str, Sequence[str], None] = '895727b1aba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_signals',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('instrument_id', sa.UUID(), nullable=False, comment='Reference to the instrument (stock)'),
    sa.Column('signal_date', sa.Date(), nullable=False, comment='Date when the signal was generated'),
    sa.Column('signal_type', sa.Enum('LARGE_DECLINE', 'SMALL_DECLINE', 'NEUTRAL', 'SMALL_GAIN', 'LARGE_GAIN', name='signal_type_enum'), nullable=False, comment='Type of signal: large_decline, small_decline, neutral, small_gain, large_gain'),
    sa.Column('close_price', sa.Float(), nullable=True, comment='Closing price on signal date'),
    sa.Column('open_price', sa.Float(), nullable=True, comment='Opening price on signal date'),
    sa.Column('daily_return', sa.Float(), nullable=True, comment='Daily return percentage (close-to-close)'),
    sa.Column('volume', sa.Float(), nullable=True, comment='Trading volume on signal date'),
    sa.Column('volatility', sa.Float(), nullable=True, comment='Historical volatility measure'),
    sa.Column('rsi', sa.Float(), nullable=True, comment='Relative Strength Index (RSI) indicator'),
    sa.Column('analysis_notes', sa.Text(), nullable=True, comment='Additional notes or reasons for the signal'),
    sa.Column('data_quality_score', sa.Float(), nullable=True, comment='Data quality score (0-1) for signal reliability'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'signal_date', name='uq_stock_signals_instrument_date')
    )
    op.create_index('idx_stock_signals_date', 'stock_signals', ['signal_date'], unique=False)
    op.create_index('idx_stock_signals_date_type', 'stock_signals', ['signal_date', 'signal_type'], unique=False)
    op.create_index('idx_stock_signals_instrument_date', 'stock_signals', ['instrument_id', 'signal_date'], unique=False)
    op.create_index('idx_stock_signals_instrument_type', 'stock_signals', ['instrument_id', 'signal_type'], unique=False)
    op.create_index('idx_stock_signals_type', 'stock_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_stock_signals_instrument_id'), 'stock_signals', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_stock_signals_signal_date'), 'stock_signals', ['signal_date'], unique=False)
    op.create_index(op.f('ix_stock_signals_signal_type'), 'stock_signals', ['signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_signals_signal_type'), table_name='stock_signals')
    op.drop_index(op.f('ix_stock_signals_signal_date'), table_name='stock_signals')
    op.drop_index(op.f('ix_stock_signals_instrument_id'), table_name='stock_signals')
    op.drop_index('idx_stock_signals_type', table_name='stock_signals')
    op.drop_index('idx_stock_signals_instrument_type', table_name='stock_signals')
    op.drop_index('idx_stock_signals_instrument_date', table_name='stock_signals')
    op.drop_index('idx_stock_signals_date_type', table_name='stock_signals')
    op.drop_index('idx_stock_signals_date', table_name='stock_signals')
    op.drop_table('stock_signals')
    # ### end Alembic commands ###
