"""update

Revision ID: 03773da36e52
Revises: 7e79eee5aad3
Create Date: 2025-10-14 13:20:30.189531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03773da36e52'
down_revision: Union[str, Sequence[str], None] = '7e79eee5aad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes FIRST before changing column types
    op.drop_index(op.f('idx_baml_conf_breakdown_gin'), table_name='baml_analyses', postgresql_using='gin')
    op.drop_index(op.f('idx_assessment_conf_breakdown_gin'), table_name='country_regime_assessments', postgresql_using='gin')

    # Now alter column types
    op.alter_column('baml_analyses', 'classification_confidence_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               comment='Detailed breakdown of confidence scores by category (text explanation)',
               existing_comment='Detailed breakdown of confidence scores by category',
               existing_nullable=True)
    op.alter_column('baml_analyses', 'data_completeness',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               comment='Assessment of data completeness (detailed explanation, not just status)',
               existing_comment="Assessment of data completeness (e.g., 'complete', 'partial')",
               existing_nullable=True)
    op.alter_column('country_regime_assessments', 'classification_confidence_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               comment='Detailed breakdown of confidence scores by category (text explanation)',
               existing_comment='Detailed breakdown of confidence scores by category',
               existing_nullable=True)
    op.alter_column('country_regime_assessments', 'data_completeness',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               comment='Assessment of data completeness (detailed explanation, not just status)',
               existing_comment="Assessment of data completeness (e.g., 'complete', 'partial')",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter column types FIRST
    op.alter_column('baml_analyses', 'classification_confidence_breakdown',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Detailed breakdown of confidence scores by category',
               existing_comment='Detailed breakdown of confidence scores by category (text explanation)',
               existing_nullable=True)
    op.alter_column('baml_analyses', 'data_completeness',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               comment="Assessment of data completeness (e.g., 'complete', 'partial')",
               existing_comment='Assessment of data completeness (detailed explanation, not just status)',
               existing_nullable=True)
    op.alter_column('country_regime_assessments', 'classification_confidence_breakdown',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Detailed breakdown of confidence scores by category',
               existing_comment='Detailed breakdown of confidence scores by category (text explanation)',
               existing_nullable=True)
    op.alter_column('country_regime_assessments', 'data_completeness',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               comment="Assessment of data completeness (e.g., 'complete', 'partial')",
               existing_comment='Assessment of data completeness (detailed explanation, not just status)',
               existing_nullable=True)

    # Recreate indexes AFTER changing column types back to JSONB
    op.create_index(op.f('idx_baml_conf_breakdown_gin'), 'baml_analyses', ['classification_confidence_breakdown'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_assessment_conf_breakdown_gin'), 'country_regime_assessments', ['classification_confidence_breakdown'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
