"""add_missing_ilsole_fields_to_economic_indicators

Revision ID: 0606b93275f2
Revises: 9bccb9891105
Create Date: 2025-10-13 15:43:27.638397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0606b93275f2'
down_revision: Union[str, Sequence[str], None] = '9bccb9891105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('economic_indicators', sa.Column('consumer_prices', sa.Float(), nullable=True, comment='Consumer prices / CPI (%)'))
    op.add_column('economic_indicators', sa.Column('deficit', sa.Float(), nullable=True, comment='Government deficit as % of GDP'))
    op.add_column('economic_indicators', sa.Column('debt', sa.Float(), nullable=True, comment='Government debt as % of GDP'))
    op.add_column('economic_indicators', sa.Column('st_rate', sa.Float(), nullable=True, comment='Short-term interest rate (%)'))
    op.add_column('economic_indicators', sa.Column('lt_rate', sa.Float(), nullable=True, comment='Long-term interest rate (%)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('economic_indicators', 'lt_rate')
    op.drop_column('economic_indicators', 'st_rate')
    op.drop_column('economic_indicators', 'debt')
    op.drop_column('economic_indicators', 'deficit')
    op.drop_column('economic_indicators', 'consumer_prices')
    # ### end Alembic commands ###
