"""remove_portfolio_actions_table_and_foreign_key

Revision ID: 0abaf3b1a5c3
Revises: dbd12f8c6ee4
Create Date: 2025-10-13 17:29:57.042636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0abaf3b1a5c3'
down_revision: Union[str, Sequence[str], None] = 'dbd12f8c6ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop foreign key and column from country_regime_assessments first
    op.drop_index(op.f('ix_country_regime_assessments_portfolio_action_id'), table_name='country_regime_assessments')
    op.drop_constraint('country_regime_assessments_portfolio_action_id_fkey', 'country_regime_assessments', type_='foreignkey')
    op.drop_column('country_regime_assessments', 'portfolio_action_id')

    # Then drop the portfolio_actions table
    op.drop_index(op.f('idx_portfolio_action_regime'), table_name='portfolio_actions')
    op.drop_index(op.f('idx_portfolio_action_urgency'), table_name='portfolio_actions')
    op.drop_table('portfolio_actions')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_regime_assessments', sa.Column('portfolio_action_id', sa.UUID(), autoincrement=False, nullable=False, comment='Reference to portfolio action recommendations'))
    op.create_foreign_key(op.f('country_regime_assessments_portfolio_action_id_fkey'), 'country_regime_assessments', 'portfolio_actions', ['portfolio_action_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_country_regime_assessments_portfolio_action_id'), 'country_regime_assessments', ['portfolio_action_id'], unique=False)
    op.create_table('portfolio_actions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='UUID primary key'),
    sa.Column('regime', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='Regime this action is for'),
    sa.Column('action_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment="'ROTATE', 'MAINTAIN', 'DEFENSIVE', 'AGGRESSIVE'"),
    sa.Column('urgency', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'"),
    sa.Column('timeframe', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment="Execution timeframe (e.g., 'Next 7-14 days')"),
    sa.Column('sector_changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Sector rotation recommendations'),
    sa.Column('factor_changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Factor timing adjustments'),
    sa.Column('position_guidance', sa.TEXT(), autoincrement=False, nullable=False, comment='Position sizing guidance'),
    sa.Column('risk_adjustment', sa.TEXT(), autoincrement=False, nullable=False, comment='Risk management recommendations'),
    sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=False, comment='Detailed rationale for actions'),
    sa.Column('estimated_impact', sa.TEXT(), autoincrement=False, nullable=True, comment='Expected portfolio impact'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolio_actions_pkey'))
    )
    op.create_index(op.f('idx_portfolio_action_urgency'), 'portfolio_actions', ['urgency'], unique=False)
    op.create_index(op.f('idx_portfolio_action_regime'), 'portfolio_actions', ['regime'], unique=False)
    # ### end Alembic commands ###
