"""increase_news_sentiment_field_size

Revision ID: 2582ef12b218
Revises: 0abaf3b1a5c3
Create Date: 2025-10-13 17:47:13.713367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2582ef12b218'
down_revision: Union[str, Sequence[str], None] = '0abaf3b1a5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baml_analyses', 'news_sentiment',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment="Overall news sentiment (e.g., 'cautiously_optimistic', 'bearish')",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baml_analyses', 'news_sentiment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_comment="Overall news sentiment (e.g., 'cautiously_optimistic', 'bearish')",
               existing_nullable=True)
    # ### end Alembic commands ###
