"""Add denormalized ticker, exchange, sector, and industry columns to stock_signals

Revision ID: 48129a47f923
Revises: 6313cee5a6a8
Create Date: 2025-10-17 14:19:12.887710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48129a47f923'
down_revision: Union[str, Sequence[str], None] = '6313cee5a6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_signals', sa.Column('ticker', sa.String(length=50), nullable=True, comment='Trading212 ticker symbol (denormalized from instruments.ticker)'))
    op.add_column('stock_signals', sa.Column('yfinance_ticker', sa.String(length=20), nullable=True, comment='Yahoo Finance ticker (denormalized from instruments.yfinance_ticker)'))
    op.add_column('stock_signals', sa.Column('exchange_name', sa.String(length=255), nullable=True, comment='Exchange name (denormalized from exchanges.exchange_name)'))
    op.add_column('stock_signals', sa.Column('sector', sa.String(length=100), nullable=True, comment="Company sector from yfinance (e.g., 'Technology', 'Healthcare')"))
    op.add_column('stock_signals', sa.Column('industry', sa.String(length=200), nullable=True, comment="Company industry from yfinance (e.g., 'Software', 'Pharmaceuticals')"))
    op.create_index('idx_stock_signals_date_sector', 'stock_signals', ['signal_date', 'sector'], unique=False)
    op.create_index('idx_stock_signals_date_sector_type', 'stock_signals', ['signal_date', 'sector', 'signal_type'], unique=False)
    op.create_index('idx_stock_signals_exchange', 'stock_signals', ['exchange_name'], unique=False)
    op.create_index('idx_stock_signals_exchange_date', 'stock_signals', ['exchange_name', 'signal_date'], unique=False)
    op.create_index('idx_stock_signals_industry', 'stock_signals', ['industry'], unique=False)
    op.create_index('idx_stock_signals_sector', 'stock_signals', ['sector'], unique=False)
    op.create_index('idx_stock_signals_ticker', 'stock_signals', ['ticker'], unique=False)
    op.create_index('idx_stock_signals_yfinance_ticker', 'stock_signals', ['yfinance_ticker'], unique=False)
    op.create_index(op.f('ix_stock_signals_exchange_name'), 'stock_signals', ['exchange_name'], unique=False)
    op.create_index(op.f('ix_stock_signals_industry'), 'stock_signals', ['industry'], unique=False)
    op.create_index(op.f('ix_stock_signals_sector'), 'stock_signals', ['sector'], unique=False)
    op.create_index(op.f('ix_stock_signals_ticker'), 'stock_signals', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_signals_yfinance_ticker'), 'stock_signals', ['yfinance_ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_signals_yfinance_ticker'), table_name='stock_signals')
    op.drop_index(op.f('ix_stock_signals_ticker'), table_name='stock_signals')
    op.drop_index(op.f('ix_stock_signals_sector'), table_name='stock_signals')
    op.drop_index(op.f('ix_stock_signals_industry'), table_name='stock_signals')
    op.drop_index(op.f('ix_stock_signals_exchange_name'), table_name='stock_signals')
    op.drop_index('idx_stock_signals_yfinance_ticker', table_name='stock_signals')
    op.drop_index('idx_stock_signals_ticker', table_name='stock_signals')
    op.drop_index('idx_stock_signals_sector', table_name='stock_signals')
    op.drop_index('idx_stock_signals_industry', table_name='stock_signals')
    op.drop_index('idx_stock_signals_exchange_date', table_name='stock_signals')
    op.drop_index('idx_stock_signals_exchange', table_name='stock_signals')
    op.drop_index('idx_stock_signals_date_sector_type', table_name='stock_signals')
    op.drop_index('idx_stock_signals_date_sector', table_name='stock_signals')
    op.drop_column('stock_signals', 'industry')
    op.drop_column('stock_signals', 'sector')
    op.drop_column('stock_signals', 'exchange_name')
    op.drop_column('stock_signals', 'yfinance_ticker')
    op.drop_column('stock_signals', 'ticker')
    # ### end Alembic commands ###
