"""Add universe tables for exchanges and instruments

Revision ID: 583bf3da4b28
Revises: 65495f51f219
Create Date: 2025-10-13 11:09:06.227619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583bf3da4b28'
down_revision: Union[str, Sequence[str], None] = '65495f51f219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('exchange_id', sa.Integer(), nullable=False, comment='Trading212 exchange ID'),
    sa.Column('exchange_name', sa.String(length=255), nullable=False, comment="Exchange name (e.g., 'NYSE', 'NASDAQ')"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether exchange is currently active'),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True, comment='Last time exchange data was refreshed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exchange_id', 'exchanges', ['exchange_id'], unique=False)
    op.create_index('idx_exchange_name', 'exchanges', ['exchange_name'], unique=False)
    op.create_index(op.f('ix_exchanges_exchange_id'), 'exchanges', ['exchange_id'], unique=True)
    op.create_index(op.f('ix_exchanges_exchange_name'), 'exchanges', ['exchange_name'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('exchange_id', sa.UUID(), nullable=False, comment='Reference to parent exchange'),
    sa.Column('ticker', sa.String(length=50), nullable=False, comment="Trading212 ticker symbol (e.g., 'AAPL_US_EQ')"),
    sa.Column('short_name', sa.String(length=50), nullable=False, comment="Short ticker name (e.g., 'AAPL')"),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Full company/instrument name'),
    sa.Column('isin', sa.String(length=12), nullable=True, comment='ISIN (International Securities Identification Number)'),
    sa.Column('instrument_type', sa.String(length=20), nullable=False, comment='Instrument type (STOCK, ETF, etc.)'),
    sa.Column('currency_code', sa.String(length=3), nullable=True, comment="Trading currency (e.g., 'USD', 'EUR', 'GBP')"),
    sa.Column('max_open_quantity', sa.Float(), nullable=True, comment='Maximum open quantity allowed by Trading212'),
    sa.Column('added_on', sa.DateTime(timezone=True), nullable=True, comment='Date instrument was added to Trading212'),
    sa.Column('yfinance_ticker', sa.String(length=20), nullable=True, comment="Yahoo Finance ticker (e.g., 'AAPL', 'AAPL.L')"),
    sa.Column('filter_status', sa.String(length=30), nullable=False, comment="Filter status: 'passed', 'no_ticker', 'data_fetch_failed', 'filtered_out', 'error'"),
    sa.Column('filter_reason', sa.Text(), nullable=True, comment="Reason for filtering out (if filter_status = 'filtered_out')"),
    sa.Column('has_yfinance_data', sa.Boolean(), nullable=False, comment='Whether yfinance data is available'),
    sa.Column('data_completeness_pct', sa.Float(), nullable=True, comment='Percentage of factor components available (0-100)'),
    sa.Column('has_sufficient_history', sa.Boolean(), nullable=True, comment='Whether stock has ≥5 years of historical data'),
    sa.Column('years_available', sa.Float(), nullable=True, comment='Years of historical data available'),
    sa.Column('data_points', sa.Integer(), nullable=True, comment='Number of historical data points (trading days)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether instrument is currently active'),
    sa.Column('last_validated', sa.DateTime(timezone=True), nullable=True, comment='Last time instrument data was validated'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("filter_status IN ('passed', 'no_ticker', 'data_fetch_failed', 'filtered_out', 'error', 'pending')", name='ck_instruments_filter_status'),
    sa.CheckConstraint('data_completeness_pct IS NULL OR (data_completeness_pct >= 0 AND data_completeness_pct <= 100)', name='ck_instruments_data_completeness'),
    sa.CheckConstraint('years_available IS NULL OR years_available >= 0', name='ck_instruments_years_available'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', name='uq_instruments_ticker')
    )
    op.create_index('idx_instruments_data_quality', 'instruments', ['has_yfinance_data', 'data_completeness_pct'], unique=False)
    op.create_index('idx_instruments_exchange_id', 'instruments', ['exchange_id'], unique=False)
    op.create_index('idx_instruments_filter_status', 'instruments', ['filter_status'], unique=False)
    op.create_index('idx_instruments_isin', 'instruments', ['isin'], unique=False)
    op.create_index('idx_instruments_passed_with_yf', 'instruments', ['filter_status', 'yfinance_ticker'], unique=False)
    op.create_index('idx_instruments_short_name', 'instruments', ['short_name'], unique=False)
    op.create_index('idx_instruments_ticker', 'instruments', ['ticker'], unique=False)
    op.create_index('idx_instruments_yfinance_ticker', 'instruments', ['yfinance_ticker'], unique=False)
    op.create_index(op.f('ix_instruments_exchange_id'), 'instruments', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_instruments_filter_status'), 'instruments', ['filter_status'], unique=False)
    op.create_index(op.f('ix_instruments_isin'), 'instruments', ['isin'], unique=False)
    op.create_index(op.f('ix_instruments_short_name'), 'instruments', ['short_name'], unique=False)
    op.create_index(op.f('ix_instruments_ticker'), 'instruments', ['ticker'], unique=False)
    op.create_index(op.f('ix_instruments_yfinance_ticker'), 'instruments', ['yfinance_ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_yfinance_ticker'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_ticker'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_short_name'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_isin'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_filter_status'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_exchange_id'), table_name='instruments')
    op.drop_index('idx_instruments_yfinance_ticker', table_name='instruments')
    op.drop_index('idx_instruments_ticker', table_name='instruments')
    op.drop_index('idx_instruments_short_name', table_name='instruments')
    op.drop_index('idx_instruments_passed_with_yf', table_name='instruments')
    op.drop_index('idx_instruments_isin', table_name='instruments')
    op.drop_index('idx_instruments_filter_status', table_name='instruments')
    op.drop_index('idx_instruments_exchange_id', table_name='instruments')
    op.drop_index('idx_instruments_data_quality', table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_exchanges_exchange_name'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_exchange_id'), table_name='exchanges')
    op.drop_index('idx_exchange_name', table_name='exchanges')
    op.drop_index('idx_exchange_id', table_name='exchanges')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
