"""check database structure

Revision ID: 6313cee5a6a8
Revises: e886fd788e27
Create Date: 2025-10-17 11:16:17.214279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6313cee5a6a8'
down_revision: Union[str, Sequence[str], None] = 'e886fd788e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_signals', 'volatility',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Annualized volatility (standard deviation of returns)',
               existing_comment='Historical volatility measure',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_signals', 'volatility',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Historical volatility measure',
               existing_comment='Annualized volatility (standard deviation of returns)',
               existing_nullable=True)
    # ### end Alembic commands ###
