"""Simplify macro regime schema - align with BAML BusinessCycleClassification

Revision ID: 6abfa6e0fefd
Revises: 03773da36e52
Create Date: 2025-10-14 18:41:37.305642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6abfa6e0fefd'
down_revision: Union[str, Sequence[str], None] = '03773da36e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint FIRST before dropping baml_analyses table
    op.drop_constraint(op.f('country_regime_assessments_baml_analysis_id_fkey'), 'country_regime_assessments', type_='foreignkey')

    # Now we can drop the baml_analyses table
    op.drop_index(op.f('idx_baml_likelihood_timestamp'), table_name='baml_analyses')
    op.drop_index(op.f('idx_baml_missing_data_gin'), table_name='baml_analyses', postgresql_using='gin')
    op.drop_index(op.f('idx_baml_regime_timestamp'), table_name='baml_analyses')
    op.drop_index(op.f('idx_baml_timestamp'), table_name='baml_analyses')
    op.drop_index(op.f('ix_baml_analyses_analysis_timestamp'), table_name='baml_analyses')
    op.drop_table('baml_analyses')
    op.add_column('country_regime_assessments', sa.Column('ism_signal', sa.Enum('STRONG_EXPANSION', 'MILD_EXPANSION', 'MILD_CONTRACTION', 'DEEP_CONTRACTION', name='ismsignalenum', native_enum=False, length=30), nullable=False, comment='ISM PMI signal'))
    op.add_column('country_regime_assessments', sa.Column('yield_curve_signal', sa.Enum('STEEP', 'NORMAL', 'FLAT', 'INVERTED', name='yieldcurvesignalenum', native_enum=False, length=30), nullable=False, comment='Yield curve signal'))
    op.add_column('country_regime_assessments', sa.Column('credit_spread_signal', sa.Enum('TIGHT', 'NEUTRAL', 'WIDENING', 'STRESS', name='creditspreadsignalenum', native_enum=False, length=30), nullable=False, comment='Credit spread signal'))
    op.add_column('country_regime_assessments', sa.Column('recession_drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='2-4 key recession risk factors'))
    op.add_column('country_regime_assessments', sa.Column('recommended_overweights', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='3-5 sectors to overweight with rationale'))
    op.add_column('country_regime_assessments', sa.Column('recommended_underweights', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='3-5 sectors to underweight with rationale'))
    op.add_column('country_regime_assessments', sa.Column('factor_exposure', sa.Enum('GROWTH_MOMENTUM', 'QUALITY_DEFENSIVE', 'BALANCED', name='factorexposureenum', native_enum=False, length=30), nullable=False, comment='Factor exposure recommendation'))
    op.add_column('country_regime_assessments', sa.Column('primary_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='2-3 main risks to monitor'))
    op.add_column('country_regime_assessments', sa.Column('conflicting_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Major contradictions (empty if none)'))
    op.alter_column('country_regime_assessments', 'analysis_run_id',
               existing_type=sa.UUID(),
               comment='Reference to analysis run',
               existing_comment='Reference to parent analysis run',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'economic_indicators_id',
               existing_type=sa.UUID(),
               comment='Reference to economic indicators',
               existing_comment='Reference to country economic indicators',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment='Country code',
               existing_comment="Country code (e.g., 'USA', 'Germany')",
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'assessment_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When assessment was made',
               existing_comment='When the assessment was made',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'regime',
               existing_type=sa.VARCHAR(length=30),
               comment='Business cycle regime',
               existing_comment="Regime: 'early_cycle', 'mid_cycle', 'late_cycle', 'recession', 'uncertain'",
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Classification confidence (0.0-1.0)',
               existing_comment='Confidence in regime classification (0.0-1.0)',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'rationale',
               existing_type=sa.TEXT(),
               comment='Rationale for classification (2-3 sentences)',
               existing_comment='Human-readable rationale for regime classification',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'recession_risk_6m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='6-month recession risk (0.0-1.0)')
    op.alter_column('country_regime_assessments', 'recession_risk_12m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='12-month recession risk (0.0-1.0)')
    op.alter_column('country_regime_assessments', 'sector_tilts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Sector weight adjustments (-0.10 to +0.10)',
               existing_comment="Sector overweight/underweight recommendations (e.g., {'Technology': 0.03})",
               existing_nullable=False)
    op.drop_index(op.f('idx_assessment_country_timestamp'), table_name='country_regime_assessments')
    op.drop_index(op.f('idx_assessment_enhanced_timestamp'), table_name='country_regime_assessments')
    op.drop_index(op.f('idx_assessment_factor_timing_gin'), table_name='country_regime_assessments', postgresql_using='gin')
    op.drop_index(op.f('idx_assessment_key_risks_gin'), table_name='country_regime_assessments', postgresql_using='gin')
    op.drop_index(op.f('idx_assessment_missing_data_gin'), table_name='country_regime_assessments', postgresql_using='gin')
    op.drop_index(op.f('idx_assessment_next_regime'), table_name='country_regime_assessments')
    op.drop_index(op.f('ix_country_regime_assessments_baml_analysis_id'), table_name='country_regime_assessments')
    op.drop_constraint(op.f('uq_country_assessment_timestamp'), 'country_regime_assessments', type_='unique')
    op.create_index('idx_assessment_risks_gin', 'country_regime_assessments', ['primary_risks'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('uq_country_assessment_ts', 'country_regime_assessments', ['country', 'assessment_timestamp'])
    # Foreign key already dropped above
    op.create_table_comment(
        'country_regime_assessments',
        'Business cycle regime assessment with portfolio positioning recommendations',
        existing_comment='Business cycle regime assessment for specific countries with AI-enhanced analysis',
        schema=None
    )
    op.drop_column('country_regime_assessments', 'inflation_momentum')
    op.drop_column('country_regime_assessments', 'recession_rationale')
    op.drop_column('country_regime_assessments', 'data_completeness')
    op.drop_column('country_regime_assessments', 'market_conditions_assessment')
    op.drop_column('country_regime_assessments', 'transition_probability')
    op.drop_column('country_regime_assessments', 'classification_confidence_breakdown')
    op.drop_column('country_regime_assessments', 'key_risks')
    op.drop_column('country_regime_assessments', 'transition_timeframe')
    op.drop_column('country_regime_assessments', 'economic_momentum_assessment')
    op.drop_column('country_regime_assessments', 'missing_critical_data')
    op.drop_column('country_regime_assessments', 'baml_analysis_id')
    op.drop_column('country_regime_assessments', 'factor_timing')
    op.drop_column('country_regime_assessments', 'potential_next_regime')
    op.drop_column('country_regime_assessments', 'news_enhanced')
    op.drop_column('country_regime_assessments', 'gdp_momentum')
    op.alter_column('economic_indicators', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment='Country code',
               existing_comment="Country code (e.g., 'USA', 'Germany')",
               existing_nullable=False)
    op.alter_column('economic_indicators', 'data_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When data was fetched',
               existing_comment='When the indicator data was fetched',
               existing_nullable=False)
    op.alter_column('economic_indicators', 'gdp_growth_qq',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GDP growth QQ (%)',
               existing_comment='GDP growth quarter-over-quarter (%)',
               existing_nullable=True)
    op.alter_column('economic_indicators', 'gdp_growth_yy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GDP growth YY (%)',
               existing_comment='GDP growth year-over-year (%)',
               existing_nullable=True)
    op.alter_column('economic_indicators', 'gdp_forecast_6m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GDP forecast 6M (%)',
               existing_comment='GDP growth forecast 6-month (%)',
               existing_nullable=True)
    op.alter_column('economic_indicators', 'inflation_forecast_6m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Inflation forecast 6M (%)',
               existing_comment='Inflation forecast 6-month (%)',
               existing_nullable=True)
    op.alter_column('economic_indicators', 'earnings_forecast_12m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Earnings forecast 12M (%)',
               existing_comment='Corporate earnings growth forecast 12-month (%)',
               existing_nullable=True)
    op.drop_index(op.f('idx_econ_ind_country'), table_name='economic_indicators')
    op.drop_index(op.f('idx_econ_ind_country_timestamp'), table_name='economic_indicators')
    op.drop_index(op.f('idx_econ_ind_timestamp'), table_name='economic_indicators')
    op.drop_index(op.f('idx_econ_status_country'), table_name='economic_indicators')
    op.drop_constraint(op.f('uq_country_data_timestamp'), 'economic_indicators', type_='unique')
    op.create_index('idx_econ_country', 'economic_indicators', ['country'], unique=False)
    op.create_index('idx_econ_country_timestamp', 'economic_indicators', ['country', 'data_timestamp'], unique=False)
    op.create_index('idx_econ_timestamp', 'economic_indicators', ['data_timestamp'], unique=False)
    op.create_unique_constraint('uq_country_timestamp', 'economic_indicators', ['country', 'data_timestamp'])
    op.drop_column('economic_indicators', 'st_rate')
    op.drop_column('economic_indicators', 'lt_rate')
    op.drop_column('economic_indicators', 'retail_sales')
    op.drop_column('economic_indicators', 'debt')
    op.drop_column('economic_indicators', 'consumer_prices')
    op.drop_column('economic_indicators', 'deficit')
    op.drop_column('economic_indicators', 'status')
    op.alter_column('macro_analysis_runs', 'num_countries',
               existing_type=sa.INTEGER(),
               comment='Number of countries analyzed',
               existing_comment='Number of countries analyzed in this run',
               existing_nullable=False)
    op.alter_column('macro_analysis_runs', 'countries',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="List of country codes (e.g., ['USA', 'Germany'])",
               existing_comment="List of country codes analyzed (e.g., ['USA', 'Germany'])",
               existing_nullable=False)
    op.alter_column('macro_analysis_runs', 'notes',
               existing_type=sa.TEXT(),
               comment='Optional notes',
               existing_comment='Optional notes about this analysis run',
               existing_nullable=True)
    op.drop_index(op.f('idx_macro_run_countries_gin'), table_name='macro_analysis_runs', postgresql_using='gin')
    op.drop_index(op.f('idx_macro_run_timestamp'), table_name='macro_analysis_runs')
    op.drop_index(op.f('idx_macro_run_type'), table_name='macro_analysis_runs')
    op.drop_index(op.f('idx_macro_run_type_timestamp'), table_name='macro_analysis_runs')
    op.create_index('idx_run_countries_gin', 'macro_analysis_runs', ['countries'], unique=False, postgresql_using='gin')
    op.create_index('idx_run_timestamp', 'macro_analysis_runs', ['run_timestamp'], unique=False)
    op.create_table_comment(
        'macro_analysis_runs',
        'Top-level container for macro regime analysis run',
        existing_comment='Top-level container for macro regime analysis execution across countries',
        schema=None
    )
    op.drop_column('macro_analysis_runs', 'analysis_type')
    op.drop_column('macro_analysis_runs', 'full_content_fetched')
    op.alter_column('market_indicators', 'data_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When data was fetched',
               existing_comment='When the indicator data was fetched',
               existing_nullable=False)
    op.alter_column('market_indicators', 'yield_curve_2s10s',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='2s10s yield spread (bps)',
               existing_comment='2s10s yield curve spread (basis points)',
               existing_nullable=True)
    op.alter_column('market_indicators', 'hy_spread',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='High-yield credit spread (bps)',
               existing_comment='High-yield credit spread (basis points)',
               existing_nullable=True)
    op.drop_index(op.f('idx_market_ind_run_id'), table_name='market_indicators')
    op.drop_index(op.f('idx_market_ind_timestamp'), table_name='market_indicators')
    op.drop_index(op.f('idx_market_ind_vix'), table_name='market_indicators')
    op.drop_index(op.f('idx_market_quality_timestamp'), table_name='market_indicators')
    op.drop_constraint(op.f('uq_market_run'), 'market_indicators', type_='unique')
    op.create_index('idx_market_run_id', 'market_indicators', ['analysis_run_id'], unique=False)
    op.create_index('idx_market_timestamp', 'market_indicators', ['data_timestamp'], unique=False)
    op.create_unique_constraint('uq_market_per_run', 'market_indicators', ['analysis_run_id'])
    op.create_table_comment(
        'market_indicators',
        'Global market indicators from FRED',
        existing_comment='Global market indicators (FRED/Yahoo Finance) for analysis run',
        schema=None
    )
    op.drop_column('market_indicators', 'data_quality')
    op.drop_column('market_indicators', 'ism_signal')
    op.drop_column('market_indicators', 'credit_signal')
    op.drop_column('market_indicators', 'vix_signal')
    op.drop_column('market_indicators', 'ig_spread')
    op.drop_column('market_indicators', 'curve_signal')
    op.alter_column('news_articles', 'assessment_id',
               existing_type=sa.UUID(),
               comment='Reference to assessment',
               existing_comment='Reference to parent regime assessment',
               existing_nullable=False)
    op.alter_column('news_articles', 'publisher',
               existing_type=sa.VARCHAR(length=255),
               comment='Publisher name',
               existing_comment='Publisher/source name',
               existing_nullable=True)
    op.alter_column('news_articles', 'published_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Publication date',
               existing_comment='When the article was published',
               existing_nullable=True)
    op.alter_column('news_articles', 'link',
               existing_type=sa.TEXT(),
               comment='URL to article',
               existing_comment='URL to original article',
               existing_nullable=True)
    op.drop_index(op.f('idx_news_relevant_date'), table_name='news_articles')
    op.create_table_comment(
        'news_articles',
        'News articles used in macro regime analysis',
        existing_comment='Macroeconomic news articles used in regime analysis',
        schema=None
    )
    op.drop_column('news_articles', 'full_content')
    op.drop_column('news_articles', 'content_length')
    op.drop_column('news_articles', 'ticker_source')
    op.drop_column('news_articles', 'is_macro_relevant')
    op.alter_column('regime_transitions', 'transition_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When transition was detected',
               existing_comment='When the transition was detected',
               existing_nullable=False)
    op.alter_column('regime_transitions', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Transition confidence (0.0-1.0)',
               existing_comment='Confidence in transition (0.0-1.0)',
               existing_nullable=False)
    op.drop_index(op.f('idx_transition_alert_date'), table_name='regime_transitions')
    op.drop_index(op.f('idx_transition_country_alert'), table_name='regime_transitions')
    op.create_table_comment(
        'regime_transitions',
        'Historical regime transitions for tracking changes',
        existing_comment='Historical regime transitions for tracking changes over time',
        schema=None
    )
    op.drop_column('regime_transitions', 'alert_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regime_transitions', sa.Column('alert_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="'LOW', 'MEDIUM', 'HIGH' based on confidence"))
    op.create_table_comment(
        'regime_transitions',
        'Historical regime transitions for tracking changes over time',
        existing_comment='Historical regime transitions for tracking changes',
        schema=None
    )
    op.create_index(op.f('idx_transition_country_alert'), 'regime_transitions', ['country', 'alert_level'], unique=False)
    op.create_index(op.f('idx_transition_alert_date'), 'regime_transitions', ['alert_level', 'transition_date'], unique=False)
    op.alter_column('regime_transitions', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence in transition (0.0-1.0)',
               existing_comment='Transition confidence (0.0-1.0)',
               existing_nullable=False)
    op.alter_column('regime_transitions', 'transition_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the transition was detected',
               existing_comment='When transition was detected',
               existing_nullable=False)
    op.add_column('news_articles', sa.Column('is_macro_relevant', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether article passed macro keyword filter'))
    op.add_column('news_articles', sa.Column('ticker_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Ticker or source identifier for the article'))
    op.add_column('news_articles', sa.Column('content_length', sa.INTEGER(), autoincrement=False, nullable=True, comment='Length of article content in characters'))
    op.add_column('news_articles', sa.Column('full_content', sa.TEXT(), autoincrement=False, nullable=True, comment='Full article text content'))
    op.create_table_comment(
        'news_articles',
        'Macroeconomic news articles used in regime analysis',
        existing_comment='News articles used in macro regime analysis',
        schema=None
    )
    op.create_index(op.f('idx_news_relevant_date'), 'news_articles', ['is_macro_relevant', 'published_date'], unique=False)
    op.alter_column('news_articles', 'link',
               existing_type=sa.TEXT(),
               comment='URL to original article',
               existing_comment='URL to article',
               existing_nullable=True)
    op.alter_column('news_articles', 'published_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the article was published',
               existing_comment='Publication date',
               existing_nullable=True)
    op.alter_column('news_articles', 'publisher',
               existing_type=sa.VARCHAR(length=255),
               comment='Publisher/source name',
               existing_comment='Publisher name',
               existing_nullable=True)
    op.alter_column('news_articles', 'assessment_id',
               existing_type=sa.UUID(),
               comment='Reference to parent regime assessment',
               existing_comment='Reference to assessment',
               existing_nullable=False)
    op.add_column('market_indicators', sa.Column('curve_signal', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment="Yield curve signal: 'steep', 'normal', 'flat', 'inverted'"))
    op.add_column('market_indicators', sa.Column('ig_spread', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Investment-grade credit spread (basis points)'))
    op.add_column('market_indicators', sa.Column('vix_signal', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment="VIX regime: 'LOW_VOL', 'MEDIUM_VOL', 'HIGH_VOL', 'elevated'"))
    op.add_column('market_indicators', sa.Column('credit_signal', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment="Credit spread signal: 'risk_on', 'neutral', 'elevated', 'distress'"))
    op.add_column('market_indicators', sa.Column('ism_signal', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment="ISM signal: 'expansion', 'neutral', 'contraction'"))
    op.add_column('market_indicators', sa.Column('data_quality', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="Data quality: 'complete', 'partial', 'incomplete', 'excellent'"))
    op.create_table_comment(
        'market_indicators',
        'Global market indicators (FRED/Yahoo Finance) for analysis run',
        existing_comment='Global market indicators from FRED',
        schema=None
    )
    op.drop_constraint('uq_market_per_run', 'market_indicators', type_='unique')
    op.drop_index('idx_market_timestamp', table_name='market_indicators')
    op.drop_index('idx_market_run_id', table_name='market_indicators')
    op.create_unique_constraint(op.f('uq_market_run'), 'market_indicators', ['analysis_run_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_market_quality_timestamp'), 'market_indicators', ['data_quality', 'data_timestamp'], unique=False)
    op.create_index(op.f('idx_market_ind_vix'), 'market_indicators', ['vix'], unique=False)
    op.create_index(op.f('idx_market_ind_timestamp'), 'market_indicators', ['data_timestamp'], unique=False)
    op.create_index(op.f('idx_market_ind_run_id'), 'market_indicators', ['analysis_run_id'], unique=False)
    op.alter_column('market_indicators', 'hy_spread',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='High-yield credit spread (basis points)',
               existing_comment='High-yield credit spread (bps)',
               existing_nullable=True)
    op.alter_column('market_indicators', 'yield_curve_2s10s',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='2s10s yield curve spread (basis points)',
               existing_comment='2s10s yield spread (bps)',
               existing_nullable=True)
    op.alter_column('market_indicators', 'data_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the indicator data was fetched',
               existing_comment='When data was fetched',
               existing_nullable=False)
    op.add_column('macro_analysis_runs', sa.Column('full_content_fetched', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether full article content was fetched'))
    op.add_column('macro_analysis_runs', sa.Column('analysis_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="Analysis type: 'news_enhanced' or 'quantitative_only'"))
    op.create_table_comment(
        'macro_analysis_runs',
        'Top-level container for macro regime analysis execution across countries',
        existing_comment='Top-level container for macro regime analysis run',
        schema=None
    )
    op.drop_index('idx_run_timestamp', table_name='macro_analysis_runs')
    op.drop_index('idx_run_countries_gin', table_name='macro_analysis_runs', postgresql_using='gin')
    op.create_index(op.f('idx_macro_run_type_timestamp'), 'macro_analysis_runs', ['analysis_type', 'run_timestamp'], unique=False)
    op.create_index(op.f('idx_macro_run_type'), 'macro_analysis_runs', ['analysis_type'], unique=False)
    op.create_index(op.f('idx_macro_run_timestamp'), 'macro_analysis_runs', ['run_timestamp'], unique=False)
    op.create_index(op.f('idx_macro_run_countries_gin'), 'macro_analysis_runs', ['countries'], unique=False, postgresql_using='gin')
    op.alter_column('macro_analysis_runs', 'notes',
               existing_type=sa.TEXT(),
               comment='Optional notes about this analysis run',
               existing_comment='Optional notes',
               existing_nullable=True)
    op.alter_column('macro_analysis_runs', 'countries',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="List of country codes analyzed (e.g., ['USA', 'Germany'])",
               existing_comment="List of country codes (e.g., ['USA', 'Germany'])",
               existing_nullable=False)
    op.alter_column('macro_analysis_runs', 'num_countries',
               existing_type=sa.INTEGER(),
               comment='Number of countries analyzed in this run',
               existing_comment='Number of countries analyzed',
               existing_nullable=False)
    op.add_column('economic_indicators', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="Data status: 'complete', 'cached', 'error'"))
    op.add_column('economic_indicators', sa.Column('deficit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Government deficit as % of GDP'))
    op.add_column('economic_indicators', sa.Column('consumer_prices', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Consumer prices / CPI (%)'))
    op.add_column('economic_indicators', sa.Column('debt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Government debt as % of GDP'))
    op.add_column('economic_indicators', sa.Column('retail_sales', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Retail sales growth (%)'))
    op.add_column('economic_indicators', sa.Column('lt_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Long-term interest rate (%)'))
    op.add_column('economic_indicators', sa.Column('st_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Short-term interest rate (%)'))
    op.drop_constraint('uq_country_timestamp', 'economic_indicators', type_='unique')
    op.drop_index('idx_econ_timestamp', table_name='economic_indicators')
    op.drop_index('idx_econ_country_timestamp', table_name='economic_indicators')
    op.drop_index('idx_econ_country', table_name='economic_indicators')
    op.create_unique_constraint(op.f('uq_country_data_timestamp'), 'economic_indicators', ['country', 'data_timestamp'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_econ_status_country'), 'economic_indicators', ['status', 'country'], unique=False)
    op.create_index(op.f('idx_econ_ind_timestamp'), 'economic_indicators', ['data_timestamp'], unique=False)
    op.create_index(op.f('idx_econ_ind_country_timestamp'), 'economic_indicators', ['country', 'data_timestamp'], unique=False)
    op.create_index(op.f('idx_econ_ind_country'), 'economic_indicators', ['country'], unique=False)
    op.alter_column('economic_indicators', 'earnings_forecast_12m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Corporate earnings growth forecast 12-month (%)',
               existing_comment='Earnings forecast 12M (%)',
               existing_nullable=True)
    op.alter_column('economic_indicators', 'inflation_forecast_6m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Inflation forecast 6-month (%)',
               existing_comment='Inflation forecast 6M (%)',
               existing_nullable=True)
    op.alter_column('economic_indicators', 'gdp_forecast_6m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GDP growth forecast 6-month (%)',
               existing_comment='GDP forecast 6M (%)',
               existing_nullable=True)
    op.alter_column('economic_indicators', 'gdp_growth_yy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GDP growth year-over-year (%)',
               existing_comment='GDP growth YY (%)',
               existing_nullable=True)
    op.alter_column('economic_indicators', 'gdp_growth_qq',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GDP growth quarter-over-quarter (%)',
               existing_comment='GDP growth QQ (%)',
               existing_nullable=True)
    op.alter_column('economic_indicators', 'data_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the indicator data was fetched',
               existing_comment='When data was fetched',
               existing_nullable=False)
    op.alter_column('economic_indicators', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment="Country code (e.g., 'USA', 'Germany')",
               existing_comment='Country code',
               existing_nullable=False)
    op.add_column('country_regime_assessments', sa.Column('gdp_momentum', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="GDP momentum signal: 'strong', 'moderate', 'weak', 'contracting'"))
    op.add_column('country_regime_assessments', sa.Column('news_enhanced', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether this assessment was enhanced with news analysis'))
    op.add_column('country_regime_assessments', sa.Column('potential_next_regime', sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment='Most likely next regime if transition occurs'))
    op.add_column('country_regime_assessments', sa.Column('factor_timing', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment="Factor timing recommendations (e.g., {'Value': 'overweight'})"))
    op.add_column('country_regime_assessments', sa.Column('baml_analysis_id', sa.UUID(), autoincrement=False, nullable=True, comment='Reference to BAML analysis (if news-enhanced)'))
    op.add_column('country_regime_assessments', sa.Column('missing_critical_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of missing critical data points'))
    op.add_column('country_regime_assessments', sa.Column('economic_momentum_assessment', sa.TEXT(), autoincrement=False, nullable=True, comment='AI-generated assessment of economic momentum'))
    op.add_column('country_regime_assessments', sa.Column('transition_timeframe', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="Estimated timeframe for potential transition (e.g., '3-6 months')"))
    op.add_column('country_regime_assessments', sa.Column('key_risks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of key risks identified in the analysis'))
    op.add_column('country_regime_assessments', sa.Column('classification_confidence_breakdown', sa.TEXT(), autoincrement=False, nullable=True, comment='Detailed breakdown of confidence scores by category (text explanation)'))
    op.add_column('country_regime_assessments', sa.Column('transition_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Probability of regime transition in next 6 months (0.0-1.0)'))
    op.add_column('country_regime_assessments', sa.Column('market_conditions_assessment', sa.TEXT(), autoincrement=False, nullable=True, comment='AI-generated assessment of market conditions'))
    op.add_column('country_regime_assessments', sa.Column('data_completeness', sa.TEXT(), autoincrement=False, nullable=True, comment='Assessment of data completeness (detailed explanation, not just status)'))
    op.add_column('country_regime_assessments', sa.Column('recession_rationale', sa.TEXT(), autoincrement=False, nullable=True, comment='Detailed rationale for recession risk assessment'))
    op.add_column('country_regime_assessments', sa.Column('inflation_momentum', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="Inflation momentum signal: 'accelerating', 'stable', 'subdued', 'falling'"))
    op.create_table_comment(
        'country_regime_assessments',
        'Business cycle regime assessment for specific countries with AI-enhanced analysis',
        existing_comment='Business cycle regime assessment with portfolio positioning recommendations',
        schema=None
    )
    op.create_foreign_key(op.f('country_regime_assessments_baml_analysis_id_fkey'), 'country_regime_assessments', 'baml_analyses', ['baml_analysis_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_country_assessment_ts', 'country_regime_assessments', type_='unique')
    op.drop_index('idx_assessment_risks_gin', table_name='country_regime_assessments', postgresql_using='gin')
    op.create_unique_constraint(op.f('uq_country_assessment_timestamp'), 'country_regime_assessments', ['country', 'assessment_timestamp'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_country_regime_assessments_baml_analysis_id'), 'country_regime_assessments', ['baml_analysis_id'], unique=False)
    op.create_index(op.f('idx_assessment_next_regime'), 'country_regime_assessments', ['potential_next_regime'], unique=False)
    op.create_index(op.f('idx_assessment_missing_data_gin'), 'country_regime_assessments', ['missing_critical_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_assessment_key_risks_gin'), 'country_regime_assessments', ['key_risks'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_assessment_factor_timing_gin'), 'country_regime_assessments', ['factor_timing'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_assessment_enhanced_timestamp'), 'country_regime_assessments', ['news_enhanced', 'assessment_timestamp'], unique=False)
    op.create_index(op.f('idx_assessment_country_timestamp'), 'country_regime_assessments', ['country', 'assessment_timestamp'], unique=False)
    op.alter_column('country_regime_assessments', 'sector_tilts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Sector overweight/underweight recommendations (e.g., {'Technology': 0.03})",
               existing_comment='Sector weight adjustments (-0.10 to +0.10)',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'recession_risk_12m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='12-month recession risk (0.0-1.0)')
    op.alter_column('country_regime_assessments', 'recession_risk_6m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='6-month recession risk (0.0-1.0)')
    op.alter_column('country_regime_assessments', 'rationale',
               existing_type=sa.TEXT(),
               comment='Human-readable rationale for regime classification',
               existing_comment='Rationale for classification (2-3 sentences)',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence in regime classification (0.0-1.0)',
               existing_comment='Classification confidence (0.0-1.0)',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'regime',
               existing_type=sa.VARCHAR(length=30),
               comment="Regime: 'early_cycle', 'mid_cycle', 'late_cycle', 'recession', 'uncertain'",
               existing_comment='Business cycle regime',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'assessment_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the assessment was made',
               existing_comment='When assessment was made',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment="Country code (e.g., 'USA', 'Germany')",
               existing_comment='Country code',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'economic_indicators_id',
               existing_type=sa.UUID(),
               comment='Reference to country economic indicators',
               existing_comment='Reference to economic indicators',
               existing_nullable=False)
    op.alter_column('country_regime_assessments', 'analysis_run_id',
               existing_type=sa.UUID(),
               comment='Reference to parent analysis run',
               existing_comment='Reference to analysis run',
               existing_nullable=False)
    op.drop_column('country_regime_assessments', 'conflicting_signals')
    op.drop_column('country_regime_assessments', 'primary_risks')
    op.drop_column('country_regime_assessments', 'factor_exposure')
    op.drop_column('country_regime_assessments', 'recommended_underweights')
    op.drop_column('country_regime_assessments', 'recommended_overweights')
    op.drop_column('country_regime_assessments', 'recession_drivers')
    op.drop_column('country_regime_assessments', 'credit_spread_signal')
    op.drop_column('country_regime_assessments', 'yield_curve_signal')
    op.drop_column('country_regime_assessments', 'ism_signal')
    op.create_table('baml_analyses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('analysis_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='When BAML analysis was performed'),
    sa.Column('confidence_adjustment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Confidence adjustment from news (-1.0 to 1.0)'),
    sa.Column('adjusted_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Final adjusted confidence after news analysis (0.0 to 1.0)'),
    sa.Column('enhanced_rationale', sa.TEXT(), autoincrement=False, nullable=True, comment='Enhanced rationale incorporating news analysis'),
    sa.Column('news_sentiment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True, comment="Overall news sentiment (e.g., 'cautiously_optimistic', 'bearish')"),
    sa.Column('contradiction_warning', sa.VARCHAR(length=2000), autoincrement=False, nullable=True, comment='Warning if news contradicts quantitative signals'),
    sa.Column('risk_adjustment_6m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='6-month recession risk adjustment from news'),
    sa.Column('risk_adjustment_12m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='12-month recession risk adjustment from news'),
    sa.Column('adjusted_risk_6m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Final adjusted 6-month recession risk (0.0 to 1.0)'),
    sa.Column('adjusted_risk_12m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Final adjusted 12-month recession risk (0.0 to 1.0)'),
    sa.Column('warning_signs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of recession warning signs from news'),
    sa.Column('leading_indicators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of leading economic indicators from news'),
    sa.Column('transition_likelihood', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Likelihood of regime transition (0.0 to 1.0)'),
    sa.Column('potential_next_regime', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Most likely next regime if transition occurs'),
    sa.Column('narrative_shift', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="Narrative shift status: 'emerging', 'stable', 'accelerating'"),
    sa.Column('narrative_themes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of dominant narrative themes in news'),
    sa.Column('estimated_timeframe', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="Estimated timeframe for potential transition (e.g., '3-6 months')"),
    sa.Column('transition_signals_list', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of specific transition signals detected'),
    sa.Column('sector_adjustments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment="Sector weight adjustments from news (e.g., {'Technology': 0.02})"),
    sa.Column('leading_sectors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of leading sectors based on news sentiment'),
    sa.Column('lagging_sectors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of lagging sectors based on news sentiment'),
    sa.Column('sector_drivers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment="Sector-specific news drivers (e.g., {'Technology': 'AI boom...'})"),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('recession_rationale', sa.TEXT(), autoincrement=False, nullable=True, comment='Detailed rationale for recession risk assessment'),
    sa.Column('economic_momentum_assessment', sa.TEXT(), autoincrement=False, nullable=True, comment='AI-generated assessment of economic momentum'),
    sa.Column('market_conditions_assessment', sa.TEXT(), autoincrement=False, nullable=True, comment='AI-generated assessment of market conditions'),
    sa.Column('classification_confidence_breakdown', sa.TEXT(), autoincrement=False, nullable=True, comment='Detailed breakdown of confidence scores by category (text explanation)'),
    sa.Column('data_completeness', sa.TEXT(), autoincrement=False, nullable=True, comment='Assessment of data completeness (detailed explanation, not just status)'),
    sa.Column('missing_critical_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of missing critical data points'),
    sa.CheckConstraint("confidence_adjustment IS NULL OR confidence_adjustment >= '-1.0'::numeric::double precision AND confidence_adjustment <= 1.0::double precision", name=op.f('ck_conf_adj_range')),
    sa.CheckConstraint('adjusted_confidence IS NULL OR adjusted_confidence >= 0.0::double precision AND adjusted_confidence <= 1.0::double precision', name=op.f('ck_adj_conf_range')),
    sa.CheckConstraint('adjusted_risk_12m IS NULL OR adjusted_risk_12m >= 0.0::double precision AND adjusted_risk_12m <= 1.0::double precision', name=op.f('ck_adj_risk_12m_range')),
    sa.CheckConstraint('adjusted_risk_6m IS NULL OR adjusted_risk_6m >= 0.0::double precision AND adjusted_risk_6m <= 1.0::double precision', name=op.f('ck_adj_risk_6m_range')),
    sa.CheckConstraint('transition_likelihood IS NULL OR transition_likelihood >= 0.0::double precision AND transition_likelihood <= 1.0::double precision', name=op.f('ck_transition_like_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('baml_analyses_pkey')),
    comment='BAML AI-enhanced analysis outputs for regime assessment'
    )
    op.create_index(op.f('ix_baml_analyses_analysis_timestamp'), 'baml_analyses', ['analysis_timestamp'], unique=False)
    op.create_index(op.f('idx_baml_timestamp'), 'baml_analyses', ['analysis_timestamp'], unique=False)
    op.create_index(op.f('idx_baml_regime_timestamp'), 'baml_analyses', ['potential_next_regime', 'analysis_timestamp'], unique=False)
    op.create_index(op.f('idx_baml_missing_data_gin'), 'baml_analyses', ['missing_critical_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_baml_likelihood_timestamp'), 'baml_analyses', ['transition_likelihood', 'analysis_timestamp'], unique=False)
    # ### end Alembic commands ###
