"""added trading economics data

Revision ID: 895727b1aba5
Revises: 6abfa6e0fefd
Create Date: 2025-10-15 12:29:35.636931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895727b1aba5'
down_revision: Union[str, Sequence[str], None] = '6abfa6e0fefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_economics_snapshots',
    sa.Column('country', sa.String(length=50), nullable=False, comment='Country code (USA, Germany, France, UK, Japan)'),
    sa.Column('fetch_timestamp', sa.DateTime(timezone=True), nullable=False, comment='When data was fetched from Trading Economics'),
    sa.Column('source_url', sa.Text(), nullable=True, comment='Source URL for indicators page'),
    sa.Column('industrial_production_value', sa.Float(), nullable=True, comment='Industrial production current value'),
    sa.Column('industrial_production_previous', sa.Float(), nullable=True, comment='Industrial production previous value'),
    sa.Column('industrial_production_reference', sa.String(length=50), nullable=True, comment='Industrial production reference date'),
    sa.Column('industrial_production_unit', sa.String(length=50), nullable=True, comment='Industrial production unit'),
    sa.Column('capacity_utilization_value', sa.Float(), nullable=True, comment='Capacity utilization current value'),
    sa.Column('capacity_utilization_previous', sa.Float(), nullable=True, comment='Capacity utilization previous value'),
    sa.Column('capacity_utilization_reference', sa.String(length=50), nullable=True, comment='Capacity utilization reference date'),
    sa.Column('capacity_utilization_unit', sa.String(length=50), nullable=True, comment='Capacity utilization unit'),
    sa.Column('num_indicators', sa.Integer(), nullable=False, comment='Number of indicators fetched'),
    sa.Column('num_bond_yields', sa.Integer(), nullable=False, comment='Number of bond yields fetched'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('num_bond_yields >= 0', name='ck_num_bond_yields_positive'),
    sa.CheckConstraint('num_indicators >= 0', name='ck_num_indicators_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'fetch_timestamp', name='uq_te_country_timestamp'),
    comment='Daily Trading Economics data snapshot per country'
    )
    op.create_index('idx_te_snapshot_country', 'trading_economics_snapshots', ['country'], unique=False)
    op.create_index('idx_te_snapshot_country_timestamp', 'trading_economics_snapshots', ['country', 'fetch_timestamp'], unique=False)
    op.create_index('idx_te_snapshot_timestamp', 'trading_economics_snapshots', ['fetch_timestamp'], unique=False)
    op.create_index(op.f('ix_trading_economics_snapshots_country'), 'trading_economics_snapshots', ['country'], unique=False)
    op.create_index(op.f('ix_trading_economics_snapshots_fetch_timestamp'), 'trading_economics_snapshots', ['fetch_timestamp'], unique=False)
    op.create_table('trading_economics_bond_yields',
    sa.Column('snapshot_id', sa.UUID(), nullable=False, comment='Reference to snapshot'),
    sa.Column('maturity', sa.String(length=10), nullable=False, comment='Bond maturity (2Y, 5Y, 10Y, 30Y)'),
    sa.Column('raw_name', sa.String(length=255), nullable=False, comment='Original bond name from Trading Economics'),
    sa.Column('yield_value', sa.Float(), nullable=False, comment='Bond yield (%)'),
    sa.Column('day_change', sa.Float(), nullable=True, comment='Day change (%)'),
    sa.Column('month_change', sa.Float(), nullable=True, comment='Month change (%)'),
    sa.Column('year_change', sa.Float(), nullable=True, comment='Year change (%)'),
    sa.Column('date', sa.String(length=50), nullable=True, comment='Reference date'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('yield_value >= 0', name='ck_yield_positive'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['trading_economics_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'maturity', name='uq_te_snapshot_maturity'),
    comment='Government bond yields from Trading Economics'
    )
    op.create_index('idx_te_bond_maturity', 'trading_economics_bond_yields', ['maturity'], unique=False)
    op.create_index('idx_te_bond_snapshot', 'trading_economics_bond_yields', ['snapshot_id'], unique=False)
    op.create_index('idx_te_bond_snapshot_maturity', 'trading_economics_bond_yields', ['snapshot_id', 'maturity'], unique=False)
    op.create_index(op.f('ix_trading_economics_bond_yields_maturity'), 'trading_economics_bond_yields', ['maturity'], unique=False)
    op.create_index(op.f('ix_trading_economics_bond_yields_snapshot_id'), 'trading_economics_bond_yields', ['snapshot_id'], unique=False)
    op.create_table('trading_economics_indicators',
    sa.Column('snapshot_id', sa.UUID(), nullable=False, comment='Reference to snapshot'),
    sa.Column('indicator_name', sa.String(length=100), nullable=False, comment="Standardized indicator name (e.g., 'gdp_growth_rate')"),
    sa.Column('raw_name', sa.String(length=255), nullable=False, comment='Original indicator name from Trading Economics'),
    sa.Column('value', sa.Float(), nullable=False, comment='Current indicator value'),
    sa.Column('previous', sa.Float(), nullable=True, comment='Previous indicator value'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='Unit of measurement (%, points, etc.)'),
    sa.Column('reference', sa.String(length=50), nullable=True, comment="Reference period (e.g., 'Aug/25')"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['trading_economics_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'indicator_name', name='uq_te_snapshot_indicator'),
    comment='Individual economic indicators from Trading Economics'
    )
    op.create_index('idx_te_indicator_name', 'trading_economics_indicators', ['indicator_name'], unique=False)
    op.create_index('idx_te_indicator_snapshot', 'trading_economics_indicators', ['snapshot_id'], unique=False)
    op.create_index('idx_te_indicator_snapshot_name', 'trading_economics_indicators', ['snapshot_id', 'indicator_name'], unique=False)
    op.create_index(op.f('ix_trading_economics_indicators_indicator_name'), 'trading_economics_indicators', ['indicator_name'], unique=False)
    op.create_index(op.f('ix_trading_economics_indicators_snapshot_id'), 'trading_economics_indicators', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_economics_indicators_snapshot_id'), table_name='trading_economics_indicators')
    op.drop_index(op.f('ix_trading_economics_indicators_indicator_name'), table_name='trading_economics_indicators')
    op.drop_index('idx_te_indicator_snapshot_name', table_name='trading_economics_indicators')
    op.drop_index('idx_te_indicator_snapshot', table_name='trading_economics_indicators')
    op.drop_index('idx_te_indicator_name', table_name='trading_economics_indicators')
    op.drop_table('trading_economics_indicators')
    op.drop_index(op.f('ix_trading_economics_bond_yields_snapshot_id'), table_name='trading_economics_bond_yields')
    op.drop_index(op.f('ix_trading_economics_bond_yields_maturity'), table_name='trading_economics_bond_yields')
    op.drop_index('idx_te_bond_snapshot_maturity', table_name='trading_economics_bond_yields')
    op.drop_index('idx_te_bond_snapshot', table_name='trading_economics_bond_yields')
    op.drop_index('idx_te_bond_maturity', table_name='trading_economics_bond_yields')
    op.drop_table('trading_economics_bond_yields')
    op.drop_index(op.f('ix_trading_economics_snapshots_fetch_timestamp'), table_name='trading_economics_snapshots')
    op.drop_index(op.f('ix_trading_economics_snapshots_country'), table_name='trading_economics_snapshots')
    op.drop_index('idx_te_snapshot_timestamp', table_name='trading_economics_snapshots')
    op.drop_index('idx_te_snapshot_country_timestamp', table_name='trading_economics_snapshots')
    op.drop_index('idx_te_snapshot_country', table_name='trading_economics_snapshots')
    op.drop_table('trading_economics_snapshots')
    # ### end Alembic commands ###
