"""add_portfolio_tables

Revision ID: 9242f7444435
Revises: 4ef81ecc53c6
Create Date: 2025-10-28 23:18:24.182181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9242f7444435'
down_revision: Union[str, Sequence[str], None] = '4ef81ecc53c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_date', sa.Date(), nullable=False, comment='Date this portfolio was created/optimized'),
    sa.Column('name', sa.String(length=255), nullable=True, comment="Optional portfolio name (e.g., 'BL Optimized 20-Stock')"),
    sa.Column('optimization_method', sa.String(length=50), nullable=False, comment="Optimization method: 'black_litterman', 'concentrated', 'equal_weight', etc."),
    sa.Column('used_baml_views', sa.Boolean(), nullable=False, comment='Whether BAML AI views were used (Black-Litterman only)'),
    sa.Column('used_factor_priors', sa.Boolean(), nullable=False, comment='Whether factor-based priors were used (fallback mode)'),
    sa.Column('total_positions', sa.Integer(), nullable=False, comment='Number of positions in portfolio'),
    sa.Column('total_weight', sa.Numeric(precision=10, scale=6), nullable=False, comment='Sum of all position weights (should be 1.0 for fully invested)'),
    sa.Column('risk_aversion', sa.Numeric(precision=10, scale=4), nullable=True, comment='Risk aversion coefficient (delta) used in optimization'),
    sa.Column('tau', sa.Numeric(precision=10, scale=6), nullable=True, comment='Prior uncertainty parameter (Black-Litterman only)'),
    sa.Column('regime', sa.String(length=50), nullable=True, comment='Macro regime at portfolio creation (EARLY_CYCLE, MID_CYCLE, etc.)'),
    sa.Column('metrics', sa.JSON(), nullable=True, comment='Additional portfolio metrics (expected return, volatility, Sharpe, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolios_date_method', 'portfolios', ['portfolio_date', 'optimization_method'], unique=False)
    op.create_index(op.f('ix_portfolios_portfolio_date'), 'portfolios', ['portfolio_date'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False, comment="Trading212 ticker (e.g., 'NFLX_US_EQ')"),
    sa.Column('yfinance_ticker', sa.String(length=50), nullable=True, comment="Yahoo Finance ticker (e.g., 'NFLX')"),
    sa.Column('weight', sa.Numeric(precision=10, scale=6), nullable=False, comment='Optimized portfolio weight (0.0 to 1.0)'),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=True, comment='Stock price at portfolio creation'),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=10, scale=6), nullable=True, comment='Annualized volatility'),
    sa.Column('alpha', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('beta', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('annualized_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('signal_id', sa.UUID(), nullable=True, comment='Reference to original stock signal (if applicable)'),
    sa.Column('signal_type', sa.String(length=50), nullable=True, comment='Signal classification (LARGE_GAIN, SMALL_GAIN, etc.)'),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('conviction_tier', sa.Integer(), nullable=True, comment='Conviction tier: 1 (highest), 2, 3 (lowest)'),
    sa.Column('original_weight', sa.Numeric(precision=10, scale=6), nullable=True, comment='Weight before optimization (from ConcentratedPortfolioBuilder)'),
    sa.Column('equilibrium_return', sa.Numeric(precision=10, scale=6), nullable=True, comment='Equilibrium expected return (prior)'),
    sa.Column('posterior_return', sa.Numeric(precision=10, scale=6), nullable=True, comment='Posterior expected return (after views)'),
    sa.Column('selection_reason', sa.String(length=500), nullable=True, comment='Why this stock was selected/weighted'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_positions_portfolio_id'), 'portfolio_positions', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_positions_portfolio_ticker', 'portfolio_positions', ['portfolio_id', 'ticker'], unique=False)
    op.create_index('ix_portfolio_positions_sector', 'portfolio_positions', ['sector'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolio_positions_sector', table_name='portfolio_positions')
    op.drop_index('ix_portfolio_positions_portfolio_ticker', table_name='portfolio_positions')
    op.drop_index(op.f('ix_portfolio_positions_portfolio_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_portfolios_portfolio_date'), table_name='portfolios')
    op.drop_index('ix_portfolios_date_method', table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
