"""add_macro_regime_analysis_tables

Revision ID: 9415f504d41b
Revises: e7998a410cec
Create Date: 2025-10-13 15:13:15.832531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9415f504d41b'
down_revision: Union[str, Sequence[str], None] = 'e7998a410cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baml_analyses',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), nullable=False, comment='When BAML analysis was performed'),
    sa.Column('regime_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output from AnalyzeMacroRegimeWithNews'),
    sa.Column('recession_risk_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output from CalculateRecessionRiskFromNews'),
    sa.Column('transition_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output from DetectRegimeTransition'),
    sa.Column('sector_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output from AnalyzeSectorSignals'),
    sa.Column('raw_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete BAML outputs dictionary'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_baml_timestamp', 'baml_analyses', ['analysis_timestamp'], unique=False)
    op.create_index(op.f('ix_baml_analyses_analysis_timestamp'), 'baml_analyses', ['analysis_timestamp'], unique=False)
    op.create_table('economic_indicators',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('country', sa.String(length=50), nullable=False, comment="Country code (e.g., 'USA', 'Germany')"),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the indicator data was fetched'),
    sa.Column('gdp_growth_qq', sa.Float(), nullable=True, comment='GDP growth quarter-over-quarter (%)'),
    sa.Column('gdp_growth_yy', sa.Float(), nullable=True, comment='GDP growth year-over-year (%)'),
    sa.Column('unemployment', sa.Float(), nullable=True, comment='Unemployment rate (%)'),
    sa.Column('inflation', sa.Float(), nullable=True, comment='Inflation rate (%)'),
    sa.Column('industrial_production', sa.Float(), nullable=True, comment='Industrial production growth (%)'),
    sa.Column('retail_sales', sa.Float(), nullable=True, comment='Retail sales growth (%)'),
    sa.Column('gdp_forecast_6m', sa.Float(), nullable=True, comment='GDP growth forecast 6-month (%)'),
    sa.Column('inflation_forecast_6m', sa.Float(), nullable=True, comment='Inflation forecast 6-month (%)'),
    sa.Column('earnings_forecast_12m', sa.Float(), nullable=True, comment='Corporate earnings growth forecast 12-month (%)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Data status: 'complete', 'cached', 'error'"),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Full Il Sole data dictionary with 'real' and 'forecast' keys"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_econ_ind_country', 'economic_indicators', ['country'], unique=False)
    op.create_index('idx_econ_ind_country_timestamp', 'economic_indicators', ['country', 'data_timestamp'], unique=False)
    op.create_index('idx_econ_ind_timestamp', 'economic_indicators', ['data_timestamp'], unique=False)
    op.create_index(op.f('ix_economic_indicators_country'), 'economic_indicators', ['country'], unique=False)
    op.create_index(op.f('ix_economic_indicators_data_timestamp'), 'economic_indicators', ['data_timestamp'], unique=False)
    op.create_table('market_indicators',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the indicator data was fetched'),
    sa.Column('ism_pmi', sa.Float(), nullable=True, comment='ISM Manufacturing PMI'),
    sa.Column('yield_curve_2s10s', sa.Float(), nullable=True, comment='2s10s yield curve spread (basis points)'),
    sa.Column('hy_spread', sa.Float(), nullable=True, comment='High-yield credit spread (basis points)'),
    sa.Column('ig_spread', sa.Float(), nullable=True, comment='Investment-grade credit spread (basis points)'),
    sa.Column('vix', sa.Float(), nullable=True, comment='VIX volatility index'),
    sa.Column('vix_signal', sa.String(length=20), nullable=True, comment="VIX regime: 'LOW_VOL', 'MEDIUM_VOL', 'HIGH_VOL'"),
    sa.Column('data_quality', sa.String(length=20), nullable=False, comment="Data quality: 'complete', 'partial', 'incomplete'"),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full FRED data dictionary'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_ind_timestamp', 'market_indicators', ['data_timestamp'], unique=False)
    op.create_index('idx_market_ind_vix', 'market_indicators', ['vix'], unique=False)
    op.create_index(op.f('ix_market_indicators_data_timestamp'), 'market_indicators', ['data_timestamp'], unique=False)
    op.create_table('portfolio_actions',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('regime', sa.String(length=30), nullable=False, comment='Regime this action is for'),
    sa.Column('action_type', sa.String(length=30), nullable=False, comment="'ROTATE', 'MAINTAIN', 'DEFENSIVE', 'AGGRESSIVE'"),
    sa.Column('urgency', sa.String(length=20), nullable=False, comment="'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'"),
    sa.Column('timeframe', sa.String(length=100), nullable=False, comment="Execution timeframe (e.g., 'Next 7-14 days')"),
    sa.Column('sector_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Sector rotation recommendations'),
    sa.Column('factor_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Factor timing adjustments'),
    sa.Column('position_guidance', sa.Text(), nullable=False, comment='Position sizing guidance'),
    sa.Column('risk_adjustment', sa.Text(), nullable=False, comment='Risk management recommendations'),
    sa.Column('rationale', sa.Text(), nullable=False, comment='Detailed rationale for actions'),
    sa.Column('estimated_impact', sa.Text(), nullable=True, comment='Expected portfolio impact'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_action_regime', 'portfolio_actions', ['regime'], unique=False)
    op.create_index('idx_portfolio_action_urgency', 'portfolio_actions', ['urgency'], unique=False)
    op.create_table('macro_analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('run_timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the analysis was executed'),
    sa.Column('analysis_type', sa.String(length=50), nullable=False, comment="'news_enhanced' or 'quantitative_only'"),
    sa.Column('full_content_fetched', sa.Boolean(), nullable=False, comment='Whether full article content was fetched'),
    sa.Column('num_countries', sa.Integer(), nullable=False, comment='Number of countries analyzed in this run'),
    sa.Column('countries', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="List of country codes analyzed (e.g., ['USA', 'Germany'])"),
    sa.Column('market_indicators_id', sa.UUID(), nullable=False, comment='Reference to global market indicators (FRED data)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about this analysis run'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_indicators_id'], ['market_indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_macro_run_timestamp', 'macro_analysis_runs', ['run_timestamp'], unique=False)
    op.create_index('idx_macro_run_type', 'macro_analysis_runs', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_macro_analysis_runs_market_indicators_id'), 'macro_analysis_runs', ['market_indicators_id'], unique=False)
    op.create_index(op.f('ix_macro_analysis_runs_run_timestamp'), 'macro_analysis_runs', ['run_timestamp'], unique=False)
    op.create_table('country_regime_assessments',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False, comment='Reference to parent analysis run'),
    sa.Column('economic_indicators_id', sa.UUID(), nullable=False, comment='Reference to country economic indicators'),
    sa.Column('baml_analysis_id', sa.UUID(), nullable=True, comment='Reference to BAML analysis (if news-enhanced)'),
    sa.Column('portfolio_action_id', sa.UUID(), nullable=False, comment='Reference to portfolio action recommendations'),
    sa.Column('country', sa.String(length=50), nullable=False, comment="Country code (e.g., 'USA', 'Germany')"),
    sa.Column('assessment_timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the assessment was made'),
    sa.Column('regime', sa.String(length=30), nullable=False, comment="Regime: 'early_cycle', 'mid_cycle', 'late_cycle', 'recession', 'uncertain'"),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence in regime classification (0.0-1.0)'),
    sa.Column('transition_probability', sa.Float(), nullable=False, comment='Probability of regime transition in next 6 months (0.0-1.0)'),
    sa.Column('rationale', sa.Text(), nullable=False, comment='Human-readable rationale for regime classification'),
    sa.Column('key_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Key signals driving classification'),
    sa.Column('recession_risk_6m', sa.Float(), nullable=True, comment='6-month recession risk (0.0-1.0)'),
    sa.Column('recession_risk_12m', sa.Float(), nullable=True, comment='12-month recession risk (0.0-1.0)'),
    sa.Column('sector_tilts', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Sector overweight/underweight recommendations (e.g., {'Technology': 0.03})"),
    sa.Column('factor_timing', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Factor timing recommendations (e.g., {'Value': 'overweight'})"),
    sa.Column('news_enhanced', sa.Boolean(), nullable=False, comment='Whether this assessment was enhanced with news analysis'),
    sa.Column('news_summary', sa.Text(), nullable=True, comment='Summary of news sentiment from BAML'),
    sa.Column('news_alignment', sa.String(length=50), nullable=True, comment="News alignment with quantitative signals: 'aligned', 'contradicts', 'mixed'"),
    sa.Column('news_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Key news signals identified by BAML'),
    sa.Column('news_based_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Warnings from news analysis'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['macro_analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['baml_analysis_id'], ['baml_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['economic_indicators_id'], ['economic_indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_action_id'], ['portfolio_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessment_country', 'country_regime_assessments', ['country'], unique=False)
    op.create_index('idx_assessment_country_timestamp', 'country_regime_assessments', ['country', 'assessment_timestamp'], unique=False)
    op.create_index('idx_assessment_regime', 'country_regime_assessments', ['regime'], unique=False)
    op.create_index('idx_assessment_timestamp', 'country_regime_assessments', ['assessment_timestamp'], unique=False)
    op.create_index(op.f('ix_country_regime_assessments_analysis_run_id'), 'country_regime_assessments', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_country_regime_assessments_assessment_timestamp'), 'country_regime_assessments', ['assessment_timestamp'], unique=False)
    op.create_index(op.f('ix_country_regime_assessments_baml_analysis_id'), 'country_regime_assessments', ['baml_analysis_id'], unique=False)
    op.create_index(op.f('ix_country_regime_assessments_country'), 'country_regime_assessments', ['country'], unique=False)
    op.create_index(op.f('ix_country_regime_assessments_economic_indicators_id'), 'country_regime_assessments', ['economic_indicators_id'], unique=False)
    op.create_index(op.f('ix_country_regime_assessments_portfolio_action_id'), 'country_regime_assessments', ['portfolio_action_id'], unique=False)
    op.create_index(op.f('ix_country_regime_assessments_regime'), 'country_regime_assessments', ['regime'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('assessment_id', sa.UUID(), nullable=False, comment='Reference to parent regime assessment'),
    sa.Column('title', sa.Text(), nullable=False, comment='Article title'),
    sa.Column('publisher', sa.String(length=255), nullable=True, comment='Publisher/source name'),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True, comment='When the article was published'),
    sa.Column('link', sa.Text(), nullable=True, comment='URL to original article'),
    sa.Column('full_content', sa.Text(), nullable=True, comment='Full article text content'),
    sa.Column('is_macro_relevant', sa.Boolean(), nullable=False, comment='Whether article passed macro keyword filter'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['country_regime_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_assessment_id', 'news_articles', ['assessment_id'], unique=False)
    op.create_index('idx_news_published_date', 'news_articles', ['published_date'], unique=False)
    op.create_index(op.f('ix_news_articles_assessment_id'), 'news_articles', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_date'), 'news_articles', ['published_date'], unique=False)
    op.create_table('regime_transitions',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('assessment_id', sa.UUID(), nullable=False, comment='Reference to assessment where transition occurred'),
    sa.Column('country', sa.String(length=50), nullable=False, comment='Country code'),
    sa.Column('transition_date', sa.DateTime(timezone=True), nullable=False, comment='When the transition was detected'),
    sa.Column('from_regime', sa.String(length=30), nullable=False, comment='Previous regime'),
    sa.Column('to_regime', sa.String(length=30), nullable=False, comment='New regime'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence in transition (0.0-1.0)'),
    sa.Column('alert_level', sa.String(length=20), nullable=False, comment="'LOW', 'MEDIUM', 'HIGH' based on confidence"),
    sa.Column('days_since_last_transition', sa.Integer(), nullable=True, comment='Days since previous transition'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['country_regime_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transition_country', 'regime_transitions', ['country'], unique=False)
    op.create_index('idx_transition_country_date', 'regime_transitions', ['country', 'transition_date'], unique=False)
    op.create_index('idx_transition_date', 'regime_transitions', ['transition_date'], unique=False)
    op.create_index('idx_transition_from_to', 'regime_transitions', ['from_regime', 'to_regime'], unique=False)
    op.create_index(op.f('ix_regime_transitions_assessment_id'), 'regime_transitions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_regime_transitions_country'), 'regime_transitions', ['country'], unique=False)
    op.create_index(op.f('ix_regime_transitions_transition_date'), 'regime_transitions', ['transition_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regime_transitions_transition_date'), table_name='regime_transitions')
    op.drop_index(op.f('ix_regime_transitions_country'), table_name='regime_transitions')
    op.drop_index(op.f('ix_regime_transitions_assessment_id'), table_name='regime_transitions')
    op.drop_index('idx_transition_from_to', table_name='regime_transitions')
    op.drop_index('idx_transition_date', table_name='regime_transitions')
    op.drop_index('idx_transition_country_date', table_name='regime_transitions')
    op.drop_index('idx_transition_country', table_name='regime_transitions')
    op.drop_table('regime_transitions')
    op.drop_index(op.f('ix_news_articles_published_date'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_assessment_id'), table_name='news_articles')
    op.drop_index('idx_news_published_date', table_name='news_articles')
    op.drop_index('idx_news_assessment_id', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_country_regime_assessments_regime'), table_name='country_regime_assessments')
    op.drop_index(op.f('ix_country_regime_assessments_portfolio_action_id'), table_name='country_regime_assessments')
    op.drop_index(op.f('ix_country_regime_assessments_economic_indicators_id'), table_name='country_regime_assessments')
    op.drop_index(op.f('ix_country_regime_assessments_country'), table_name='country_regime_assessments')
    op.drop_index(op.f('ix_country_regime_assessments_baml_analysis_id'), table_name='country_regime_assessments')
    op.drop_index(op.f('ix_country_regime_assessments_assessment_timestamp'), table_name='country_regime_assessments')
    op.drop_index(op.f('ix_country_regime_assessments_analysis_run_id'), table_name='country_regime_assessments')
    op.drop_index('idx_assessment_timestamp', table_name='country_regime_assessments')
    op.drop_index('idx_assessment_regime', table_name='country_regime_assessments')
    op.drop_index('idx_assessment_country_timestamp', table_name='country_regime_assessments')
    op.drop_index('idx_assessment_country', table_name='country_regime_assessments')
    op.drop_table('country_regime_assessments')
    op.drop_index(op.f('ix_macro_analysis_runs_run_timestamp'), table_name='macro_analysis_runs')
    op.drop_index(op.f('ix_macro_analysis_runs_market_indicators_id'), table_name='macro_analysis_runs')
    op.drop_index('idx_macro_run_type', table_name='macro_analysis_runs')
    op.drop_index('idx_macro_run_timestamp', table_name='macro_analysis_runs')
    op.drop_table('macro_analysis_runs')
    op.drop_index('idx_portfolio_action_urgency', table_name='portfolio_actions')
    op.drop_index('idx_portfolio_action_regime', table_name='portfolio_actions')
    op.drop_table('portfolio_actions')
    op.drop_index(op.f('ix_market_indicators_data_timestamp'), table_name='market_indicators')
    op.drop_index('idx_market_ind_vix', table_name='market_indicators')
    op.drop_index('idx_market_ind_timestamp', table_name='market_indicators')
    op.drop_table('market_indicators')
    op.drop_index(op.f('ix_economic_indicators_data_timestamp'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_country'), table_name='economic_indicators')
    op.drop_index('idx_econ_ind_timestamp', table_name='economic_indicators')
    op.drop_index('idx_econ_ind_country_timestamp', table_name='economic_indicators')
    op.drop_index('idx_econ_ind_country', table_name='economic_indicators')
    op.drop_table('economic_indicators')
    op.drop_index(op.f('ix_baml_analyses_analysis_timestamp'), table_name='baml_analyses')
    op.drop_index('idx_baml_timestamp', table_name='baml_analyses')
    op.drop_table('baml_analyses')
    # ### end Alembic commands ###
