"""Add signal_distributions table for z-score percentile tracking

Revision ID: 98b1e2adc526
Revises: 48129a47f923
Create Date: 2025-10-17 18:52:14.323993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98b1e2adc526'
down_revision: Union[str, Sequence[str], None] = '48129a47f923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_distributions',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('distribution_date', sa.DateTime(timezone=True), nullable=False, comment='Date when this distribution was calculated'),
    sa.Column('sample_size', sa.Integer(), nullable=False, comment='Number of stocks in this distribution sample'),
    sa.Column('universe_description', sa.Text(), nullable=True, comment="Description of stock universe (e.g., 'S&P 500', 'European Large Cap', 'Trading212 Universe')"),
    sa.Column('mean', sa.Float(), nullable=False, comment='Mean of composite z-scores (should be ~0 for proper standardization)'),
    sa.Column('std', sa.Float(), nullable=False, comment='Standard deviation of composite z-scores (should be ~1 for proper standardization)'),
    sa.Column('median', sa.Float(), nullable=False, comment='Median of composite z-scores (should be ~0 for symmetric distribution)'),
    sa.Column('skewness', sa.Float(), nullable=True, comment='Skewness of distribution (0 = symmetric, positive = right-skewed)'),
    sa.Column('kurtosis', sa.Float(), nullable=True, comment='Kurtosis of distribution (3 = normal, higher = fat tails)'),
    sa.Column('p20', sa.Float(), nullable=False, comment='20th percentile threshold (bottom 20%)'),
    sa.Column('p40', sa.Float(), nullable=False, comment='40th percentile threshold (separates SMALL_DECLINE from NEUTRAL)'),
    sa.Column('p60', sa.Float(), nullable=False, comment='60th percentile threshold (separates NEUTRAL from SMALL_GAIN)'),
    sa.Column('p80', sa.Float(), nullable=False, comment='80th percentile threshold (top 20%)'),
    sa.Column('p20_deviation', sa.Float(), nullable=True, comment='Deviation from theoretical p20 (-0.84)'),
    sa.Column('p40_deviation', sa.Float(), nullable=True, comment='Deviation from theoretical p40 (-0.25)'),
    sa.Column('p60_deviation', sa.Float(), nullable=True, comment='Deviation from theoretical p60 (+0.25)'),
    sa.Column('p80_deviation', sa.Float(), nullable=True, comment='Deviation from theoretical p80 (+0.84)'),
    sa.Column('large_gain_pct', sa.Float(), nullable=True, comment='Percentage of stocks classified as LARGE_GAIN (expected: 20%)'),
    sa.Column('small_gain_pct', sa.Float(), nullable=True, comment='Percentage of stocks classified as SMALL_GAIN (expected: 20%)'),
    sa.Column('neutral_pct', sa.Float(), nullable=True, comment='Percentage of stocks classified as NEUTRAL (expected: 20%)'),
    sa.Column('small_decline_pct', sa.Float(), nullable=True, comment='Percentage of stocks classified as SMALL_DECLINE (expected: 20%)'),
    sa.Column('large_decline_pct', sa.Float(), nullable=True, comment='Percentage of stocks classified as LARGE_DECLINE (expected: 20%)'),
    sa.Column('max_bucket_deviation', sa.Float(), nullable=True, comment='Maximum deviation from 20% across all buckets (should be < 5%)'),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='Whether this distribution passes validation criteria'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this distribution should be used for classification (latest valid one)'),
    sa.Column('validation_notes', sa.Text(), nullable=True, comment='Notes on validation results (warnings, issues, etc.)'),
    sa.Column('min_zscore', sa.Float(), nullable=True, comment='Minimum z-score in sample'),
    sa.Column('max_zscore', sa.Float(), nullable=True, comment='Maximum z-score in sample'),
    sa.Column('raw_zscores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Optional: store raw z-score array or histogram bins for detailed analysis'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_distributions_active_date', 'signal_distributions', ['is_active', 'distribution_date'], unique=False)
    op.create_index('idx_signal_distributions_date', 'signal_distributions', ['distribution_date'], unique=False)
    op.create_index('idx_signal_distributions_sample_size', 'signal_distributions', ['sample_size'], unique=False)
    op.create_index('idx_signal_distributions_valid', 'signal_distributions', ['is_valid'], unique=False)
    op.create_index(op.f('ix_signal_distributions_distribution_date'), 'signal_distributions', ['distribution_date'], unique=False)
    op.create_index(op.f('ix_signal_distributions_is_active'), 'signal_distributions', ['is_active'], unique=False)
    op.create_index(op.f('ix_signal_distributions_is_valid'), 'signal_distributions', ['is_valid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_distributions_is_valid'), table_name='signal_distributions')
    op.drop_index(op.f('ix_signal_distributions_is_active'), table_name='signal_distributions')
    op.drop_index(op.f('ix_signal_distributions_distribution_date'), table_name='signal_distributions')
    op.drop_index('idx_signal_distributions_valid', table_name='signal_distributions')
    op.drop_index('idx_signal_distributions_sample_size', table_name='signal_distributions')
    op.drop_index('idx_signal_distributions_date', table_name='signal_distributions')
    op.drop_index('idx_signal_distributions_active_date', table_name='signal_distributions')
    op.drop_table('signal_distributions')
    # ### end Alembic commands ###
