"""fix_news_alignment_column_length

Revision ID: b2b970954c9c
Revises: 9415f504d41b
Create Date: 2025-10-13 15:29:58.512454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b970954c9c'
down_revision: Union[str, Sequence[str], None] = '9415f504d41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country_regime_assessments', 'news_alignment',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               comment='News alignment with quantitative signals',
               existing_comment="News alignment with quantitative signals: 'aligned', 'contradicts', 'mixed'",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country_regime_assessments', 'news_alignment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               comment="News alignment with quantitative signals: 'aligned', 'contradicts', 'mixed'",
               existing_comment='News alignment with quantitative signals',
               existing_nullable=True)
    # ### end Alembic commands ###
