"""extract_key_signals_gdp_and_inflation_momentum

Revision ID: dbd12f8c6ee4
Revises: 9e58a2966324
Create Date: 2025-10-13 16:32:39.346629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbd12f8c6ee4'
down_revision: Union[str, Sequence[str], None] = '9e58a2966324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_regime_assessments', sa.Column('gdp_momentum', sa.String(length=50), nullable=True, comment="GDP momentum signal: 'strong', 'moderate', 'weak', 'contracting'"))
    op.add_column('country_regime_assessments', sa.Column('inflation_momentum', sa.String(length=50), nullable=True, comment="Inflation momentum signal: 'accelerating', 'stable', 'subdued', 'falling'"))
    op.drop_column('country_regime_assessments', 'key_signals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_regime_assessments', sa.Column('key_signals', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Key signals driving classification'))
    op.drop_column('country_regime_assessments', 'inflation_momentum')
    op.drop_column('country_regime_assessments', 'gdp_momentum')
    # ### end Alembic commands ###
