"""Remove filter columns and clean data

Revision ID: e7998a410cec
Revises: cdf65b4bcc4a
Create Date: 2025-10-13 14:09:52.088758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7998a410cec'
down_revision: Union[str, Sequence[str], None] = 'cdf65b4bcc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and clean data."""
    # STEP 1: Delete instruments that didn't pass filters (before dropping columns)
    print("Cleaning up filtered-out instruments...")
    op.execute("""
        DELETE FROM instruments
        WHERE filter_status IN ('filtered_out', 'no_ticker', 'data_fetch_failed', 'error', 'pending')
    """)

    # STEP 2: Drop indexes
    op.drop_index(op.f('idx_instruments_data_quality'), table_name='instruments')
    op.drop_index(op.f('idx_instruments_filter_status'), table_name='instruments')
    op.drop_index(op.f('idx_instruments_passed_with_yf'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_filter_status'), table_name='instruments')

    # STEP 3: Drop columns
    op.drop_column('instruments', 'filter_status')
    op.drop_column('instruments', 'data_completeness_pct')
    op.drop_column('instruments', 'has_yfinance_data')
    op.drop_column('instruments', 'data_points')
    op.drop_column('instruments', 'filter_reason')
    op.drop_column('instruments', 'years_available')
    op.drop_column('instruments', 'has_sufficient_history')

    print("Migration complete! Only instruments with filter_status='passed' remain.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('has_sufficient_history', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Whether stock has ≥5 years of historical data'))
    op.add_column('instruments', sa.Column('years_available', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Years of historical data available'))
    op.add_column('instruments', sa.Column('filter_reason', sa.TEXT(), autoincrement=False, nullable=True, comment="Reason for filtering out (if filter_status = 'filtered_out')"))
    op.add_column('instruments', sa.Column('data_points', sa.INTEGER(), autoincrement=False, nullable=True, comment='Number of historical data points (trading days)'))
    op.add_column('instruments', sa.Column('has_yfinance_data', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether yfinance data is available'))
    op.add_column('instruments', sa.Column('data_completeness_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Percentage of factor components available (0-100)'))
    op.add_column('instruments', sa.Column('filter_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment="Filter status: 'passed', 'no_ticker', 'data_fetch_failed', 'filtered_out', 'error'"))
    op.create_index(op.f('ix_instruments_filter_status'), 'instruments', ['filter_status'], unique=False)
    op.create_index(op.f('idx_instruments_passed_with_yf'), 'instruments', ['filter_status', 'yfinance_ticker'], unique=False)
    op.create_index(op.f('idx_instruments_filter_status'), 'instruments', ['filter_status'], unique=False)
    op.create_index(op.f('idx_instruments_data_quality'), 'instruments', ['has_yfinance_data', 'data_completeness_pct'], unique=False)
    # ### end Alembic commands ###
