"""add_macro_regime_tables

Revision ID: ecf0a9a2bfdc
Revises: 1c95f3fd3da4
Create Date: 2026-01-30 17:32:39.681909

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ecf0a9a2bfdc"
down_revision: str | Sequence[str] | None = "1c95f3fd3da4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ``upgrade()`` above is a bare auto-generated stub — it never created
    # any ``macro_regime`` objects (no other revision references them
    # either), so there is nothing here to reverse. A no-op is the correct
    # implementation, not a raise: raising breaks `alembic downgrade` for
    # every revision that crosses this one, turning a harmless pass-through
    # into a hard failure for no schema reason.
    pass
